### ISSUE TITLE
Unable to parse copy files under relative copybook path.

### ISSUE THREAD

**Issue by ebat79** [spgennard/vscode_cobol#100]
**Describe the bug**
When copybook directory is relative to the path of the ".cbl" source file an "Invalid Search directory" message appear.

**To Reproduce**
I attach a [zip file](https://mega.nz/#!Hk4ECYpJ!wh1J1lQ-YEV4wcKMsc_1mam5dX-7Ur0opU81KszCmpc) containing an example workspace.

**Expected behavior**
Searching for copy files to cache for.
Where? Relative to the path where the source file exist.
When? When opening an ACUCOBOL source file.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/1749453/69225963-a4b07000-0b7f-11ea-988f-3a9b86b12ff0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - COBOL Plugin version 5.7.21

**What user & workspace settings are being used?:**
- See the zip attachment [tmp_moduli.zip](https://mega.nz/#!Hk4ECYpJ!wh1J1lQ-YEV4wcKMsc_1mam5dX-7Ur0opU81KszCmpc)

**Additional context**
Is it possible to add an experimental flag to the plugin settings for implementing relative path scanning?
Precedent close issue relative to this was #94 .

**Comment by spgennard** [comment]
The structure of the example requires two workspaces, one for the 2018 &2019.

The workspaces are placed in the 2018/2019 structures and each workspace has its own cache, so it does not clash.

Using one workspace for duplicate copybooks is not going to work with the cache.

Sample Fixed workspace projects
[issue100.zip](https://github.com/spgennard/vscode_cobol/files/3871024/issue100.zip)

**Comment by ebat79** [comment]
Creating a workspace for each year involves extra work every year but makes sense.

Actually my purpose is to use the same structure as "copypath" defined in the build file. This is the copypath defined in the batch file of a project that I'm contributing to:

`SET COPYPATH=.\;..\txt;..\fd;..\iscbl;..\730;\workspace\ws-atf\fd;\workspace\ws-atf\txt;\workspace\fd;\workspace\txt;\workspace\bmp;\workspace\ws-con\fd;\workspace\ws-sys\txt;\workspace\ws-f24\txt
`

**Comment by spgennard** [comment]
The workspaces included in the above zips are identical because of the use relative directories.

I have thought about allowing the use of multi-path environment variables if this was done the copybookdirs would become:

```json
    "coboleditor.copybookdirs": [
        ".",
        "$COPYPATH"
    ]
```

If this is good enough, then I will change the title of the issue and look at this.

**Comment by ebat79** [comment]
I saw what you corrected and realized that the paths are actually relative to the workspace and not to the source so I adjusted accordingly, creating separate workspaces and workspace-related paths. That's enough for me.
That said, the only thing that asks you to improve is the speed of research in large projects.

**Comment by spgennard** [comment]
Great you have a solution, so with that I will close it.

But for your information:

My short-medium terms plans are to move the parsing into a language server layer (out of process),
so then make the parsing more on-demand and do some serious performance analysis on it.
