### ISSUE TITLE
New line tab stop

### ISSUE THREAD

**Issue by gmonteeeiro** [spgennard/vscode_cobol#103]
**Describe the bug**
When you press enter to get a new row, vscode goes to column 1 instead of staying in the current column.

**To Reproduce**
Just press enter do get a new row

**Expected behavior**
Expected to continue in current column rather than back to 1

**Screenshots**
![Gif example](https://i.imgur.com/QlOwFLI.gif)
(see the end of gif)

**Desktop:**
 - OS: Windows 10

**Comment by spgennard** [comment]
Have you tried changing the settings?  (editor.autoIndent)

eg:

```json
           "[COBOL]": {
                "editor.autoIndent": "full",
...
```

**Comment by spgennard** [comment]
Any comments?

**Comment by spgennard** [comment]
Okay, I know if you set the above setting it works.   

If you feel otherwise more information/settings are required, so closing now due to no comments from user.
