### ISSUE TITLE
[Enhancement] Accept additional extensions ?

### ISSUE THREAD

**Issue by bvargin-dev** [spgennard/vscode_cobol#104]
Hi, first THANKS a lot for this plugin.

I'm not personally good in JS, that's why I prefer to summit the demand.

Is it possible (if not already) to take custom extensions per language. By example, for our copylib, the files are named ".lib" and files are not recognized even if  they are added to the settings "coboleditor.copybookexts".

Currently to make it worked, the file package.json is modified at "languages"."extensions" level.
```
 {
                "id": "COBOL",
                "aliases": [
                ...
                "extensions": [
                    ".cbl",
                    ".cblsrce",
                ...
                    ".wks",
                    ".pco",
                    ".lib"
                ...
}
```
The idea, is to have a setting like copybookexts which add values to the extension list.

Thanks in advance for your help or recommendation.
Best Regards.

**Comment by spgennard** [comment]
You don't need to change any extension to assign a new file association.

**Adding a file extension to a language**

You can add new file extensions to an existing language with the [files.associations setting](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file).

For example:

In your settings.json:

```json
 "files.associations": {
    "*.lib": "cobol",
    "*.pco": "cobol",
    "*.lib*": "cobol"
  }
```

(Above is a guess given your requirements).

Lastly, I have provided an example on how you can create your own custom *COBOL* extension based on my extension.   You can git the github area [[here](https://github.com/spgennard/vscode_custom_cobol)].

**Comment by bvargin-dev** [comment]
Hi,

Thanks a lot for the answer. I have to put "COBOL" in upper case and it worked like a charm.
^^
