### ISSUE TITLE
Comment lines colourization broken

### ISSUE THREAD

**Issue by ebat79** [spgennard/vscode_cobol#106]
**Describe the bug**
AcuCobol: line comment with the "*" character in column 7 does not format properly when "." character is present in the first 6 column.

**To Reproduce**
Here an exemple:
```
v.2000*             IF  WK-TUTTI-2-BONUS = 0 OR
v.2000*                 WK-TUTTI-2-BONUS = 1
v.2000*                 IF  R3DO-IMPORTO(26) NOT = 0
v.2000*                     MOVE 2 TO WK-TUTTI-2-BONUS
v.2000*                 ELSE
v.2000*                     IF  WK-BONUS-IRPEF-NR NOT = 0
v.2000*                         MOVE 1 TO WK-TUTTI-2-BONUS
v.2000*                     END-IF
      *                 END-IF
      *             END-IF

```
**Expected behavior**
All the line formatted like comments.

**Desktop (please complete the following information):**
 - OS: WIN10
 - Version 1903

**Screenshot**
![Snipaste_2020-02-18_15-51-30](https://user-images.githubusercontent.com/1749453/74747089-aa911c80-5266-11ea-8ecf-5fdf4cdcdae2.png)

**Comment by spgennard** [comment]
fixed
