### ISSUE TITLE
How to add own set of statements?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#107]
COBOL is often used with in-house preprocessors, many use self-defined commands that are replaced before the actual COBOL compilation is done.
Therefore it would be good to know how to add those. Sample:

```
#SOME-STUFF(parameter, parameter
  parameter)
```

```
;COMMAND parameter keyword parameter optional-keyword
```

Ideally the following would be possible:

* define those commands and their format in a separate file (ideally like a "dialect" so different files can use different dialects)
* possibly with an extended format (like number and kind of parameters [variables, set of keywords, ...], online-help [as it is provided for the CBL_routines],  possibly with a defined end-symbol, in the first sample a `)`, ...)
* have them included in syntax-highlighting and code-completion

**Comment by spgennard** [comment]
Take a look @ https://github.com/spgennard/vscode_custom_cobol

**Comment by GitMensch** [comment]
Thank you, this is really useful. Could you add a note to the README about this possibility. providing the link?
