### ISSUE TITLE
FR: context specific code completion

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#108]
_remark: I may just *use* it wrong, in this case this may be considered as a documentation issue._

things done:

* entered `goto `
* pressed [CTRL]+[SPACE]

expected:

list of paragraphs (ideally ordered, first in the current section if any, then in all others)

current result:

all words in the current source file are shown (COBOL identifiers, words in comments)

Same issue with "more common" statements like `subtract` - there is an auto-completion leading to `subtract a from b giving c` but when you move the cursor to the "a" and press [CTRL]+[SPACE] you do get the complete word list again (expected: identifiers, ideally those in the previous lines up to the last paragraph first, then all in the order defined in the `DATA DIVISION`.

As "peek definition" is implemented and works fine I guess the actual COBOL identifiers are known to the extension already.

**Comment by spgennard** [comment]
Have explored the "editor -> suguest" features in the editor, this will allow you to turn down the features depending on your own requirements.

**Comment by GitMensch** [comment]
> 
> 
> Have explored the "editor -> suguest" features in the editor, this will allow you to turn down the features depending on your own requirements.

How do I reach this? Wouldn't it be useful if the extension would be context-sensitive in its suggestions or does it need a deeper understanding of the code (language server implementation) before?

**Comment by spgennard** [comment]
Visual Studio Code has two ways of providing language support, first by APIs and the second via the lsp.   This extension uses the APIs.. both provide the same functionality.    

The APIs came first and the lsp came later.

I have no plans to recode the extension to make it include a COBOL lsp, as it gives no immediate benefit to the user.

Context-sensitive suggestions are possible but I suspect the performance of node & parser might not be up to the job.   I already have some source files that are taking 20-30 seconds to parse
which makes it not very useful if this information was used to provide the feature.

**Comment by spgennard** [comment]
If you enable the experimental feature flag, you can have a play around with.

Support for add/move/perform/to/go to has been added.

**Comment by GitMensch** [comment]
I've just tried:

* updated the extension, it now says to be at 6.2.4 (Changelog says different)
* enable user-setting coboletor:experimental_features
* reload
* enter `move p` --> still all paragraphs are shown that start with "p"

maybe I have mis-read this?

**Comment by spgennard** [comment]
You need to exit/restart the plugin.

It is experiential and I am in doubt about its use in medium to large files but you can see it working below.

![image](https://user-images.githubusercontent.com/5991192/80458116-38088100-8928-11ea-896a-3635968aef3e.png)

**Comment by spgennard** [comment]
This is now as complete as I can make it.

**Comment by GitMensch** [comment]
OK, that's the "linting" option. I do see that it works in general - one question @spgennard: the typed suggestions only show up after the first character is entered - can you also show it when `MOVE ` + [CTRL]+[SPACE] is used?
