### ISSUE TITLE
FR: context specific code highlighting (statements)

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#109]
If the cursor is on an identifier all other uses (including in the comments) of this identifier is "highlighted". That is marvelous (I _guess_ that is [mostly] a vscode feature already) and really useful.

"But"... the same happens on statements, for example when the cursor is at `UNTIL` then all other `UNTIL` are highlighted. It would be much more helpful if the `PERFORM` (and possible) `END-PERFORM` along with possible other clauses of the current statement would be highlighted (similar for `EVALUATE` -> mark related `WHEN` and possible `WHEN OTHER`+`END-EVALUATE`.

**Comment by spgennard** [comment]
Sorry, I have no control over this, it appears to be done on text rather than in the context of a language.

I agree it can be annoying but it can also be useful too.
