### ISSUE TITLE
comment lines break code-folding

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#110]
sample code:
```cobol
           evaluate true
             *> checks stuff
              when stuff
                 perform do-stuff
                 perform do-more-stuff
             *> checks quite different stuff
              when stuffy
                 perform do-stuff
              when other
                 goback
           end-evaluate
```

this has the expected code folding (you can fold each `WHEN` and also the complete `EVALUATE`):
![working code-folding](https://user-images.githubusercontent.com/6699539/78900385-10d03980-7a77-11ea-9e46-0a67b26ac738.png)

But if you now change the comments to a comment line the folding gets broken:

```cobol
           evaluate true
      *       checks stuff
              when stuff
                 perform do-stuff
      *          important: more stuff do do
                 perform do-more-stuff
      *       checks quite different stuff
              when stuffy
                 perform do-stuff
              when other
                 goback
           end-evaluate
```

![grafik](https://user-images.githubusercontent.com/6699539/78900669-77edee00-7a77-11ea-9fac-1df7d715d967.png)

Expected: line comments are folding wise handled identically to inline comments

**Comment by spgennard** [comment]
This is a restriction in vscode, it only has the notion of two types of comments styles and you can only have one of each.

The first type is a line comment and this is set to "*>", the second is block comments which do not exist in COBOL.

A block comment has a "start" token and an "end" token.

Because of this vscode has no idea what a fixed format comment is, hence it gets confused.

So, I am afraid this will never get fixed until vscode changes.

**Comment by spgennard** [comment]
One after thought, it you are using Micro Focus COBOL you can create your own custom
regions, for example:

      $region evaluate-true-stuff
           evaluate true
      *>      checks stuff
              when stuff
                 perform do-stuff
      *>         important: more stuff do do
                 perform do-more-stuff
      *>      checks quite different stuff
              when stuffy
                 perform do-stuff
              when other
                 goback
           end-evaluate
      $end-region

**Comment by spgennard** [comment]
The vscode docs on folding explains the reason why, it is basically because of the fixed line 
comment not being the same indent level.


      Indentation-based folding: This is VS Code's default folding behavior. 
      When it sees two lines of the same indentation level, it creates a 
      folding marker that allows you to collapse that region.

**Comment by GitMensch** [comment]
@spgennard if this is vscode's default folding behavior you may override it - actually code with bad indentation should be foldable, too. Can you re-open this issue tracking this FR?

**Comment by spgennard** [comment]
I debugged through vscode and i found no extension points, so you will need
to request an extension point from vscode before I can consider it.
