### ISSUE TITLE
FR for breadcrumb view: include PROGRAM/FUNCTION

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#113]
With the sample code from #112 we have a breadcrumb like
`file -> PROCEDURE DIVISION -> SOME-PAR`.

It would be nice to have also the defined program/function shown, some samples:

```cobol
PROGRAM-ID. prog1.
```
```cobol
PROGRAM-ID. "prog2".
```
```cobol
PROGRAM-ID. prog3 as 'SOMEPROG'.
```
```cobol
FUNCTION-ID. 'func.'
```

I suggest to leave both the literals and the case as it is, leading to the following possible breadcrumbs:

`file -> PROGRAM prog1 -> PROCEDURE DIVISION -> SOME-PAR`
`file -> PROGRAM "prog2" -> PROCEDURE DIVISION -> SOME-PAR`
`file -> PROGRAM prog3 ('SOMEPROG') -> PROCEDURE DIVISION -> SOME-PAR` or
`file -> PROGRAM prog3 as 'SOMEPROG' -> PROCEDURE DIVISION -> SOME-PAR`
`file -> FUNCTION 'func' -> PROCEDURE DIVISION -> SOME-PAR`

Especially when you have a file with multiple program/function definitions in this helps a lot, especially if the sub-content is moved to a sub, currently a multi-program source has the following breadcrumb options showing up when multiple programs/functions are defined in one source:

![multi-program source](https://user-images.githubusercontent.com/6699539/79388200-370d4200-7f6d-11ea-8278-6fb10ceda0c0.png)

**Comment by spgennard** [comment]
Changes already made
