### ISSUE TITLE
bugs/FR related to the outline

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#115]
The outline for this sample source:
```cobol
       IDENTIFICATION   DIVISION.
       PROGRAM-ID.      prog.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
           SOURCE-COMPUTER. mine WITH DEBUGGING MODE.
       INPUT-OUTPUT     SECTION.
       FILE-CONTROL.
       SELECT TEST-FILE ASSIGN "./TEST-FILE".
       DATA             DIVISION.
       FILE             SECTION.
       FD  TEST-FILE.
       01  TEST-REC     PIC X(40).
       01  TEST-REC2.
           03 FILLER    PIC X.
           03 TEST-REC2-DATA PIC X(39).
       PROCEDURE        DIVISION.
       DECLARATIVES.
       TEST-DEBUG SECTION.
           USE FOR DEBUGGING ON TEST-FILE.
           DISPLAY DEBUG-ITEM "|" END-DISPLAY.
       END DECLARATIVES.
       SOME-PAR.
           OPEN  OUTPUT TEST-FILE.
           WRITE TEST-REC FROM "DEF".
           CLOSE TEST-FILE.
        OTHER-PAR.
           OPEN  INPUT TEST-FILE.
           READ TEST-FILE.
           CLOSE TEST-FILE.
           STOP RUN.
```

looks currently like:
![outline](https://user-images.githubusercontent.com/6699539/79391032-10510a80-7f71-11ea-8817-4a634ace4f57.png)

Things that would be nice to be improved:

* `TEST-REC` and `TEST-REC2` should be both subordinate to the `FD` `TEST-FILE`, not on the same level (note: the FD [or SD] should be stopped after the first separator, stuff like the `LINAGE` clause, `CODE-SET` clause and others are "contents" of the FD/SD, not the FD/SD itself)
* `TEST-REC2-DATA` should be below `TEST-REC2`, not on the same level
* inclusion of `DECLARATIVES` (see #112) would be nice, either "before" `PROCEDURE DIVISION` or subordinate to it
* inclusion of the program/function (see #113)
* more different icons, maybe (I have no clue what different icons are available...):
   * one for program/function; which we have
   * one for the `DIVISION`s, possibly extra or with the same icon: `DECLARATIVES`
   * one for the `SECTION`s
   * _possibly_ special icons for each of `FILE SECTION`, `WORKING-STORAGE SECTION`, `LOCAL-STORAGE SECTION`, `SCREEN SECTION` and `LINKAGE SECTION`
   * one for the paragraphs
   * one for the FD/SDs (done with 6.1.3)
   * one for the records (level 01/77 items); done
   * another for `OCCURS` items
   * _possibly_ another for sub-items
   * _possibly_ one for conditional-items (level 88 items)
   * one for constants (level 78 items [done] and `CONSTANT AS` [done with 6.1.5])

**Comment by spgennard** [comment]
Sorry,  ability to choose different icons, is limited to the types of symbols provided in the outline view, these are documented @  https://vshaxe.github.io/vscode-extern/vscode/SymbolKind.html

**Comment by GitMensch** [comment]
Both the [source](https://github.com/vshaxe/vscode-extern/blob/master/src/vscode/SymbolKind.hx) of the reference you showed and [from vsCode](https://github.com/microsoft/vscode/blob/1ed53d174f641d7b7397faa05be528d00b673120/src/vs/editor/common/modes.ts#L937) lists 25 types (which we do not have reached yet) and with https://github.com/microsoft/vscode/issues/23927 we additional have `SymbolTag`s, for a minimal use of it see the addition of the deprecation tag in this [random commit](https://github.com/Dart-Code/Dart-Code/commit/2426a1a623d83b45e68fc5526a1cba00b6ff2222).

Conclusion: the existing `SymbolKind`s and SymbolTag`s should be inspected and applied to the list above.

**Comment by spgennard** [comment]
I am already using a large amount of them,  most are not applicable to
programs but are in classes, enum, interfaces, valuetypes, partial classes
etc..

These icons have to match the type of symbol as it is linked to other
functionality.. ie: it's not just a presentation icon

**Comment by GitMensch** [comment]
I see. Which icons are still free?

**Comment by spgennard** [comment]
These are the ones, I will be implemented when I continue to add more OO related items:
 - Module, Namespace, Package, String, Boolean, Array, Object, EnumMember, Event, Operator, TypeParameter, Key

These are the ones that I don't think I will use:
- Number, Null

**Comment by spgennard** [comment]
The request/requirements for this is unclear, please review existing support and create specific issues rather one with many issues, some of which are not fixable or limitations

**Comment by GitMensch** [comment]
@spgennard said

> Sorry, ability to choose different icons, is limited to the types of symbols provided in the outline view, these are documented @ https://vshaxe.github.io/vscode-extern/vscode/SymbolKind.html

I'm not sure if this applies to the outline, view, too - for tree views (with a dependency to the most current vscode api) one can use [codicon](https://microsoft.github.io/vscode-codicons/dist/codicon.html), see [October 2020 Notes](https://code.visualstudio.com/updates/v1_51#_codicon-colors-in-trees). I _guess_ the new The new [ThemeIcon color API](https://github.com/microsoft/vscode/blob/5dbb54cab77218f8f722c49fb10dfe44fd909298/src/vs/vscode.d.ts#L821-L826) does not only apply to trees and messages but also to the outline view.
