### ISSUE TITLE
improve intrinsic function support

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#119]
The first part is maybe a de-confusing.
Currently there are two places where functions are defined in this repository, first the {function definition in cobol.json][1] (twice, one in lower-case and one in upper-case to keep the case of "function"/"FUNCTION" in line with the actual function name; very limited ) and second the highlighting in the [entcobol language definition][2] (likely complete for Enterprise COBOL but some functions supported by COBOL 2002 and newer or different dialects is not included).

I think it would be good to have this 2*1+1 definitions only on one place (not depending on the dialect in use).

The second part is about teaching the extension how many parameters the functions have, what they are used for and what the function actually does.
You can find a list I've created for this in 2018 at https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/APIs/cobol.xml (all entries with func="yes") where you can get the necessary data from.

[1]:https://github.com/spgennard/vscode_cobol/blob/ea4ac1686bfa6e458ce1211150ae37df22f94728/snippets/cobol.json#L685
[2]:https://github.com/spgennard/vscode_cobol/blob/6ff00e521e25c7e51f32b348db731f8c21df51c2/syntaxes/enterprisecobol.tmLanguage.json#L464

**Comment by spgennard** [comment]
Visual Studo code requires the snippets to be defined in one place and the syntax grammar in another, so it will be inevitable that duplication will occur.

Uppercase/lowercase is provided as it is currently the only way of handling the matching of the snippet to the case of the code.   It's just how vs code is.. we just have to work with its limitations.

The second part, you are welcome to provide snippets or use your .xml to generate them.

**Comment by spgennard** [comment]
more cross-platform snippets added
