### ISSUE TITLE
FR include a documentational note to all settings

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#120]
With the current version the following would be good to add/extend:

* coboleditor:cache_metadata: what does this actually mean and where is it stored
* coboleditor:comment_line: ???
* coboleditor:diagnostic: ???
* coboleditor:enable_tabstop: ???
* coboleditor:experimental_features: ???  (at least give a hint to the description)
* coboleditor:file_format: explanation is well, just fix the double "m" in the format... and possibly give a short sample here
* coboleditor:fuzzy_variable_search: What means "fuzzy" and "legacy" in this case?
* coboleditor:ignorecolumn_b_onwards: I *guess* this is about ignoring everything after column 72? Is there an option to move the column? In any case you may want to consider naming it differently, I suggest to go with what COBOL 2002+ says "margin_right", especially if you have a new setting numeric setting "margin_right" that can be adjusted, then you don't need the setting at all (if my guess was correct)
* coboleditor:linter: Is it disabled by default and we can only limit it with this setting? What does linting means in this context (to the user)?
* coboleditor:margin: I *guess* that is about showing the margin, but no, cannot be as I have it un-ticked but have margin drawn.
* coboleditor:tabstops: What format is expected?

**Comment by spgennard** [comment]
A lot of these settings are present but are set dynamically and for internal use.

Documentation is not a priority for settings as I prefer to have good sensible defaults, so no settings need to be set.

If I consider a setting of use to the general public, I will document it.

**Comment by GitMensch** [comment]
Hm, ... so what are these settings about?

**Comment by spgennard** [comment]
I have a simple policy, if I document it, I support it and these are
undocumented because they may change or simply vanish.
