### ISSUE TITLE
Can JCL language id be changed to lower case "jcl"

### ISSUE THREAD

**Issue by travatine** [spgennard/vscode_cobol#127]
Hi,

I'm writing an extension that contributes "JCL" snippets.
```
"contributes": {
		"snippets": [
			{
				"language": "jcl",
				"path": "./snippets/snippets.json"
			}
		]
	},
```

I've noticed that this extension defines JCL with language id "JCL".
Whilst a number of other VS code extensions use the id "jcl" ( lower case) .

The ["VS Code" docs](https://code.visualstudio.com/docs/languages/identifiers) suggest it is a good idea to use "lower case" for langauge ids.
```
...

New identifier guidelines#
When defining a new language identifier, use the following guidelines:

Use the lowercased programming language name.

...
```

It'd be great if this extension could use a lower case id "jcl";

That way my snippets could work with multiple vs code extensions.

Thanks for considering this feature request.
Travis

**Comment by spgennard** [comment]
The extension already has a lower case alias for the language, so your snippets should be picked up.

```json
            {
                "id": "JCL",
                "aliases": [
                    "JCL",
                    "jcl"
                ],
                "extensions": [
                    ".jcl",
                    ".job",
                    ".cntl",
                    ".prc",
                    ".proc"
                ],
                "configuration": "./jcl.configuration.json"
            },
```

**Comment by travatine** [comment]
Hi,

Thanks for the quick reply.

I get this "unknown language 'jcl'" error when I open a JCL file:

![image](https://user-images.githubusercontent.com/17565183/81247106-c200ca00-904b-11ea-9199-d0a2525beb70.png)

My package json looks like:
```
 "contributes": {
        "snippets": [
            {
                "language": "jcl",
                "path": "./snippets/snippets.code-snippets"
            }
        ]
    }
```

So it looks like  "contributes.snippets" uses the "id" of the language rather than alias?

This page ( https://code.visualstudio.com/docs/languages/identifiers ) says;

> "Note that casing matters for exact identifier matching ('Markdown' != 'markdown')"

**Comment by spgennard** [comment]
Ideally, I agree it would be nice to change but then I end up breaking one that uses it in uppercase.

I might be wrong but I think you can add more than one language id separated by a comma.

```json
 "contributes": {
        "snippets": [
            {
                "language": "jcl,JCL",
                "path": "./snippets/snippets.code-snippets"
            }
        ]
    }
```

**Comment by travatine** [comment]
Thanks
