### ISSUE TITLE
issues with "process files in workspace for metadata"

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#129]
Given the following (workspace) settings:

```json
{
  "files.associations": {
    "*.PRG": "COBOL",
    "*.LST": "COBOL"
  },
  "files.autoGuessEncoding": true,
  "projectCommonFolder": "${workspaceFolder}/../Release Components/common",
  "files.autoGuessEncoding": true,
  "coboleditor.copybookexts": [
    "cpy",
    "CPY"
  ],
  "coboleditor.copybooks_nested": true,
  "coboleditor.pre_parse_line_limit": 30,
  "coboleditor.copybookdirs": [
    ".",
    "${workspaceFolder}",
    "${workspaceFolder}/src/cpy/common",
    "${workspaceFolder}/src/cpy/files",
    "${workspaceFolder}/src/cpy/screens",
    "${projectCommonFolder}/src/cpy/common",
    "${projectCommonFolder}/src/cpy/files",
    "${projectCommonFolder}/src/cpy/screens"
  ],
  "coboleditor.experimential_features": true,
  "coboleditor.cache_metadata": "on",
}
```

And executing the plugin function "process files in workspace for metadate" I've received the follwing output:

~~~
   CopyBook: 2009-06-09 (not found)
   CopyBook: . => c:\dev\Project
Error:File failed! (c:\dev\Project)
Error: EISDIR: illegal operation on a directory, read
	at Object.readSync (fs.js:513:3)
	at LineByLine._readChunk (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\node_modules\n-readlines\readlines.js:92:28)
	at LineByLine.next (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\node_modules\n-readlines\readlines.js:130:30)
	at new FileSourceHandler (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\out\FileSourceHandler.js:27:33)
	at Function.processOneFile (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\out\cobolquickparse.js:454:45)
	at new COBOLQuickParse (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\out\cobolquickparse.js:396:29)
	at Function.processFileInDirectory (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\out\vscobolquickparse.js:126:35)
	at Function.processAllFilesDirectory (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\out\vscobolquickparse.js:112:31)
	at Function.processAllFilesInWorkspaces (c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\out\vscobolquickparse.js:89:39)
	at c:\Users\me\.vscode-oss\extensions\bitlang.cobol-6.2.16\out\extension.js:270:37
	at _executeContributedCommand (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:549:220)
	at _.$executeContributedCommand (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:549:595)
	at p._doInvokeHandler (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:464)
	at p._invokeHandler (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:156)
	at p._receiveRequest (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:817)
	at p._receiveOneMessage (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:685:623)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:683:791
	at l.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:851:104
	at l.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at t.PersistentProtocol._receiveMessage (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:717)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:897
	at l.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at p.acceptChunk (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:897)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:249
	at Socket.t (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:197:232)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
   CopyBook: directories (not found)
 - Processing file : c:\dev\Project\ChangeLog
Completed scanning all COBOL files in workspace              (114.34ms)
~~~

* I have no clue where this "CopyBook 2009-06-09" entry comes from
* the project folder and the ChangeLog file are obviously no CopyBooks --> in general: I think it would be reasonable to only check files that match the `coboleditor.copybookexts` as copybooks

_Side question_ here: does this setting above look reasonable?

**Comment by spgennard** [comment]
The directory "." is unexpected and is a directory in *nix.

Logically, the inclusion of "." makes no sense, as the current directory may not be as you expect and can change during the life span of your editing session.    

This is because current directory can be changed by any extension or vscode itself at any time.

**Comment by GitMensch** [comment]
> The directory "." is unexpected and is a directory in *nix.

`coboleditor.copybookdirs` is a setting of directories, isn't it?

> Logically, the inclusion of "." makes no sense, as the current directory may not be as you expect and can change during the life span of your editing session.

I agree that this is unreasonable for cached metadata to be used. But for a file that is currently open it would be useful. As it isn't needed in my current scenario I'll just drop it (the copybooks are just allowed to be in specific files and should always be search in exactly this order), for "general" your remove from the defaults and skipping with 71cfba8 looks fine.

> I need to review this and adjust.

Thank you, please also review the indexing as this should only use files that are part of the registered *cobol* associations and additional "as copybook" only use the ones listed in `coboleditor.copybookexts`. Thanks!

**Comment by spgennard** [comment]
The following were not picked up as invalid directories but will be soon.

The first item: ${workspaceFolder}" can be removed, as this is always searched.

${workspaceFolder}/src/cpy/common should be src/cpy/common
and the same for the other ${workspaceFolder} items

I am unsure where ${projectCommonFolder} comes from.

```json
    "${workspaceFolder}",
    "${workspaceFolder}/src/cpy/common",
    "${workspaceFolder}/src/cpy/files",
    "${workspaceFolder}/src/cpy/screens",
    "${projectCommonFolder}/src/cpy/common",
    "${projectCommonFolder}/src/cpy/files",
    "${projectCommonFolder}/src/cpy/screens"
```

**Comment by GitMensch** [comment]
The folder is defined above (next to the workspace folder), so I'll start that with ../

**Comment by spgennard** [comment]
Remember vscode has moved to multi-root workspaces, so you can have more than one folders, so "../" might not give you the desired behavior if multiple workspace folders are used or cause the search to search into unexpected places.

**Comment by GitMensch** [comment]
As long as that's a multi-workspace-folder-only issue I don't care, but that highlights another point even more: support to specify a full path should be given and the default (and in this case `${workspaceFolder}` is also fine, even when it comes with a warning "not supported for multi-workspace"]).
Support for relative paths should be possible, too, but always default to the file that is currently processed, *not* the workspaceFolder (one could still use relative paths to it as long as one starts with `${workspaceFolder}`).

Do you agree?

**Comment by spgennard** [comment]
${workspaceFolder} is 1+ directories, so "../" will be relative to every directory in the workspace.

You can already use a hardcode path or just delegate the search to multi-path environment variable.
eg: "$PATH".   Which would search everywhere on the $PATH, more likely you could have $COBCOPYBOOKDIR that is setup outside of vscode but used in vscode.

**Comment by GitMensch** [comment]
Hm, so I understand that relative paths are relative paths now to every folder in the workspace (for a reason I don't understand), is that correct? In this case `../` would be just bad (in my scenario).
The point of using only relative paths starting with `${workspaceFolder}` was that you do not have to setup *anything* outside, just install a vscode based editor, clone/checkout the workspace from VCS,  open the workspace it as folder, install the suggested extensions (including this one) and you're finished, no matter where you did the clone/checkout.

I'm really confused now and think even more than on the beginning that it would be best for this scenario to start all `coboleditor.copybookdirs` with `${workspaceFolder}`, correct?
If this isn't supported (I am still not sure) then is there any other option that does not mean to tinker with the user's environment?

**Comment by GitMensch** [comment]
Just to reference what I was looking at: https://code.visualstudio.com/docs/editor/variables-reference

> `${workspaceFolder}` - the path of the folder opened in VS Code

... by "open folder", which is exactly the scenario I have

**Comment by spgennard** [comment]
The opening text says, it all..   It is only available in debugging and task configuration files.

```text
Visual Studio Code supports variable substitution in Debugging and Task configuration files as well as some select settings. Variable substitution is supported inside key and value strings in launch.json and tasks.json files using ${variableName} syntax.
```

**Comment by GitMensch** [comment]
After [this shocking revelation](https://code.visualstudio.com/docs/editor/variables-reference#_is-variable-substitution-supported-in-user-and-workspace-settings)... does the plugin have access to `${workspaceFolder}` and could replace it on its own in its settings?

**Comment by spgennard** [comment]
The plugin, already loops through all the workspace folders, so it is not required.

What it is doing is:

 ```text
 foreach folder in workspaceFolders
  foreach copybookdir in copybookdirs
    possible path = path.join(folder,copybookdir)
    possible file = path.join(possble path, copybook file)
```

You can see the actual search path in the COBOL console channel.

**Comment by GitMensch** [comment]
> The plugin, already loops through all the workspace folders

We have previously seen that this - without any exception-part is not ideal as it prevents the use of absolute names. As this is only pseudo-code I could not check if there is a check, but I'd suggest something like the following:

```
foreach copybookdir in copybookdirs
  if inString(copybookdir, "${")
     copybookdir = replaceEnv(copybookdir);
     copybookdir = replaceWorkSpaceFolder(copybookdir);
  if isAbsolute(copybookdir)
    possible file = path.join(copybookdir, copybook file)
  else
    foreach folder in workspaceFolders
      possible path = path.join(folder,copybookdir)
      possible file = path.join(possble path, copybook file)
```

**Comment by spgennard** [comment]
It is already expanding "$" env's, remember I said it expands "$PATH" and includes them as is.

Paths' that direct path are already handled in the same way

My recommendation is to set an environment variable with all the directories you 
are interested in and just add "$MYENV" into the copybook search config.

For example:

```shell
 set PROJECTCOMMONFOLDER=$HOME/src/cpy/common:$HOME/src/cpy/files:$HOME/src/cpy/screens
```

```json
		"coboleditor.copybookdirs": [
			"CopyBooks",
			"Shared",
			"copybooks",
			"src/cpy/common",
			"src/cpy/files",
			"src/cpy/screens"
			"$PROJECTCOMMONFOLDER"
			],
```

**Comment by GitMensch** [comment]
> It is already expanding "$" env's, remember I said it expands "$PATH" and includes them as is.

Yes, I see - but then you're fast in "what is done on Win32" land, therefore I suggest to deprecate this in favor of the vscode standard `${env:PATH}` and add resolving of `${workspaceFolder}` on the way.

Question: Are absolute paths handled correctly (without further check in the workspace folders)?
Can you add translation for `${env:name}` and add resolving of `${workspaceFolder}` please?

**Comment by spgennard** [comment]
> Yes, I see - but then you're fast in "what is done on Win32" land, therefore I suggest to deprecate this in favor of the vscode standard ${env:PATH} and add resolving of ${workspaceFolder} on the way.

Win32 land would be "%PATH%" rather than $PATH

${env:PATH} is the inclusion of the PATH environment variable within
the string, eg: ${env:HOME}/src/copy, whereas $PATH is the expansion
of PATH and separated out into multiple paths to expand the search,
the two are different in ideas and usew.

> Question: Are absolute paths handled correctly (without further check in the workspace folders)?
Yes, I've already stated this.

> Can you add translation for ${env:name} and add resolving of ${workspaceFolder} please?
Can you explain why this is needed, as every item in the copybook dir
is used a part of ${workspaceFolder} search, therefore it is not
required.

On Fri, 8 May 2020 at 23:48, Simon Sobisch <notifications@github.com> wrote:
>
> It is already expanding "$" env's, remember I said it expands "$PATH" and includes them as is.
>
> Yes, I see - but then you're fast in "what is done on Win32" land, therefore I suggest to deprecate this in favor of the vscode standard ${env:PATH} and add resolving of ${workspaceFolder} on the way.
>
> Question: Are absolute paths handled correctly (without further check in the workspace folders)?
> Can you add translation for ${env:name} and add resolving of ${workspaceFolder} please?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
--
Stephen Gennard
stephen@gennard.net

**Comment by GitMensch** [comment]
> Can you explain why this is needed, as every item in the copybook dir is used a part of `${workspaceFolder}` search, therefore it is not required.

Sure. The reason is that with `${workspaceFolder}` we do *not* get the lookup in multiple folders but an absolute path. The lookup is faster and no copybooks that possibly lay around in some folder are taken up just because they are there.

Relative path support is good, but it must be relative to the file, not something else.
Example (all using the `cpy` entry):

* area1
  * prog1.cob
  * prog2.cob
  * cpy
      * copy1.cpy
      * copy2.cpy
* area2
  * prog3.cob
  * prog4.cob
  * cpy
      * copy1.cpy
      * copy2.cpy
* cpy
  * copy1.cpy

prog3+4 should (with relative paths) "see" exactly "their" copy1, not the one from prog1+2 and vice versa - none of these should "see" the copy1 in the root.

**Comment by GitMensch** [comment]
With your hints (and me learning more about the environment step for step) I did understand that we cannot define any arbitrary constant (like I've tried with `projectCommonFolder`) to use it in another setting.

Using `workspaceFolder` works like a charm with 6.2.26, if you agree I would create a PR against README to add some details to the settings part highlighting where to use a relative path and where `workspaceFolder` is reasonable to be used for the copybook settings.

One last note (other than "please not break `workspaceFolder`" ;-) is that the copybook search directories seems to be never cleared but only added (change settings.json and you see on the output that the new search directories get in - but the old are never cleared until restart). Should I create a separate issue for this?
