### ISSUE TITLE
missing reference for FILE STATUS and ASSIGN name

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#131]
Sample:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID.      'test'.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT TST-FILE ASSIGN TO file-name
                  ACCESS MODE     IS SEQUENTIAL
                  FILE STATUS     IS file-status
                  ORGANIZATION    IS LINE SEQUENTIAL.
       DATA DIVISION.
       FILE SECTION.
       FD  TST-FILE.
       01  TST-REC.
           03 TST-CHR  PIC X(01) OCCURS 80.
       WORKING-STORAGE SECTION.
      *
       77 file-name    pic x(256).
       77 file-status  pic xx.
      * 
       PROCEDURE DIVISION.
           MOVE 'TEST' TO file-name
           open output TST-FILE
           if file-status (1:1) = '0'
              close TST-FILE.
           goback.
```

The reference of `TST-FILE` is perfect already, the reference of `file-name` and `file-status` misses the reference in the `SELECT` clause.
Note: if you'd need to parse the `SELECT` clause (which would be needed if the extension is planned to understand it and know the relation between these two variables): the clauses can occur in any order and there are many "noise"/"optional" words in there. If the extension is not planned to understand the `SELECT` clause it would be enough to read everything between the `SELECT` and the next separator period `.` and store everything as reference that isn't a reserved word.

Thanks for this plugin which gets better every week :-)

**Comment by GitMensch** [comment]
Thank you for the fix which works with this sample. As hinted before both `TO` and `IS` are optional/noise words therefore the fix seems only partial.

Would ot be enough to read everything between the `SELECT` and the next "dot" and store everything as reference that isn't a reserved word?

**Comment by spgennard** [comment]
I take a look later but for now, it will have to do.

**Comment by GitMensch** [comment]
> I take a look later but for now, it will have to do.

Sounds reasonable. You may consider opening this ticket.
