### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by josejmm** [spgennard/vscode_cobol#132]
**Describe the bug**
I haven't any color in Cobol reserved words.

**To Reproduce**
I just open the workspace and I have'n any colors in the Cobol code.

**Expected behavior**
I expect colors in Cobol reserved words like IDENTIFICATION, PROGRAM-ID, ...

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6

**Screenshots**
<img width="743" alt="Screen Shot 2020-05-09 at 21 42 43" src="https://user-images.githubusercontent.com/64977506/81484554-1d92a980-923e-11ea-8425-a13c551ebfcb.png">

Many thanks,
Jose

**Comment by spgennard** [comment]
Your screenshot does not show if the COBOL language is selected or not for the tut.cob source file.

**Comment by GitMensch** [comment]
@josejmm The lower right should look something like the following: 
![grafik](https://user-images.githubusercontent.com/6699539/81569380-7b8ad280-939f-11ea-9af9-3b68d33f74dc.png)

**Comment by josejmm** [comment]
The COBOL word didn't appear. Now is working.
Many thanks
