### ISSUE TITLE
FR: option to open CALLed programs

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#138]
While this isn't possible for `CALL variable` it is possible for the common `CALL 'SOMEPROG'`.
To be able to use it the extension would need another setting "programdirs" and "programextensions".

**Comment by spgennard** [comment]
entry-points were already added to the global symbol cache but due to a bug, the found program-id's were not being added correctly.

If you remove your cache directory and rebuild it, then CALL to source that have program-id/entry-points will be found.

**Comment by GitMensch** [comment]
Rechecked, now works if I open the program to be called first at least once; this is still the case after using "process files in workspace for metadata" - can you please include it there? I suggest to track this in this issue, too.

Can we define an array which paths and/or extensions to not use for the metadata/symbol cache? For example everything under "build" is an output format (preprocessed by multiple tools), not the actual source. I guess a new issue may be useful for this.

After a bit of wondering. why it still did not worked for many programs in the codebase I've looked at is that most of the programs have their program-id in a copybook, and even if #140 would be implemented then the missing preparsing handling of `REPLACING 'PROGID' BY 'MYPROG'` would lead to the symbols not resolved correctly.
Should a new issue for handling the `REPLACING` be created (or is this outside of the extension)?

**Comment by spgennard** [comment]
```COPY REPLACING``` is a huge step, I would have to move from using a scanner to implementing a full parser and that is completely out of scope.

However, one mitigation... could be..

COBOL runtime's has a "default" ```PROGRAM-ID```, this is based on the source filename.   In most cases the ```PROGRAM-ID```is the same, so it is never observed.   This could help in this situation.

**Comment by GitMensch** [comment]
> COBOL runtime's has a "default" `PROGRAM-ID`, this is based on the source filename. In most cases the `PROGRAM-ID`is the same, so it is never observed. This could help in this situation.

Yes, that would work in >90% of the cases. Very good idea.
Can you add this, possibly together with letting the entry points be found when files are processed for metadata?

**Comment by spgennard** [comment]
the 90% solution was compled

**Comment by GitMensch** [comment]
Thanks for the update - so PROGRAM-ID assumed to be identical to the file? Any entry points included yet (if not it seems reasonable to create a new issue for those)?

**Comment by spgennard** [comment]
Entry points ar included providing they are literals

**Comment by GitMensch** [comment]
The following is, according to metadata dump (7.0.0) added to the entry list:

````cobol
           MOVE "ENTRY" TO W123-VAR.
           MOVE W456-INP (W789-NR) TO VAR1
                                          W001-VAR.
```

as two global symbols.

The parser seems to not recognize the literal correctly (adding  `to` to the global symbols) and interpreted a symbol prefixed by spaces and followed by a period `W001-VAR. ` as paragraph (adding `W001-VAR` to the labels) which it would be if the previous not-comment-token would be a period [an `ENTRY` does not need a period before],

**Comment by spgennard** [comment]
To be expected, it is not a parser it is a tokenizer, so it will get things wrong.

**Comment by GitMensch** [comment]
Thank you for the note. Would you accept PRs to (possibly) fix these two specific cases?
