### ISSUE TITLE
pre_parse_line_limit does not consider copybooks

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#140]
In a current project the common headers are *always* placed in a copybook.
Because of the current recognition of a program/copybook only in the first pre_parse_line_limit lines some features like `go to definition` sometimes work only partial or not at all.

Can we have a setting like `pre_parse_in_copybook`? In this project's case the copybooks contain the `IDENTIFICATION DIVISION` down to the first entries of the `WORKING-STORAGE SECTION`, sometimes also with `SELECT` and `FD` entries.

**Comment by sevencookies** [comment]
I too have this issue with the go to definition not working. I had to have caching on and changed the 'pre_parse_line_limit' to a larger number to cover the code size in the copybooks. At the moment, I use PEEK REFERENCE to find the definition in the copybooks, maybe not how it is suppose to work but a work-around with 'FD' and sometimes 'WS' entries.

    "coboleditor.cache_metadata": "partial",
    "coboleditor.pre_parse_line_limit": 250,

**Comment by spgennard** [comment]
The pre parse line limit is present to limit the parsing of the "head" of the file to determine what type of file it is.

If it is a normal COBOL program, a full scan is done, otherwise, it tries to "guess" depending on the contents where the contents are being used in... ie: in a copybook in procedure division, or a copybook in a working-storage.

So, if you include a sample of the "head" of the copybook then I can try and accommodate it.

**Comment by sevencookies** [comment]
Sorry for the delay, I found that VSCode possibly with this extension was quite slow so I stopped using it. That been said, I have started to reuse it and noted that with the default settings, using peek references will not show copybook references. An example of a copybook for some genealogy data contains alot of comments since it refers to compliance to a standard; see example below.

```
000001******************************************************************
000002* The individual tags prefixed with '$' have been implemented;   *
000003* $# 0 @XREF:INDI@ INDI                                          *
000004*       1 RESN <RESTRICTION_NOTICE>                              *
000005* $     1 <<PERSONAL_NAME_STRUCTURE>>                            *
000006* $     1 SEX <SEX_VALUE>                                        *
000007* $     1 <<INDIVIDUAL_EVENT_STRUCTURE>>                         *
000008* $     1 <<INDIVIDUAL_ATTRIBUTE_STRUCTURE>>                     *
000009*       1 <<LDS_INDIVIDUAL_ORDINANCE>>                           *
000010* $     1 <<CHILD_TO_FAMILY_LINK>>                               *
000011* $     1 <<SPOUSE_TO_FAMILY_LINK>>                              *
000012*       1 SUBM @<XREF:SUBM>@                                     *
000013*       1 <<ASSOCIATION_STRUCTURE>>                              *
000014* $     1 ALIA @<XREF:INDI>@                                     *
000015*       1 ANCI @<XREF:SUBM>                                      *
000016*       1 DESI @<XREF:SUBM>                                      *
000017* $     1 <<SOURCE_CITATION>>                                    *
000018* $     1 <<MULTIMEDIA_LINK>>                                    *
000019* $     1 <<NOTE_STRUCTURE>>                                     *
000020*       1 RFN <PERMANENT_RECORD_FILE_NUMBER>                     *
000021*       1 AFN <ANCESTRAL_FILE_NUMBER>                            *
000022*       1 REFN <USER_REFERENCE_NUMBER>                           *
000023*          2 TYPE <USER_REFERENCE_TYPE>                          *
000024*       1 RIN <AUTOMATED_RECORD_ID>                              *
000025* $     1 <<CHANGE_DATE>>                                        *
000026*                                                                *
000027* The personal name structure, prefixed with '$' is implemented; *
000028* $# n NAME <NAME_PERSONAL>                                      *
000029*       +1 NPFX <NAME_PIECE_PREFIX>                              *
000030* $     +1 GIVN <NAME_PIECE_GIVEN>                               *
000031*       +1 NICK <NAME_PIECE_NICKNAME>                            *
000032*       +1 SPFX <NAME_PIECE_SURNAME_PREFIX                       *
000033* $     +1 SURN <NAME_PIECE_SURNAME>                             *
000034*       +1 NSFX <NAME_PIECE_SUFFIX>                              *
000035* $     +1 <<SOURCE_CITATION>>                                   *
000036*       +1 <<NOTE_STRUCTURE>>                                    *
000037*                                                                *
000038* The child family link structure prefix with '$' is implemented;*
000039* $# n FAMC @<XREF:FAM>@                                         *
000040*       +1 PEDI <PEDIGREE_LINKAGE_TYPE>                          *
000041*       +1 <<NOTE_STRUCTURE>>                                    *
000042* The spouse family link structure prefix with '$' is implement; *
000043* $# n FAMS @<XREF:FAM>@                                         *
000044*       +1 <<NOTE_STRUCTURE>>                                    *
000045*                                                                *
000046* The note link structure prefixed with '$' is implemented;      *
000047* $# n NOTE @<XREF:NOTE>@                                        *
000048* $      +1 <<SOURCE_CITATION>>                                  *
000049* The note inline structure prefixed with '$' is implemented;    *
000050* $# n NOTE <SUBMITTER_TEXT>                                     *
000051* $     +1 [ CONC | CONT ] <SUBMITTER_TEXT>                      *
000052* $     +1 <<SOURCE_CITATION>>                                   *
000053*                                                                *
000054* The change date structure prefixed with '$' is implemented;    *
000055* $# n CHAN                                                      *
000056* $#(5) +1 DATE <CHANGE_DATE>                                    *
000057* $        +2 TIME <TIME_VALUE>                                  *
000058*       +1 <<NOTE_STRUCTURE>>                                    *
000059*(5) Reunion stores the change date against the 'CHAN' tag.      *
000060*                                    Tags with '#' are mandatory.*
000061******************************************************************
000062******************************************************************
000063* The individual file is a fixed length file containing an       *
000064* individual id, name, gender, date and place for birth and      *
000065* death events.                                                  *
000066******************************************************************
000067 FD FD-Individual-File
000068    DATA RECORD IS FD-Individual-Record.
000069******************************************************************
000070* The structure of the individual record is as follows;          *
000071* FD-Individual-EOF      Conditional for setting end of file     *
000072* FD-Individual-Id       Primary key of unique prefix and id,    *
000073* FD-Individual-Name     Secondary grouping of surname and given,*
000074* - FD-Ind-Brief-Surname The brief surname of the individual,    *
000075* - FD-Ind-Brief-Given   The brief given name of the individual, *
000076* FD-Individual-Data     Grouping of individual data,            *
000077* - FD-Ind-Name          The full name of the individual,        *
000078* - FD-Ind-Given         The given name of the individual,       *
000079* - FD-Ind-Surname       The surname of the individual,          *
000080* - FD-Ind-Alias         The alias of the individual,            *
000081* - FD-Ind-Sex           The gender of the individual,           *
000082* -- FD-Male             Conditional for male of 'M' or 'm',     *
000083* -- FD-Female           Conditional for female of 'F' or 'f',   *
000084* -- FD-Unknown          Conditional for unknown of 'U' or 'u',  *
000085* - FD-Birth-Date        Date of birth or Unknown,               *
000086* - FD-Death-Date        Death date, Unknown, blank for living,  *
000087* - FD-Ind-Change-Date   The date of last change,                *
000088* - FD-Ind-Change-Time   The time of last change,                *
000089* FD-Parents-Count       The count of parents of the child which *
000090*                        is generally one unless adopted. To a   *
000091*                        maximum of 9, biological parents and 8  *
000092*                        adoptions.                              *
000093* FD-Child-Family-Data   Grouping of family ids when individual  *
000094*                        was a child, outlining parents and      *
000095*                        siblings,                               *
000096* - FD-Child-Family      A table of child family ids,            *
000097* FD-Spouse-Count        The count of spouses of which is zero   *
000098*                        to a maximum of 9,                      *
000099* FD-Spouse-Family-Data  Grouping of family ids when individual  *
000100*                        was an adult with spouse(s),            *
000101* - FD-Spouse-Family     A table of adult or spouse family ids.  *
000102* FD-Ind-Cite-Count      The count of citations for individual,  *
000103* FD-Ind-Event-Count     The count of events for this individual,*
000104* FD-Ind-Media-Count     The count of media for this individual, *
000105* FD-Ind-RefNoteCount    The count of referencing notes to a     *
000106*                        maximum of 99,                          *
000107* FD-Ind-Ref-Note-Id     A table of reference note ids for notes,*
000108* FD-Ind-InlineNoteCount The number of notes attached to this    *
000109*                        individual, ranging from zero to 999.   *
000110*                        The individual id and unique number     *
000111*                        ranging from 1 to note count is used to *
000112*                        uniquely identify each note component   *
000113*                        with note lines 2 upwards coming from   *
000114*                        'CONT' and 'CONC' tags.                 *
000115* NOTE: Ancestry has inline notes & Reunion has reference notes, *
000116*       and citations against gender (or sex).                   *
000117******************************************************************
000118 01 FD-Individual-Record.
000119    88 FD-Individual-EOF         VALUE HIGH-VALUES.
000120    02 FD-Individual-Id          PIC X(10).
000121    02 FD-Individual-Name.
000122       03 FD-Ind-Brief-Surname   PIC X(30).
000123       03 FD-Ind-Brief-Given     PIC X(30).
000124    02 FD-Individual-Data.
000125       03 FD-Ind-Name            PIC X(120). *>WS-Name-Width-Const
000126       03 FD-Ind-Given           PIC X(120). *>WS-Name-Width-Const
000127       03 FD-Ind-Surname         PIC X(120). *>WS-Name-Width-Const
000128       03 FD-Ind-Alias           PIC X(30).
000129       03 FD-Ind-Sex             PIC X.
000130          88 FD-Male             VALUE "M", "m".
000131          88 FD-Female           VALUE "F", "f".
000132          88 FD-Unknown          VALUE "U", "u".
000133       03 FD-Birth-Date          PIC X(35).
000134       03 FD-Death-Date          PIC X(35).
000135       03 FD-Ind-Change-Date     PIC X(11).
000136       03 FD-Ind-Change-Time     PIC X(12).
000137    02 FD-Parents-Count          PIC 9     USAGE IS COMPUTATIONAL.
000138    02 FD-Child-Family-Data.
000139       03 FD-Child-Family        PIC X(10) OCCURS 9 TIMES
000140                                 INDEXED BY FD-Child-Family-Index.
000141    02 FD-Spouse-Count           PIC 9     USAGE IS COMPUTATIONAL.
000142    02 FD-Spouse-Family-Data.
000143       03 FD-Spouse-Family       PIC X(10) OCCURS 9 TIMES
000144                                 INDEXED FD-Spouse-Family-Index.
000145    02 FD-Ind-Cite-Count         PIC 999   USAGE IS COMPUTATIONAL.
000146    02 FD-Ind-Event-Count        PIC 999   USAGE IS COMPUTATIONAL.
000147    02 FD-Ind-Media-Count        PIC 999   USAGE IS COMPUTATIONAL.
000148    02 FD-Ind-RefNoteCount       PIC 99    USAGE IS COMPUTATIONAL.
000149    02 FD-Ind-Ref-Note-Id        PIC X(10) OCCURS 99 TIMES
000150                                 INDEXED FD-Individual-Note-Index.
000151    02 FD-Ind-InlineNoteCount    PIC 999   USAGE IS COMPUTATIONAL.
```

In a program that uses this copybook, all definitions and references are not found via peek or go to. The copybook are copied via `COPY "FD-Individual" IN "./CopyBooks"`

**Comment by spgennard** [comment]
@sevencookies - The "pre_parse_line_limit" is functionality that parses the first couple of lines of the source code to determine if this the file is COBOL or a looks like a copybook.   If it is a copybook it tries to "guess" what section/division the code might belong too.

The source parser does not visit copybook's, so this definition will be as you found invisible to the editor.

If you want an IDE experience consider using something like [Micro Focus Visual COBOL`](https://www.microfocus.com/en-us/products/visual-cobol/overview), which does have copybook expansion and inline editing of copybooks.

**Comment by sevencookies** [comment]
I tried the `COPY "FD-Individual".` instead of using the IN clause, using the include -I switch for compiling etc. but the same result, i.e. unable to detect any references in the copybooks.

**Comment by sevencookies** [comment]
Thanks for the reply, Micro Focus is not available on the macOS platform unfortunately. But knowing that the issue I have is not part of the extension functionality is fine, it explains why the copybook definitions are "invisible" as you mentioned above. I will leave the parser settings at the default and continue to enjoy your extension with VSCode. The Goto and Peek Definitions and References for non-copybook code is still extremely valuable and useful.

**Comment by spgennard** [comment]
@sevencookies - It is on my todo list but I need to come up with a way of doing it without slowing things down further, javascript is not the fastest thing for parsing source code... especially COBOL which often has large files and deep copybooks.

You can use virtualization on MacOSX and use Micro Focus products, which works well with the "host" to "vm" file sharing (aka using the VM for display & compute).

You have the choice of either using the Windows products (Eclipse or Visual Studio) or one of the Linux products using Eclipse.

**Comment by sevencookies** [comment]
That is fantastic - I look forward to any developments but I, like others, appreciate your efforts and time involved in this development.

**Comment by GitMensch** [comment]
Hm, is this also true when all non-default parser settings are enabled and the metadata processing is done once manually? At least that is the setup I've used months ago and peek has always gone into the copybook.

Does that work (and is possibly a one-time issue that one can do each several days (after the copybooks had more changes)?

(confused)

Note: It may be possible to use ctags or something similar under the hood to do the parsing, wouldn't it?

**Comment by sevencookies** [comment]
Re: "also true when all non-default parser settings are enabled and the metadata processing is done once manually", I found changing the "pre_parse_line_limit" enabled peek for references into copybooks, but my experience with on my older computer, I have refrained from changing alot of the metadata and parsing settings since last time it caused the editor to slow to a crawl, e.g. after newline, tab would be slow or relunctant to operate so i would have to use space, the intellisync would show "loading" and fail to show anything. My fresh install of VSCode and this extension is working well on the defaults abit copybook being limited.
I thought ctags (Exuberant Ctags) maybe useful but I noted that it is only retrieving paragraph names and not section names nor any variables. There maybe another ctags that works better than Exuberant -- not sure.

**Comment by spgennard** [comment]
Before I started the adventure of parsing/tokenizing in the extension I used to use ctags and as you say it has numerous issues including:
 - it does understand source format
 - missing support for paragraphs
 - not understanding classes/method/interface/enums 

Plus.. various ctags extensions did not work well either eg; could not handle "-"'s

Which is why I started to do the work myself.

fyi - Universal Ctags is better but it still broken with very similar issues.

I even started to fix it but it got to a point that it was not the way to go..
  https://github.com/universal-ctags/ctags/compare/master...spgennard:cobol_sourceformat_enhancements

**Comment by GitMensch** [comment]
As you brought this up... @spgennard Can you please add the test case to https://github.com/universal-ctags/ctags/pull/1768 and https://github.com/universal-ctags/ctags/pull/1778? Even when you find uct not to be useful for this plugin it would be nice to have your changes available.

Concerning this topic: I suggest to do the parsing of _any_ file not currently open only upon explicit request and store the result n the workspace. I see no issue in some additional KBytes and "time consuming parsing" if the later is only done upon request (so I can do it when I want, for example before the launch break or over night).

**Comment by sevencookies** [comment]
Am I correct in assuming there is a new option called parse copybook for references? I will try the use metadata caching (always on), process metadata cache on startup and parse copybook for references.
The use of this is working for peeking references. I tried goto definition but it said no definitions were found but excellent work in adding this feature. I assume the metadata caching is required for this feature of parsing copybook for references?

**Comment by spgennard** [comment]
Yes, but it is still work in progress and I need to make other changes to follow through on the changes.

The metadata cache is not required, as this is "in-memory" parsing and is currently not cached (but will be/depending on your setting).

**Comment by sevencookies** [comment]
Thank you. May I ask a couple of questions if it is not too much trouble;
1. Are the ctags in .tags directory used by your extension?
2. The caching of metadata; what is it used for? Does it assist the Intellisyncing, goto and peeking features?

**Comment by spgennard** [comment]
1. No, ctags are not used by the extension.
2. I am in the process of unifying how this works, at the moment the cache is used for anything that is found outside of the source you are working on.

**Comment by sevencookies** [comment]
Thank you for this; I will removed ctags. My cobol extension settings at present are - caching metadata is on and set to refresh on restart, looking for references in copybooks with copybooks directory defined and unc directories disabled (don't know if I need that). I used the default for others (e.g. Intellisync uses unchanged etc).
```
    "coboleditor.cache_metadata": "on",
    "coboleditor.copybookdirs": [
        "CopyBooks"
    ],
    "coboleditor.disable_unc_copybooks_directories": true,
    "coboleditor.fileformat": [
        {
            "pattern": "**/FIXED*.cbl",
            "sourceformat": "fixed"
        }
    ],
    "coboleditor.parse_copybooks_for_references": true,
    "coboleditor.process_metadata_cache_on_start": true,
    "coboleditor.tabstops": [

        0,
        7,
        11,
        15,
        19,
        23,
        27,
        31,
        35,
        39,
        43,
        47,
        51,
        55,
        59,
        63,
        67,
        71,
        75,
        79
    ],
```
