### ISSUE TITLE
FR: support COPY of/in

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#142]
I'd consider this much less important than #137 and primarily want to add it for a possible reference later.

The current copybook paring only gets the name out of the statement and fails to recognize the IN/OF phrase:
```cobol
COPY 'STUFF' IN 'HERE'.
```
In this case (`IN` can also be switched to `OF` here) the copybook "STUFF" is searched in a sub-folder "HERE" (applied to all entries in the copybook search path).

**Comment by spgennard** [comment]
I am not sure I can do this in a generic way, as lots of COBOL vendors support it in various
different ways, some search inside .lbr files, another inside jar files/zip files, some assume
"HERE" is a directory, another assumes "HERE" is resource module (local & remote).

Implementing it as directory, would help some but hinder others that need it to be something
different.. hence I am unsure.   

I will need to think about it further.

**Comment by GitMensch** [comment]
Correct review, to have it actually working you'd need another set of options how to resolve HERE (and even with one piece of compiler on one sytem - it may be support both, too).

As I said: I don't see this as very important for now.

**Comment by spgennard** [comment]
I will add to the backlog

**Comment by spgennard** [comment]
please checkout recent changes

**Comment by spgennard** [comment]
please feel to open a new case if you find any issues related to this
