### ISSUE TITLE
Comment not recognise

### ISSUE THREAD

**Issue by heshm** [spgennard/vscode_cobol#144]
**Describe the bug**
At fixed format cobol source,when the first element is '|',the color of the comment is not correct.

such as:
       * Some comment here   
|      *  Some comment here

**Comment by spgennard** [comment]
This is a non-standard comment character.

If you use the ACUCOBOL, then I suspect it will be okay.

[click on COBOL, change to ACUCOBOL]

**Comment by spgennard** [comment]
For example:

Using COBOL dialect:

![image](https://user-images.githubusercontent.com/5991192/82545905-39a41e00-9b4f-11ea-9ee7-de187cb976ed.png)

and ACUCOBOL dialect:

![image](https://user-images.githubusercontent.com/5991192/82545982-50e30b80-9b4f-11ea-8714-6c8552e98dc9.png)

**Comment by GitMensch** [comment]
The most important thing here: the `|` works as inline comment (not only in column 7), where ISO2002 added `*>` for this (quite well supported in most dialects; the `|` as inline comment is only supported in ACUCOBOL which is correct).

I've verified that this works - issue can be closed.
