### ISSUE TITLE
mfcobol-errformat2 has invalid regex 

### ISSUE THREAD

**Issue by vladhietala** [spgennard/vscode_cobol#146]
mfcobol-errformat2  has the regex
```"^\\*+\\s+COBCH\\d+([a-zA-Z])\\s+([^:]+):\\s+(\\S*)\\((\\d+),(\\d+),.*\\)$"```

and the correct should be 
```"^\\*+\\s+COBCH\\d+([a-zA-Z])\\s+([^:]+):\\s+(\\S*)\\((\\d+),(\\d+).*\\)$"```

Link to working regex
https://regex101.com/r/KDdavB/1/

**Comment by spgennard** [comment]
On further investigation, the error format your are using is an old ERRFORMAT"2", which only has
two fields, 

    **    COBCH0012S Operand WS-DATE is not declared  : 
      \\90.0.0.131\Sistemas\Promax\11.66.00.24\usuario\xxx.xx\fontes\PW00070S.cbl(90,50)

The new format has three fields:

    **    COBCH0368S Exception phrase inappropriate  : CEESAMPLE.cbl(90,18,15)

Therefore, I will be including "mfcobol-errformat2-old" to cover this old product.

**Comment by vladhietala** [comment]
Thanks, we are using Net Express V5 and I made some changes to adjust its extension to our work environment.

Other developers at the company are using Net Express, but I prefer to use modern editors. I used sublime with its extension until I discovered that I can compile COBOL with vscode. So, I just have to thank you for developing this extension.

**Comment by spgennard** [comment]
Glad you like it.

I will change the -end to -netx-sx in the problem matcher name, so it is
more reflective of the product it is usable with and update the docs.
