### ISSUE TITLE
Performance issues with metadata cache and go to definition for copybook using network drives

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#153]
**Describe the bug**
I have a network share where I keep a large collection of copybooks that are shared among my projects, workspaces. This share is added in my `coboleditor.copybookdirs` as a UNC path `\\FileServer\CopyBooks`. Having this path in the settings significantly slows down the caching process _and_ even worse the go to definition command.

From the attached javascript profile while the setting included the network share, it took ~30 seconds to resolve the go to definition command for a workspace that had already been fully cached and the cache contained the entry for the copybook I wanted to jump into. [CPU-20200624T160153.894Z.cpuprofile.txt](https://github.com/spgennard/vscode_cobol/files/4826746/CPU-20200624T160153.894Z.cpuprofile.txt)

Removing the network share from the settings fixed the problem, but now it can't go to my network copybooks.

**To Reproduce**
* Add a potentially slow file system path to the  `coboleditor.copybookdirs`
* Enable metadata cache
* Process files in workspace
* Ctrl+Click on a copybook COPY statement

**Expected behavior**
In a workspace that has a fully loaded cache, going to the definition of the copybook file should be very quick.

**Screenshots**
![image](https://user-images.githubusercontent.com/675956/85594854-eb7eb080-b60d-11ea-848e-98c6f16ed1bd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Code 1.42.1, Extension: 6.3.11

**What user & workspace settings are being used?:**
* `coboleditor.copybookdirs` contains Windows file share at end of list
* `coboleditor.cache_metadata` on

**Additional context**
Not sure there's anything you can do about how long `fs.exitsSync` takes on network file systems, but maybe there's a workaround to give up on a file if takes long then a set amount of time.

**Comment by kabel** [comment]
Yeah, I'm working on some workarounds to copy things locally. It's a tad more complex than a simple copy, but I appreciate the robocopy suggestion.

In order to have a timeout or limit, you'd have to update the opencopybook API to use more async functions and/or promises for the definition provider. That way you can use the async API from fs and combine it with a promise that automatically rejects after a timeout:

```typescript
function isFileAsync(sdir: string): Promise<boolean> {
	let timeout = new Promise<boolean>((_, reject) => setTimeout(() => reject("Timeout"), 500));
	let fileStat = require('util').promisify(fs.stat)(sdir).then(f => f.isFile());
	return Promise.race([timeout, fileStat]);
}
```

Let me see if I can put something together in a PR.

**Comment by spgennard** [comment]
Hold off the PR (don't want to waste time), as it might clash with some changes.

 - option to drop all unc copybook dirs
 - feature to drop slow directories during extension setup

**Comment by spgennard** [comment]
I should also say the changes to use file async are much more wide-spread in the code base, from the parsing, source definition, outline/symbol provider.

But more importantly, I would like to move away from using any 'fs' api, as this means the extension can only work the "file://" schema and ideally, it should work on all schemas, so a re-think is required to things differently... especially if the extension is to be used in browser-based hosting environments for the extension.

**Comment by spgennard** [comment]
Can you please report back with more information using the latest version

**Comment by kabel** [comment]
I can confirm that the new setting does in-fact block my UNC share folder entry and keeps the extension host happily running at acceptable performance. Having that setting off (or while I was in some odd configuration state), still causes the extension to spin the CPU and trigger VS Code's extension performance warning.

**Comment by spgennard** [comment]
The other thing, I did was to include a "quick" performance check while initializing the extension, so if an "isDirectory" takes more than 2seconds it drops it from the list of viable extensions (and says so).

I am considering removing the ability to reference any copybook directory that is not in the workspace, this way the use of the node fs api can be reduced to almost nothing, as I can then move back to using the vscode/workspace apis.

This would include static/directories & unc files.. aka anything outside the workspaces.

**Comment by kabel** [comment]
Taking out the ability to reference copybooks outside of the workspace would not be great because it would take away a feature that shared libraries provide. Leaving users to come up with their own packaging system to get things into each workspace.

I haven't dug into the flame graph is see what exactly is taking the most time. But if I had to guess, the UNC path is not slow for a _single_ `fs.stat` request, rather, when you have it in _loops_ that are executed over and over again with candidate paths (this copybook path with this or that extension). You're flooding the network with a bunch of `stat` requests that collectively take too much time for the share to handle in a timely manner. 

I'm fine with manually trying to copy my copybook "packages" out of the UNC share, but it would not be great to have to do this for every workspace that I have. I'm sure I could work around it with symlinks, but it just adds more complexity.

**Comment by spgennard** [comment]
I should clarify, I would also attempt to add the "direct" path into the workspace automatically, thus allowing a degree of automatic migration.

**Comment by spgennard** [comment]
Just for reference, if you add the UNC directories to your workspace and remove them for them copybooks dir settings, is it better?

**Comment by kabel** [comment]
> Just for reference, if you add the UNC directories to your workspace and remove them for them copybooks dir settings, is it better?

I don't know why I didn't think of that before. I think I was worried that it was cause the extension to start writing caches files to that directory (most users don't have write access) or try to process all the files in there, which is _a lot_.

Long story short: Added the path as a workspace folder and everything is still working quickly!

**Comment by spgennard** [comment]
Option to migrate to "out of workspace" folders into the folder has been include and a warning message if an unc name is used.

Anyway, the later might be used now.

PS.  Glad you have a working solution.
