### ISSUE TITLE
Extensão causa alta carga de cpu

### ISSUE THREAD

**Issue by faustoramos78** [spgennard/vscode_cobol#156]
- Issue Type: `Performance`
- Extension Name: `cobol`
- Extension Version: `6.3.16`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\faust\bitlang.cobol-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by spgennard** [comment]
Stable issue, no information given
