### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by Tommi04** [spgennard/vscode_cobol#157]
Issue Type: <b>Bug</b>

ALT+F12 doesn't work anymore. ALT+click doesn't work anymore. suggestions words doesn't work well because i haven't suggestion of word that are in PROCEDURE DIVISION but not in WORKING-STORAGE SECTION.
Some days ago when i pressed end key the cursor gone at the end of the line and if i pressed up or down key it remained at the end, now when i press up or down key it remains at the same column.
When i type "AT END" when i read a file, it gives me "environment division" suggestion also if i press space bar, i have to press twice, i don't remember it first.

This extension worked well some times ago

Extension version: 6.3.19
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by spgennard** [comment]
> ALT+F12 doesn't work anymore. ALT+click doesn't work anymore. suggestions words doesn't work well because i haven't suggestion of word that are in PROCEDURE DIVISION but not in WORKING-STORAGE SECTION.

More information is required

> Some days ago when i pressed end key the cursor gone at the end of the line and if i pressed up or down key it remained at the end, now when i press up or down key it remains at the same column.

The extension does not do anything with cursor movement, I suggest you look at your configuration/extensions installed. 


> When i type "AT END" when i read a file, it gives me "environment division" suggestion also if i press space bar, i have to press twice, i don't remember it first.

If you do not want this, turn off the "Snippets suggestions".

![image](https://user-images.githubusercontent.com/5991192/86345588-9e28c180-bc53-11ea-84b1-c26d986d3106.png)

**Comment by cobolcowboy** [comment]
Hmm, I'm running into something similar. Pressing ALT+F12 used to open the file at a particular paragraph when I would press it while my cursor was within the paragraph name in a PERFORM statement. Now it says it cannot find the definition. It seems to work fine with regular variables but will not jump to named paragraphs.
