### ISSUE TITLE
Unable to navigate to subsection paragraph

### ISSUE THREAD

**Issue by cobolcowboy** [spgennard/vscode_cobol#159]
**Describe the bug**
Please see the following COBOL code to reproduce:

```
 IDENTIFICATION DIVISION.
 PROGRAM-ID.    TEST.
 ENVIRONMENT DIVISION.
 CONFIGURATION SECTION.
  SOURCE-COMPUTER. UNIX-MF.
  OBJECT-COMPUTER. UNIX-MF.
 INPUT-OUTPUT SECTION.
 FILE-CONTROL.
 DATA DIVISION.
 FILE SECTION.
 WORKING-STORAGE SECTION.

 PROCEDURE DIVISION.
 010-MAIN-PROCESSING-SECTION SECTION 01.
 010-MAIN-PROCESSING.

     PERFORM 900-OPEN THRU 900-EXIT.

     EXIT PROGRAM.

 900-OPEN-CLOSE-INIT SECTION 60.
 900-OPEN.
         DISPLAY "AT 900-OPEN"

 900-EXIT.
     EXIT.
```

**To Reproduce**
1. Load example file
2. Peek/goto definition of 900-OPEN
3. Extension fails to find paragraph

**Expected behavior**
I would expect to be able to navigate to this paragraph like normal. 

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Version 6.3.19

**Comment by spgennard** [comment]
Looks okay to me.

![image](https://user-images.githubusercontent.com/5991192/86628205-7aea7300-bfc1-11ea-89bc-4074ba74e7f8.png)

**Comment by cobolcowboy** [comment]
I suppose it must be something related to my config. I'll look into it. Thanks.
