### ISSUE TITLE
Feature Request: Use `ExtensionContext.storagePath` for symbol cache

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#161]
I'm not a big fan of having internal, developer environment specific files being stored in my repo/workspace. While it's easy enough to put `.vscode_cobol` into the ignore files, it would be nicer to use the space vscode already reserves for extensions to write private state via [ExtensionContext.storagePath](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.storagePath).

I know we previously tried and didn't like Memento, but maybe [ExtensionContext.workspaceState](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.workspaceState) can provide some support for routing the the right storage location.

Maybe it's easier to have it in the repo to quickly delete things, so maybe hide this in a config option.

**Comment by spgennard** [comment]
This would be a major change of scope.  It would mean everything would be visible to everything.

While also causing clashes in cache, as each program is scoped to the workspace.

In effect you could only have one version of a program per extension install.

Sorry it just doesn't work... Plus people the directory into SVN/git.

My long term plans are to move the encoded/compressed JSON files into one sqlite dB.

With one table per program.. but this just an idea.

**Comment by kabel** [comment]
I'm not so sure about the change in scope. The `storagePath` is unique to the workspace folder, so it's essentially the same thing as the location you put `.vscode_cobol` today. This is exactly how the c++ extension works: https://github.com/microsoft/vscode-cpptools/blob/e17ff5e93ef4061472328d4afff86d152e5fcb03/Extension/src/LanguageServer/client.ts#L731-L746

**Comment by spgennard** [comment]
It still does help people place it svn/git along side the source.

**Comment by kabel** [comment]
I understand some of the value of storing it in the repo, if the file format is stable from version to version. However, I still stand by there being a config option for this preference as it introduces a possible environment specific place for bugs in the cache. I have to explain to team members to try clearing/recommitting the cache when things don't appear to be working.

**Comment by spgennard** [comment]
How would you delete it if it was hidden in this store?

**Comment by kabel** [comment]
Either
- Share the platform and user specific location for the user to manually delete (Ex: `~/.config/Code/User/workspaceStorage/003a9bf85795627b1e3e1b582a807e5c/bitlang.vscode_cobol/`
- Expose the delete/clear cache command you used to have in the extension

This is akin to the debate about things like committing the `node_modules` folder. Besides, don't the cache files have things like platform specific paths in them? Doesn't that make them less portable between developers and platforms?

**Comment by spgennard** [comment]
If you set "coboleditor.cache_directory_strategy" to "storagepath" then it will use the storage path area.

The default is "workspace" but you can set in the user settngs etc..

**Comment by GitMensch** [comment]
Thanks for the option to adjust the storage path with 639ceb985fec7f864c981a850a79871fb18805c8 and to delete the cache via extension command in a0e3e6174b71018c04b91c9c3ac44a4e5cf36e23 - along with all the changes you've done to the caching!
