### ISSUE TITLE
Is it possible to use "complex editor settings" for coboleditor.tabstops?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#162]
Would the new feature https://code.visualstudio.com/updates/v1_47#_edit-object-settings-from-the-settings-editor be something useful for the `coboleditor.tabstops` setting?
Are there other settings that may benefit from this change in vscode?

**Comment by spgennard** [comment]
It does not work with arrays or nested objects.

**Comment by spgennard** [comment]
To quote:

       Now, you can edit non-nested object settings from the Settings editor.

The object, is an array and nested.

```json
          "type": "array",
                    "items": {
                        "type": "number",
                        "title": "tabstops",
                        "properties": {
                            "tabstop": {
                                "type": "number",
                                "description": "tabstop"
                            }
                        }
                    },
```

**Comment by GitMensch** [comment]
Hm, is this more nested as in the example?
Looks like the setting is `coboleditor.tabstobs` and the issue (if anything other than requesting a newer vscode version) is possibly that it is an array? But then, the setting for the filename extension look to be the same. I'm a bit confused here...

**Comment by spgennard** [comment]
This is the same too..


```json

 "coboleditor.copybookexts": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "title": "copybookextension",
                        "properties": {
                            "tabstop": {
                                "type": "string",
                                "description": "copybookextension"
                            }
                        }
                    },

**Comment by GitMensch** [comment]
... but the copybookextension works in the UI?

**Comment by spgennard** [comment]
it appears to not handle "numbers" or "integers" in arrays.

**Comment by spgennard** [comment]
I can confirm the above is true, so I guess we wait for the next improvement from Microsoft.

**Comment by spgennard** [comment]
I can confirm the above is true, so I guess we wait for the next improvement from Microsoft.
