### ISSUE TITLE
Please update the ChangeLog

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#165]
... ideally regularly. It is hard to guess what changes were implemented when, the only thing I do (on nearly each update) is to check the commit log.
Maybe CI could include the commit messages since last release into ChangeLog before the automated release? This should work for many of the good commit messages (and where it doesn't still leaves a trace for the user and provide you with a starting point for polishing this from time to time.

**Comment by spgennard** [comment]
log to CHANGELOG.md include in publish

**Comment by GitMensch** [comment]
Thank you, that's looks useful.

What do you think about using `--ignore-commits-without-issue` (which likely means to create some issues for changes before commits, but also creates a nice way to group commits in any case)?
