### ISSUE TITLE
Is there any reason to keep old branches?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#166]
There's currently the old develop, two merged branches and one about `bib` files (not sure what this branch is about, it actually changes the package identifier and seems to be about limiting the extension to MicroFocus only, so maybe nothing to keep here).

**Comment by spgennard** [comment]
Yes, history.   

Sorry, I don't believe in removing branches unless there is a technical, commercial, cost-driven or legal reason needing to do it.

**Comment by GitMensch** [comment]
Thank you for the answer, I'm fine with that just wondered (as my technical reason is that those may be auto-transferred on checkout). But I agree "removing branches, keeping tags" is primarily a style question.
