### ISSUE TITLE
How to disable warning "paragraph not referenced"?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#170]
As paragraphs are often only there because of "shop style rules" or to "scope" different code parts I'd suggest to have this disabled by default, but the question here is: how do I disable only this single diagnostic?

**Comment by spgennard** [comment]
turn off the "coboleditor.linter"

**Comment by GitMensch** [comment]
That setting has more consequences, doesn't it?

**Comment by spgennard** [comment]
No, it has one "linter" and this is it..

**Comment by GitMensch** [comment]
Thanks for the info (note: I generally do like it and would like to see it extended in the future).

**Comment by spgennard** [comment]
> 
> 
> Thanks for the info (note: I generally do like it and would like to see it extended in the future).

Me, too..

I was also thinking about a linter to highlight fields that do not obey "house" standards (defined via settings)

**Comment by GitMensch** [comment]
Good idea. As I'm currently learning a different set of "house standards": It would be good if those settings would also have:

* a filename/path schema it applies to (likely with a default to `*/*`) which allows an override like "only allowed in xyz (where it is downgraded to "informational", otherwise would be "warning", or even "error")
* reserved words to not use (= you get a linter warning but the source still compiles)
