### ISSUE TITLE
FR: add minimal handling of conditional compiler directives

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#174]
idea:
* add variables that may be evaluated in the settings (so for this example `COMPILER` may be defined to 1,2,...
* resolve them in places like `$IF COMPILER = 1 ... $ELSE ... $END`, if it cannot be resolved (at least one of the variables is not setup) handle all branches

**Comment by spgennard** [comment]
The constant ```COMPILER``` generally comes from the compiler settings, so I am unsure how useful this will be.

**Comment by GitMensch** [comment]
That was just a sample, I may should have written `MYSPECIALDEFINE`. The idea is "whatever is active may be specified by the programmer in the extension settings. If the extension parses a conditional compiler directive and _can_ resolve it either by those or for example simple arithmetic ones `>> IF 1 EQUALS 2` then it "processes it", only parsing the active branch, otherwise it leaves that alone and does as now.

I also don't think that this is something with a high priority, but I've seen a use for it in a copybook which contains many of those directives (the sources are compiled with multiple compilers and I mostly care about one) - and as is the extension cannot know which of those COBOL variable definitions is the correct one.
