### ISSUE TITLE
Not all workspace folders are included in the copybooks

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#177]
Giving the settings in #173 I've expected all source folders to be included as copybooks.
When the extension is activated I see all entries listed under "Workspace Folders" (including the one that is not there - the "two paths for home" solution), but under " CopyBook Search directories (7)" the "root" entry and both home directories are missing.

Any idea how to solve this?

**Comment by spgennard** [comment]
In the version of the extension, you are using the "CopyBook Search directories" are the extra copybook directories to search
on top of the workspace folders.

**Comment by spgennard** [comment]
Is this still an issue?

**Comment by spgennard** [comment]
Is this still an issue?

**Comment by GitMensch** [comment]
Seems to be fine now, but please see #211 for a related issue.
