### ISSUE TITLE
Copybook not longer working (quoted works)

### ISSUE THREAD

**Issue by chupi33** [spgennard/vscode_cobol#182]
Hello

vscode insiders : 1.48
vscodium : 1.47
vscobol : 6.6.3

I don't know how long it's been but copybooks seems to be KO

my settings.json

    "[COBOL]": {
        "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?",
        "files.autoGuessEncoding": false,
        "files.encoding": "windows1252",
    },
    "coboleditor.copybookdirs": [
        "srvcbl\\src\\main\\cpy\\windows",
        "srvcbl\\src\\main\\cpy\\contexte",
        "srvcbl\\src\\main\\cpy\\dclgen",
        "srvcbl\\src\\main\\cpy\\divers",
        "srvcbl\\src\\main\\cpy\\signature",
        "srvcbl\\src\\main\\cpy\\tabref"
    ],
    "coboleditor.copybookexts": [
        "cpy",
        "cob",
        "CPY",
        "COB",
        "cbl",
        "CBL"
    ],

this conf hasn't change in months
i try with
srvcbl/src/main/cpy/windows instead of srvcbl\\src\\main\\cpy\\windows

And now when i do CTRL + click on COPY FOO ... nothing's happening :(

i don't know how to create some debug or diag informations ...

thks 

PS : wildcards are possible ? like srvcbl\\src\\main\\* ?

**Comment by spgennard** [comment]
Have you checked the Output/COBOL window to see what directories have been found and what have not?

**Comment by spgennard** [comment]
I am unable to reproduce your issue.

![2020-08-07_12-24-35](https://user-images.githubusercontent.com/5991192/89641435-8a532980-d8a9-11ea-91ee-459703eb6b0a.gif)

**Comment by chupi33** [comment]
with your gif, i understand !!! 🤣  

in our code, COPY are declare without double quotes
if i add "" it works
before it works in any case

PS : i didn't know the output Cobol windows 👍

**Comment by spgennard** [comment]
Okay, I understand the issue.   A fix will be coming asap.
