### ISSUE TITLE
Metadata entries (like AUTHOR and SOURCE-COMPUTER) are not terminated by a newline

### ISSUE THREAD

**Issue by MCEmperor** [spgennard/vscode_cobol#187]
**Describe the bug**
Metadata entries like `AUTHOR` or `SOURCE-COMPUTER` are not terminated by a newline, causing all subsequent code to be highlighted as if it were a comment.

```
       IDENTIFICATION DIVISION.
        PROGRAM-ID. SomeProgram.

        AUTHOR. MCEmperor.
        INSTALLATION. Intel.
        DATE-WRITTEN. 2020-08-13.

      * Some comment. This will end the metadata highlighing,
      * So the next keyword is highlighted correctly.

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
        SOURCE-COMPUTER. MIGHTYFRAME.
        OBJECT-COMPUTER. RM-COMPATIBLE.

       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
```

**To Reproduce**
1. Copy the abovementioned code block.
2. View this code in VSCode with this extension enabled.

As can be seen, *everything* behind a metadata attribute (like `AUTHOR`) is commented out, not only the true value of the metadata attribute (which, in the case of `AUTHOR`) is just `MCEmperor`. The highlighting extends to the next comment, if found, otherwise until the end of file is found.

**Expected behavior**
The metadata value should end if a newline is found.
With other words, in the abovementioned example, the value of the metadata attribute `AUTHOR` should be `MCEmperor`, and not `MCEmperor↵        INSTALLATION. Intel.↵        DATE-WRITTEN…` (et cetera).

**Additional context**
I think this has something to do with a recent commit, as I did not observe the problem until recently. I suspect the fix to issue #186, commit https://github.com/spgennard/vscode_cobol/commit/811ccf1e77de2cd292d298a9aa7690433b94453b, has broken the highlighting. Using the _Install Another Version_ feature of VSCode, I found out that this problem exists since version **6.6.13**.

**Comment by MCEmperor** [comment]
Nice work, it works again!

**Comment by spgennard** [comment]
@MCEmperor - Glad it is sorted, sorry I was having a "bad" regex day when I broke it.

**Comment by GitMensch** [comment]
Please reopen, this issue is definitely fixed for "COBOL" but still true for "COBOL_LISTFILE".

**Comment by spgennard** [comment]
Not all listing formats are the same, you will need to give an example.

As the list_cobol grammar is a super set of the COBOL grammar.

It works with micro focus listing files.

**Comment by GitMensch** [comment]
That's a MF listing file:

![sample](https://user-images.githubusercontent.com/6699539/96142804-c71f4a80-0f02-11eb-9a5e-61bbf979ed88.png)

**Comment by spgennard** [comment]
The COBOL listing support was an experiment, I will schedule it for removal and focus on other things.
