### ISSUE TITLE
Add support of coboldoc

### ISSUE THREAD

**Issue by OlegKunitsyn** [spgennard/vscode_cobol#189]
[COBOLDoc](https://github.com/brunopacheco1/coboldoc) is an auto-documentation markup and command-line tool used to annotate COBOL source code, a successor of JSDoc, PHPDoc and Javadoc industrial standards.

Please let programmers quickly generate the comment-blocks in COBOLDoc format by using keyboard shortcuts (like `/**ENTER` in JetBrains IDEs). Of course, implementation of the comments must be considered in each dialect.

Example:
- sources: https://github.com/OlegKunitsyn/core-string/blob/master/src/string.cbl
- auto-documentation: https://github.com/OlegKunitsyn/core-string/blob/master/coboldoc/string.cbl.md

**Comment by spgennard** [comment]
Micro Focus uses the Microsoft standard xmldoc document syntax, so this will need to considered as well.

I think veryant also use a different format.

**Comment by spgennard** [comment]
From veryant/isCOBOL docs:

![image](https://user-images.githubusercontent.com/5991192/90569725-47952980-e1a6-11ea-93bf-27c085351380.png)

**Comment by spgennard** [comment]
Next, ROBOTDOC has support for COBOL and it looks like it was added by "Brian Tiffin" which I believe worked on GnuCOBOL.

https://github.com/gumpu/ROBODoc
https://rosettacode.org/wiki/Documentation#COBOL

So far we have four different mechanisms... two for GnuCOBOL, one for Micro Focus, one for isCOBOL

**Comment by GitMensch** [comment]
Actually we have 2 that may be used in any dialect (the free ones, used for example in GnuCOBOL, that are created outside of the compiler), one (MF) that _may_ only work there (@spgennard can you please post a sample like you did for isCOBOL?) and one that only works with a specific dialect with a specific output format.

**Comment by spgennard** [comment]
This is a complete example but it gives you an idea.

```cobol
       *>  for more examples see https://docs.microsoft.com/en-us/dotnet/csharp/codedoc
       *>> <summary>... what ever</summary/>
       *>>
       *>> <example>
       *>>   Insert example on how to use the class here
       *>>  <code>
       *>>    declare a as ilexample
       *>>    display a.MyProperty
       *>>  </code>
       *>> </example>
       class-id ilexample public.

       *>> <value>Get MyProperty</value>
       01 MyProperty       public string.
       *>> <summary>A constructor for this class</summary>
       *>> <remark>This is an example</remark>
       method-id new public.
       procedure division.

           exit method.
       end method.

       *>> <summary>method sample</summary>
       *>> <remarks>
       *>>   <para>Some information</para>
       *>>   <para>... and again </para>
       *>> </remarks>
       *>> <returns>something...</returns>
       *>> <exception cref="member">description</exception>
       *>> <param name="a-name">a name of something</param>
       *>> <see cref="other" />
       *>> <seealso cref="elsewherfe" />
       method-id sample.
       linkage section.
       01 a-name   pic x(10).
       procedure division using by reference a-name.

       end method.

       end class.
```

**Comment by spgennard** [comment]
Fyi.. ground work in progress

**Comment by OlegKunitsyn** [comment]
> From veryant/isCOBOL docs:
> 
> ![image](https://user-images.githubusercontent.com/5991192/90569725-47952980-e1a6-11ea-93bf-27c085351380.png)

Can you link to the document, please? isCOBOL documentation and samples in the trial distribution does not anything about.

**Comment by spgennard** [comment]
see https://support.veryant.com/resources/isCOBOL2009_releaseoverview.pdf

**Comment by spgennard** [comment]
Okay, got to a reasonable place to release it.. if you have coboldoc installed.. try using "right mouse"/show doc when editing.. for example:

![image](https://user-images.githubusercontent.com/5991192/91672845-b53b4100-eb28-11ea-977a-9e003a878633.png)

(must be using 6.7+)

**Comment by OlegKunitsyn** [comment]
Nice! Is it possible to add comment-blocks by using keyboard shortcuts? It was a primary goal.

**Comment by spgennard** [comment]
What keystroke are you thinking of?

And what would the contents be?

**Comment by GitMensch** [comment]
> And what would the contents be?

That's too "on-site-specific", and likely also "per-project". Therefore I'd suggest using a template ".tmpl"  that contain whatever the local template it - which also takes care of different users using different COBOL documentation tools.

I'd suggest to have the template names fixed "per use" (see below) and search if there's a template next to the file (and if not then all the way up to the workspace root), do an exchange of _some_ predefined variables (like program/function/(section/paragraph name, author, `USING` items) and then insert it to the appropriate place.

In any case there would be the need of at least two templates:
* one for the program/function - containing at least the `PROCEDURE DIVISION USING` items
* one for sections/paragraphs
* possibly one for variables

**Comment by spgennard** [comment]
You can create per-workspace snippets and assign a keybinding to the snippet.

- https://code.visualstudio.com/docs/editor/userdefinedsnippets
- https://stackoverflow.com/questions/44312494/how-to-create-per-workspace-snippets-in-vscode

**Comment by OlegKunitsyn** [comment]
Sorry for misunderstanding.... Shortcut to `coboldoc generate src/* -o doc` in the terminal is not a problem. 

Developers hate writing documentation, make typos and forget to update. The benefit is to save time on creating and updating of the doc-blocks, delivering a minimal documentation for COBOL software:
- file-descriptor, on the top of the file
- program-descriptor, on the top of the program, by taking into account Linkage section
- function-descriptor, on the top of the function, by taking into account Linkage section

There is nothing new.

**Keystrokes**
Does not matter which one to choose. 

JetBrains
https://www.jetbrains.com/help/idea/working-with-code-documentation.html#add-new-comment

Eclipse
http://www.eclipseonetips.com/2010/05/05/add-comments-and-javadocs-in-eclipse-with-a-single-keystroke/

Visual Studio
https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2019

**Formats**

Formatting standards of the doc-blocks are dialect-dependent and partially described in https://github.com/brunopacheco1/coboldoc i.e. MSDN-like for Visual COBOL / Raincode COBOL, Javadoc-like for isCOBOL
Actual format of a file could be chosen by https://github.com/spgennard/vscode_cobol#shortcuts
For dialects without documented format i.e. GnuCOBOL, ICOBOL, Enterprise COBOL, I suggest default https://github.com/brunopacheco1/coboldoc#comment-blocks which is Javadoc-like.

Freedom of mixing several standards in a project leads to additional entropy and considered counterproductive from the Quality Assurance perspective. `Ordnung muss sein` :)

**Comment by spgennard** [comment]
It looks like "[COBOLDoc](https://github.com/brunopacheco1/coboldoc)" project has stalled with a lot of outstanding issues.

I will leave the existing support in place but if the COBOLDoc project does not progress in the next couple of weeks, I will look at the pulling the support as it is not functional enough to be good enough for the "real" world applications (sadly).

**Comment by OlegKunitsyn** [comment]
Let me comment given bullet points one by one:

>lot of outstanding issues

All those issues are enhancements.

>does not progress

There is no deadlines in a community-driven development.
>not functional enough

No bugs open. The tool is up and running in my projects (at least).
>COBOLDoc state

Not archived. What is your SLA? Version incrementing on weekly basis is not a problem.

>Do you intend to work on its issues?

I'm a contributor, too. I've contacted alive COBOL vendors collecting doc-blocks standards and code samples and put the finding in the topic. I have an idea to rewrite cli to yarn, because I personally like it :) but there is no real reason for that.

>leave the existing support

Feel free. The goal of this topic was to add *auto-documentation to COBOL sources* but not an integration with an external tool.

**Comment by spgennard** [comment]
I consider the issues such as the lack of support of classes, methods, entry points and other language structures as a part of the normal use of COBOL, therefore I would say they are bugs.

Support for the doc comments and the viewer go hand in hand, if one goes there is no point in promoting something that is unfortunately incomplete.

I think I understand your view point and I wish you well.

**Comment by spgennard** [comment]
For the record, the auto doc was functional but not as refined as I would like it.. here is the screenshots of it in action.

![image](https://user-images.githubusercontent.com/5991192/96225994-d9909700-0f89-11eb-8dc8-c2da81051ea9.png)

![image](https://user-images.githubusercontent.com/5991192/96226039-eca36700-0f89-11eb-81ff-b7849d550da2.png)
