### ISSUE TITLE
How to add own file extensions to the cobol sourceview?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#190]
In 1b360e9cd7fcb27c0200111678061aa1f9e9e84f#diff-756270bd9aa2a25997101e0a66fbb0a4L93 I see that the list is hard-wired - would it be possible to move this list completely to the extension settings, or at least be able to add file extensions there? [BTW:: at least in this commit "cobol" is included twice in that `switch`]

Maybe it is possible and more useful to do this per file type (which can be setup in the user/workspace settings) instead of per file extension? But then we'd have to setup a file type for COBOL copybooks, so I'm not sure about that.
But given copybooks - we do have a list of those in the settings already (seeing the copybooks [which are already setup in this extension's settings and in the task for the compiler] was the actual reason for this issue...)

Side note: We neither have "Jcl" nor "Hlasm" nor "Pli" - please use "COBOL" instead of "Cobol", too.

Being able to adjust the list of "source view types" may be nice, too (most PC based COBOL neither have HLASM nor PL/I and often no JCL either).

BTW: How are the entries in the source view sorted?

**Comment by spgennard** [comment]
The sourceview is still experimental and requires more work on it,  including the configuration side.

I created it to mimic the flat source view often seen in mainframe editor but I am unsure if I will be ever able to achieve it.

It is still lacking in core functionality, so for the moment configuration enhancements will hinder it's development.

**Comment by GitMensch** [comment]
Thank you for the explanation I suggest to leave this issue open as a reminder about possible configuration and how this may(not) be achieved and only "fix" the COBOL spelling whenever you do the next work in that area for now.
