### ISSUE TITLE
Please add output for finished metadata processing

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#193]
When I use the appropriate option from the command palette I see in the output pane:

> Starting to process metadata from workspace folders (on demand)

... and then nothing more. therefore I'm not sure there's actually anything done. Is it?

Can you please:

* output the current folder (if that information is reasonably available) that is processed
* add a final "workspace processed in xyz seconds"

In case there is something like this in 6.6.40 - how can I debug why this doesn't happen?

**Comment by spgennard** [comment]
Fyi - If the overall time is >0.5secs the message is displayed, otherwise it is not.

**Comment by GitMensch** [comment]
Good to know. I still suggest to add a "metadata processing finished in n secs" in any case, this way a user knows that something did happen.

**Comment by GitMensch** [comment]
Thanks, despite the "extra" directories it shows (see #194) I can now see every folder is parsed as expected and get a final output of "Completed scanning all COBOL files in workspace              (3755.00ms)"

Works!

**Comment by GitMensch** [comment]
Rechecked with 6.7.0, the output is still there, but it only gets shown all at once (at least with vscode 1.48.0), so I've stared it twice (the first time needed 114574ms [non-cached file access], the additional ones take ~5 seconds).

Previously (I _think_ it was 6.4.3) I've seen "starting to process"... directly, then have seen the folders being printed one by one and then the completion message.

@spgennard Can you please inspect why the printing is now not seen directly?

**Comment by spgennard** [comment]
@GitMensch - It appears to be because I am using async/await, if I remove this the output appears quicker but blocks (as expected)

**Comment by GitMensch** [comment]
yay...

First: Thank you for the explanation. second: is there something like an explicit flush we may can use in the async thread?
If not: can the "controller" (that does the wait) do the output for the "worker", then await() again?

**Comment by spgennard** [comment]
I've not found any way of flushing the output to see if this is the reason.

I am going to look and see if I use a different mechanism to show that something is happening in the background.
