### ISSUE TITLE
"combined Workspace and CopyBook Folders to search" should only contain workspace folders with relevant files

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#194]
Because of a setup that has multiple relative and one absolute path - and the same workspace definition being used for both Windows and GNU/Linux with different absolute paths (see https://github.com/microsoft/vscode/issues/105290 to get the idea) I currently see the following output (/projects/project1 is the directory where the workspace definition is):

~~~
  Combined Workspace and CopyBook Folders to search:
   => /projects/project1/src
   => /projects/project1/src/subProject1
   => /projects/project1/src/subProject2
   => /projects/project1/src/subProject3
   => /projects/project1/X:/common
   => /home/all/common
   => /projects/project1/sql
   => /projects/project1/config
~~~

I'd expect `/projects/project1/X:/common` not to be in there as a check should raise ENOENT for that folder. `/projects/project1/sql` and `/projects/project1/config` _may be removed there, too as it does not contain any files that are evaluated by the extension and checking this _once_ should provide better performance than checking all files in there each time.

**Comment by spgennard** [comment]
No validation is done on workspace folders, if they are present it assumes they are valid or will become valid.

The directory is technically a valid Linux directory, it just does not exist.

**Comment by GitMensch** [comment]
> No validation is done on workspace folders, if they are present it assumes they are valid or will become valid.

I understand that this is the current approach, this issue  is about the suggestion to change that,

**Comment by spgennard** [comment]
Not sure that is a good idea as the folder may appear late r and monitoring auto mountable areas is not nice.

Why not use links/junctions to resolve the issue?

**Comment by GitMensch** [comment]
The issue is that at least one of the out-of-tree path is actually user-specific and there's no option to use `{env:USER}` in the folder definition currently. But if you find it to be not reasonable to "skip" the folders that _currently_ don't contain sources relevant to this extension that's of course your decision to take (which should result in closing that issue then).

I'm not sure about this after your explanation "may be there later" but would tend to: if added later then a cleanup of the meta data should fix that issue; better not monitor folders which contain only unrelated files (or even do not exist [yet]). That part is the "more general" issue in this discussion so I'll rename it.

**Comment by GitMensch** [comment]
In any case I invite you to vote for the referenced vscode issue which is now in the backlog...

**Comment by spgennard** [comment]
Yes, I will.

**Comment by GitMensch** [comment]
Closed as this is unlikely to be adjustded.
