### ISSUE TITLE
Can we include this extension in the debugging view (current insider feature)

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#197]
I do wonder if it is possible to register this extension to include the "show definition" command to the `navigation` group in the variable context menu or if this must be done from the debugging extension - see https://github.com/microsoft/vscode/issues/70377 for details.

**Comment by spgennard** [comment]
Reading the link, it most certainly will need to be done in each COBOL debugger extension.

**Comment by GitMensch** [comment]
Thanks for the check.
