### ISSUE TITLE
problemMatcher: please add code attribute where possible

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#198]
For MF ERRFORMAT(2) the code attribute is already part of the pattern regex, it is just not included as attribute: `COBCH\\d+` can be simply grouped and placed into the `code` attribute.
mf-msbuild and errformat(3) likely have something similar, but it looks like that isn't matched yet.

OpenCOBOL and COBOL-IT doesn't have it, GnuCOBOL 3.1 RC2 has it optional (at the end within [], for details see https://github.com/spgennard/vscode_cobol/issues/145#issuecomment-677652274), so this _may_ need two different regexes (first with, then without the diagnostic code).

Adding this to the problemMatches will definitely help when you have many diagnostics (I parse the diagnostics of a huge workspace and they are... huge), both with filter and find.

**Comment by GitMensch** [comment]
Please reopen this issue, the `code` attribute is still not set for any default pattern.

**Comment by GitMensch** [comment]
OK, so we have a code for MF errformat'2' (I _tend_ to leave the COBCH prefix in [do you happen to know what it means?], similar to MS' C1234 messages) - is there nothing like that in the errformat'3' or mfcobol-msbuild at all (I guess in an additional line)?

Please reopen until the GC-specific code markers are also included (see comment above).

**Comment by spgennard** [comment]
COBCH - COBol CHecker 

The COBOL CHEKCKER is the syntax parser of the compiler.

**Comment by vladhietala** [comment]
This changes broken my problem matcher.

My task.json 
``` jsonp
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "options": {
        "env": {
          "COBCPY": "${workspaceFolder}\\cpy;${workspaceFolder}\\..\\..\\biblioteca\\cpy",
          "cwd": "${workspaceFolder}\\fontes\\"
        }
      },
      "label": "Compile to INT",
      "type": "process",
      "command": "cobol",
      "args": [
        "${file}",
        "int(${workspaceFolder}\\fontes\\)",
        "cobidy(${workspaceFolder}\\fontes\\)",
        "nognt",
        "anim",
        "move-len-check(TRUNC)",
        "warning(2)",
        "errformat(2)",
        "errlist(verbose)",
        ";"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": true,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": false
      },
      "problemMatcher": "$mfcobol-errformat3"
    },
    {
      "options": {
        "env": {
          "COBCPY": "${workspaceFolder}\\cpy;${workspaceFolder}\\..\\..\\biblioteca\\cpy"
        },
        "cwd": "${workspaceFolder}\\fontes\\"
      },
      "label": "Compile to GNT",
      "type": "process",
      "command": "cobol",
      "args": [
        "${file}",
        "cobidy(${workspaceFolder}\\fontes\\)",
        "gnt",
        "anim",
        "errformat(3)",
        ";"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": true,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": false
      },
      "problemMatcher": "$mfcobol-errformat3"
    },
    {
      "label": "Compile to EXE",
      "type": "shell",
      "command": "remove-item ${workspaceFolder}\\fontes\\${fileBasenameNoExtension}.* -include *.obj, *.int, *.gnt",
      "problemMatcher": [],
      "dependsOrder": "sequence",
      "dependsOn": ["Compile_OBJ", "Link_EXE"],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    },
    {
      "label": "Link_EXE",
      "type": "process",
      "command": "cbllink",
      "args": [
        "-O${workspaceFolder}\\fontes\\${fileBasenameNoExtension}.exe",
        "${workspaceFolder}\\fontes\\${fileBasenameNoExtension}.obj",
        "extsm.obj",
        "-Rm"
      ],
      "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": true,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": false
      },
      "problemMatcher": []
    },
    {
      "options": {
        "env": {
          "COBCPY": "${workspaceFolder}\\cpy;${workspaceFolder}\\..\\..\\biblioteca\\cpy",
          "cwd": "${workspaceFolder}\\fontes\\"
        }
      },
      "label": "Compile_OBJ",
      "type": "process",
      "command": "cobol",
      "args": [
        "${file}",
        "obj(${workspaceFolder}\\fontes\\)",
        "int(${workspaceFolder}\\fontes\\)",
        "csi",
        "anim",
        ";"
      ],
      "problemMatcher": "$mfcobol-errformat3",
      "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": true,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": false
      }
    }
  ]
}
``` 
And my output using "Compile to Int" task
```
Executing task in folder user.name: C:\Program Files (x86)\Micro Focus\Net Express 5.1\Base\bin\cobol.exe \\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\pw09017b.cbl int(\\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\) cobidy(\\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\) nognt anim NOCHECKNUM move-len-check(TRUNC) warning(2) errformat(2) errlist(verbose) ; 

Micro Focus Net Express V5
Version 5.116.0022 Copyright (C) Micro Focus 1984-2018. All rights reserved.
URN AXCGG/AA0/00000
Micro Focus Embedded HTML Preprocessor
Version 5.1.16.01 Copyright (C) Micro Focus 1984-2018. All rights reserved.
**    COBCH1247W Truncated MOVE. Source length (265) exceeds target length (255)  : \\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\pw09017b.cbl(1754,65)
            move ws-command-exec                   to rlbk
**    COBCH1247W Truncated MOVE. Source length (255) exceeds target length (200)  : \\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\pw09017b.cbl(1910,58)
            move ws-command-exec                   to rlbk
**    COBCH1247W Truncated MOVE. Source length (255) exceeds target length (200)  : \\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\pw09017b.cbl(1938,58)
            move wid-pd99800 to whs-arquivo
**    COBCH1247W Truncated MOVE. Source length (265) exceeds target length (255)  : \\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\pw09017b.cbl,\\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\..\..\biblioteca\cpy\PC
* Checking complete with no serious errors
The terminal process "C:\Program Files (x86)\Micro Focus\Net Express 5.1\Base\bin\cobol.exe '\\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\pw09017b.cbl', 'int(\\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\)', 'cobidy(\\10.2.2.20\Sistemas\P\11.68.00.26\usuario\user.name\fontes\)', 'nognt', 'anim', 'NOCHECKNUM', 'move-len-check(TRUNC)', 'warning(2)', 'errformat(2)', 'errlist(verbose)', ';'" terminated with exit code: 4.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by spgennard** [comment]
@vladhietala - you compiling with "errformat(2)" with Net Express but are using a problem matcher for errformat"3" from Visual COBOL.

You might be better off using the "mfcobol-errformat2-netx-sx" problem matcher

**Comment by vladhietala** [comment]
Sorry, i trying compiling using others matchers and when copy/paste I forgot to back to original. I used errformat3 for months and now was broken. Btw, now i using my UserDefined problem matcher.

**Comment by spgennard** [comment]
The Visual COBOL version of the ERRFORMAT"3" has a COBCH present in the line but the Net Express version which is now being used to identify the error code... hence it can not be used for the Net Express format of the error message.

**Comment by GitMensch** [comment]
Reference for @vladhietala's report: There's a new mfcobol-errformat3-netx-sx pattern available, should be working fine again: 45c47be390c4ae68d9002be6509abc0e39ad18a5 and c240e6d2bc08bababe2482a1a67d6828e93a7566

**Comment by GitMensch** [comment]
@spgennard: Can you please verify that there's no code available in the messages that currently are matched by  `mfcobol-msbuild` (I _guess_ they may be included in an additional line`).

And please include the (optional) code for gnucobol3 (see comment above), thanks.

**Comment by GitMensch** [comment]
@spgennard, The MF ones seems quite fie now.
Please repopen and add code attribute to GnuCOBOL3 (does not apply to OpenCOBOL or C*IT).

It _can_ happen on any severity and is always at the end of the disgnostic, wrapped in ` [$code]`, here are some samples:

>prog.cob:54: warning: expression '1' EQUALS '1' is always TRUE [-Wconstant-expression]
prog.cob:54: warning: PERFORM ONCE since UNTIL is always TRUE [-Wadditional]
prog.cob:59: warning: expression '115' LESS THAN '16' is always FALSE [-Wconstant-expression]
prog.cob:61: warning: offset of 'var' out of bounds: -98 [-Wignored-error]
prog.cob:62: warning: expression '115' GREATER THAN '16' is always TRUE [-Wconstant-expression]
prog.cob:71: warning: expression '115' LESS THAN '16' is always FALSE [-Wconstant-expression]
prog.cob:73: error: offset of 'var' out of bounds: -99
prog.cob:74: warning: expression '115' GREATER THAN '16' is always TRUE [-Wconstant-expression]
prog.cob:82: warning: expression '15' EQUALS '115' is always FALSE [-Wconstant-expression]
prog.cob:85: warning: expression '115' EQUALS '15' is always FALSE [-Wconstant-expression]
prog.cob:54: warning: expression '1' EQUALS '1' is always TRUE [-Wconstant-expression]
prog.cob:54: warning: PERFORM ONCE since UNTIL is always TRUE [-Wadditional]
prog.cob:59: warning: expression '115' LESS THAN '16' is always FALSE [-Wconstant-expression]
prog.cob:61: warning: offset of 'var' out of bounds: -98 [-Wignored-error]
prog.cob:62: warning: expression '115' GREATER THAN '16' is always TRUE [-Wconstant-expression]
prog.cob:71: warning: expression '115' LESS THAN '16' is always FALSE [-Wconstant-expression]
prog.cob:73: error: offset of 'var' out of bounds: -99
prog.cob:74: warning: expression '115' GREATER THAN '16' is always TRUE [-Wconstant-expression]
prog.cob:82: warning: expression '15' EQUALS '115' is always FALSE [-Wconstant-expression]
prog.cob:85: warning: expression '115' EQUALS '15' is always FALSE [-Wconstant-expression]

> prog.cob:7: warning: redefinition of 'prog' [-Wadditional]
prog.cob:3: note: 'prog' previously defined here [-Wadditional]
prog.cob:23: error: redefinition of program name 'foo'
prog.cob:31: error: redefinition of program name 'prog'
prog.cob:42: error: redefinition of 'foo'
prog.cob:35: note: 'foo' previously defined here
prog.cob:42: error: redefinition of program name 'foo'
prog.cob:49: error: PROCEDURE DIVISION header missing
prog.cob:50: error: redefinition of program name 'samename'

> prog.cob:18: error: OPEN REVERSED is obsolete in GnuCOBOL [-Werror=obsolete]
prog.cob:22: error: OPEN REVERSED is obsolete in GnuCOBOL [-Werror=obsolete]

It _may_ be possible to use an optional group to not increase the necessary patterns by using something like the following:

* limit message `*.` to not contain `[`: `[^[]*` (there may be a more elegant way)
* optional group with the code including its wrapping (this will be ignored
* nested group with the additional content

I think it would look like:

```diff
             {
                 "name": "gnucobol3-note-cobc",
-                "regexp": "^(.*):(\\d+):\\s.*([nN]ote|Anmerkung|[nN]ota):(.*)$",
+                "regexp": "^(.*):(\\d+):\\s.*([nN]ote|Anmerkung|[nN]ota): ([^[]*)( \\[(.*))\\]?$",
                 "file": 1,
                 "line": 2,
-                "message": 4
+                "message": 4,
+                "code": 6
             },
```

[online test](regexr.com/5dmc7) (without the double `\\`) - obviously this must be applied to the common pattern and the one for note, warning, error

**Comment by GitMensch** [comment]
... a similar approach of using optional and/or nested groups may also allow the amount of pattern definitions to be decreased.

**Comment by GitMensch** [comment]
@spgennard just a friendly ping on the GnuCOBOL matchers (should I open a new issue for that while the original one was about it already?) and the possibility to improve the MF matchers

**Comment by GitMensch** [comment]
@spgennard do you prefer to reopen this one or should I create a new one about adding the optional code attribute for the GnuCOBOL problem matchers as outlined above (and originally brought up in the starting post of this issue)?
