### ISSUE TITLE
Do we need to tweak the pre_parse_line_limit?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#199]
The setting's description says for coboleditor.pre_parse_line_limit: "used to determine if source is COBOL or a CopyBook"; but as I've already have the file extensions setup to include "myext" in coboleditor.copybookexts, then why does the extension need an additional setting?
In my case the files with myext include a changelog and documentation in the header, which sometimes has > 100 entries so I've tried to increase the setting to 250, but I still get "no symbols found in document" in the outline for the file...

I'm still not sure that there's a need for that setting (just skip initial empty lines, comment lines and directive lines and look for the first 5 other lines or so), but _guess_ the documentation for it may be confusing.

**Comment by spgennard** [comment]
The file extension only tells you that the file is related to COBOL, it does not help me "guess" how the copybook is used.

The extension need to "guess" if the copybook is part of a storage area or the procedure division.

**Comment by GitMensch** [comment]
Then I suggest to change the doc to say so:

"used to determine if source is a program/function or part of DATA DIVISION / PROCEDURE DIVISION"

.. still there's the question why the workplace setting of `coboleditor.pre_parse_line_limit: 250` did not helped (I had likely not restarted after adjusting that, if this is necessary the extension doc should give a hint on that).

**Comment by spgennard** [comment]
> .. still there's the question why the workplace setting of coboleditor.pre_parse_line_limit: 250 did not helped (I had likely not
 > restarted after adjusting that, if this is necessary the extension doc should give a hint on that).

I guess you will need to share the first 250 lines, so I see what is happening (understand if you don't want to place on the issue)..

if that is the case, email me stephen @ gennard . net

**Comment by GitMensch** [comment]
Retested with current version of this extension:

* the documentation entry should definitely be adjusted
* whenever changing `oboleditor.pre_parse_line_limit` (at least via workspace setting) a reload of the complete vscode window is necessary

If I change it from 25 to 250 nothing happens, after reload I see the outline, after changing it back to 25 reopen only that file has consequence. Reloading the window and the outline is gone again. Is it possible to remove the need for the reload in this case? If not then it should be mentioned in its doc entry.

In general: is it possible to change the approach of fixed lines to "always read only 5 lines, but only increase the counter for lines that are not empty or comment lines or directive lines" and dropping that setting - or changing its meaning to "lines that are neither [see above]")?

**Comment by GitMensch** [comment]
Just a ping after rechecking: I still suggest to adjust the documentation, would I be sure enough what the good/correct short way to tell it would be I'd do a PR...

Concerning the other part of this issue: is it reasonable to count empty/comment lines or can we drop that (= skip those lines)?
(If we do we may not need this setting any more).
