### ISSUE TITLE
The keyword BINARY is not colored when followed by a binary size override declaration

### ISSUE THREAD

**Issue by MCEmperor** [spgennard/vscode_cobol#201]
**Describe the bug**
The `binary` keyword is not highlighted when a _binary size override_ is used.

**To Reproduce**
1. Create a COBOL source code file
2. Define a COBOL variable with a _binary size override_ declaration. For example: `77 myVar binary(4) pic S9`.
3. The `binary` keyword is not colored as keyword.

**Expected behavior**
I expect `binary` to be syntax-colored, regardless of whether it is immediately followed by a parenthesis.

----

A _binary size override_, sometimes called _binary allocation override_, affects the number of bytes allocated for the variable, regardless of the `picture`. For example, `binary pic 9(4)` would normally cause two bytes to be allocated for that variable, because the picture's maximum value, 9999, fits into two bytes. However, `binary(4) pic 9`, for example, causes four bytes to be allocated for the variable, even though the picture implies a single byte to be allocated. [See here](https://www.microfocus.com/documentation/visual-cobol/VC23/EclWin/HRLHLHDRMF01U909.html).

**Comment by spgennard** [comment]
Author: Stephgen Gennard <stephen@gennard.net>
Date:   Mon Sep 14 21:32:13 2020 +0100

    The keyword BINARY is not colored when followed by a binary size override declaration Fix#201
     - added ACU specific storage modifiers
