### ISSUE TITLE
Issue with Metadata cache setting?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#206]
When using the command "COBOL: process files in workspace for metadata" I now get:

> Metadata cache is off, no action taken

As this is a multi-folder workspace (primarily because of the suggestion to do so here) the workspace setting should be used and that has:

```json
		"coboleditor.cache_metadata": "storagepath",
		"coboleditor.parse_copybooks_for_references": true,
		"coboleditor.pre_parse_line_limit": 250,
```

**Comment by kabel** [comment]
Looks like fallout from merging the `coboleditor.cache_metadata` and `coboleditor.cache_directory_strategy` settings.

**Comment by spgennard** [comment]
resolved

**Comment by GitMensch** [comment]
Thanks for 8fa9f320c10b498c9ff675425bcb00d302abe795 (only not referenced because of missing space)
