### ISSUE TITLE
Outline regression starting at 6.7.17

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#207]
**Describe the bug**
The outline is empty for valid COBOL workspace files. See attached temp workspace.

**To Reproduce**
1. Open workspace file main.cbl
2. Expand outline

**Expected behavior**
The outline is populated with the file's symbols

**Screenshots**
6.7.17
![image](https://user-images.githubusercontent.com/675956/93217542-d1490000-f72e-11ea-849e-4b3699376c9c.png)

6.7.16
![image](https://user-images.githubusercontent.com/675956/93217655-f178bf00-f72e-11ea-908b-979d175e69ca.png)

**Comment by spgennard** [comment]
resolved

**Comment by GitMensch** [comment]
To add the reference: 6fa59af77391543e391a8ab2d300fe2f74aedcf3 - thanks for the report and fix.
@spgennard Shouldn't the outline parsing and construction be something that may be automatically checked in the future?

**Comment by spgennard** [comment]
@GitMensch It does have parsing tests

The issue was from the vscode settings, so Full GUI automation would be required to test it.

Ironically it was the abstracting of the settings for testing that compounded the issue.
