### ISSUE TITLE
Feature Request: Add config setting to allow finding definitions in _any_ workspace file

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#208]
The COBOL metadata cache is getting better, but, as people keep reporting, the expectation of what gets cached where is still confusing. I'd like a setting that allows me to see/use cached symbols (data elements, constants, paragraphs, etc) in _any_ file in my workspace, regardless of where the copybook is copied in via `COPY`.

This feature would allow me to quickly use COBOL references in different files without having to double-check my `COPY` statements _and_ allow copybooks that (implicitly) depend on other copybooks to reference symbols from their dependency. Obviously these could lead to compile errors if I forget to actually tie everything together with the proper, `COPY` statements, but I can live with that.

**Comment by spgennard** [comment]
This would cause a huge amount of false/out of scope results and lead the developer to use something that does not exist.

Plus, it would be very very slow in large projects.

I think you need to think about the problem in a more editor friendly way and propose an alternative.

**Comment by kabel** [comment]
I totally understand your concern about this causing out-of-scope references and performance hit. That I why I propose such a feature to be hidden under an optional configuration setting so we can test in multiple environments and get actual results rather than speculation. Likewise with this taking a performance hit, I would expect such a feature to only work with symbols that have _already_ been cached by using the `coboleditor.process_metadata_cache_on_start`. When all the parsing happens on startup, in the background, the performance has not been an issue for me on my large workspaces. I would not expect this new feature to trigger a parse of any files (outside of saving/updating the copybook source file).

It would be good to have a reference workspace that explains the problem I'm trying to work around. I have two copybooks that depend on each other (working-storage in one file and procedures in another). They do not reference each other via `COPY` statements because they must be separated in different divisions/sections of the utilitzing program(s). While editing the procedure copybook, I want IntelliSence to provide me the autocomplete suggestions from the implicitly dependent working-storage copybook. Similarly, I want to use the vscode 'Go to definition' and 'Go to references' to see _potential_ resolution of these symbols. 

The main program ties these dependencies together in their appropriate divisions. Current features allow me to navigate to these copybooks and use the symbols in the main program, but I can't reach the symbols from the copybook file. I _am_ able to dump the metadata cache and see that it knows about the symbols I'm interested in.

See attached comment-annotated workspace (`main.cbl` and `Shared\better.cbl`).

[Temp.zip](https://github.com/spgennard/vscode_cobol/files/5226334/Temp.zip)

**Comment by spgennard** [comment]
If you enable parse_copybooks_for_references and use portable COBOL syntax for the COPY statement, it will help.

```json
{
    "coboleditor.cache_metadata": "storagepath",
    "coboleditor.copybookdirs": [
        "CopyBooks",
        "OldCopyBooks"
    ],
    "coboleditor.copybookexts": [
        "cbl"
    ],
    "coboleditor.parse_copybooks_for_references": true
}
```


```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. main.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
           01 WS-FIELD PIC X(80).
           COPY "betterWS" in "Shared".
       PROCEDURE DIVISION.
           PERFORM foo.
           PERFORM bar.
           PERFORM better.
           STOP RUN.
           COPY "foo.cbl" in "Shared".
           COPY "bar" in "Shared".
           COPY "better.cbl" in "Shared".
```

and them "peek" will work eg:

![image](https://user-images.githubusercontent.com/5991192/93259162-50721e80-f797-11ea-9a2d-a9d74d77ec83.png)

**Comment by kabel** [comment]
Thanks for the feedback. I was already using `coboleditor.parse_copybooks_for_references` in my user settings.

The peek is already working from `main.cbl` using the existing syntax shared. Our house rules (and personal preference) require the `COPY` statements to only use the quoted token alone. I could try to get our house rules changed, ⛰️. It would be nice for the opencopybook provider to also support the `OF` token in addition to `IN`. That's from our internal/house preprocessor and the COBOL flavors we support (ILE COBOL, MCP COBOL ASNI-85).


It's the intellisense from the copybook that I'm most interested in. As I do copybook (library) development, I hate having to flip back and forth to remember what I called some data element. Also, I think the default (generated copybook symbol) is leaking to intellisense:
![image](https://user-images.githubusercontent.com/675956/93261103-dfffd900-f767-11ea-9a02-ebb6f2b5cb9f.png)

**Comment by spgennard** [comment]
If I remember right the "better" & "betterWS" is coming from the default editor IntelliSense for text, so you can turn it off.

```json
    "editor.suggest.showWords": false
```

**Comment by kabel** [comment]
Ah, could be. I wouldn't dare turn that off because it saves me on repeat data element names that it can't find.

I may have been fooled by the metadata dump:
![image](https://user-images.githubusercontent.com/675956/93262739-5ac9f380-f76a-11ea-9ebc-83065117916e.png)

**Comment by spgennard** [comment]
If you using 6.7.25 or later, you could try some out an embedded comment to include the copybook:

```cobol
 *> cobol-include-copybook Shared/foo.cbl
```

For example:

```cobol
       better.
      *> THE FOLLOWING LINE DOES _NOT_ SUPPORT INTELLISENSE FROM
      *> betterWS.cbl
           MOVE ZEROS TO BETTER-DATA-ELEMENT.
           display "this procedure is coming soon...".
      *> THE FOLLOWING LINE DOES _NOT_ SUPPORT INTELLISCENSE FROM
      *> Shared\foo.cbl nor CopyBooks\Shared\foo.cbl


      *> cobol-include-copybook Shared/foo.cbl
           PERFORM foo.
```

You get:

![image](https://user-images.githubusercontent.com/5991192/93268193-b44f1400-f7a4-11ea-95d4-ff687f700811.png)

**Comment by kabel** [comment]
Wonderful. I think I may like that comment syntax so that the dependencies are explicitly defined in the files.

**Comment by GitMensch** [comment]
> If you using 6.7.25 or later, you could try some out an embedded comment to include the copybook

That's very interesting (but not documented, is it?) Do we need to type it as is (including the inline comment and spacing)? Are there more?

Can we add a setting for keywords that trigger it? Most local rules have something like "mention the copybooks you need that way in a comment: xyz", so it would be useful for this specific hint to be able to be adjusted (maybe an array defaulting to one entry with the current variant?).

@kabel Do I assume right, that this feature enables you to close this FR? [note: I do see a performance issue already as mentioned in #173 ]

**Comment by kabel** [comment]
> Do I assume right, that this feature enables you to close this FR?

Yes, if this experimental comment keyword continues, It covers my needs for this FR.

**Comment by GitMensch** [comment]
I hope that this keyword option will be documented and a feature that stays (hopefully with the option to adjust the used pattern), too.
I suggest to close this issue after documentation for that feature.

**Comment by kabel** [comment]
> I hope that this keyword option will be documented and a feature that stays (hopefully with the option to adjust the used pattern), too.

Agreed. I would much prefer to configure it our have something _much_ shorter, say `*>@CIC`, giving more space to the file path/name vs `*> cobol-include-copybook`.

**Comment by spgennard** [comment]
I would prefer to avoid using any "@" prefix because they are very overloaded, not only do you get some javadoc style doc, coboldoc style comments but also structural commenters such as:  https://github.com/GuillaumeIsabelleX/gixdeko-comments

Meanwhile, I have added settings:

```json
"coboleditor.process_scanner_hints_embedded_in_comments": true
```

Which will be documented when a name/schema is agreeded.

My suguestions are:

```cobol
*> vscode.cobol.dependency: Shared/foo.cbl
*> v.c.d: Shared/foo.cbl

*> editor-hint: dependency Shared/foo.cbl
*> e-h: dep Shared/foo.cbl

*> editor-hint: copy Shared/foo.cbl
*> e-h: copy Shared/foo.cbl


Note: other languages include simular things for example:
```

---
  #pragma GCC dependency

    #pragma GCC dependency allows you to check the relative dates of the current file and another file. If the other file is more recent than the current file, a warning is issued. This is useful if the current file is derived from the other file, and should be regenerated. The other file is searched for using the normal include search path. Optional trailing text can be used to give more information in the warning message.

    #pragma GCC dependency "parse.y"
    #pragma GCC dependency "/usr/include/time.h" rerun fixincludes

----

**Comment by GitMensch** [comment]
I'd prefer to let the default not be too specific on the use case, the dependency hint can be quite useful outside of vscode or other editors, too.
Therefore I suggest to use one of the following (actually I do like the @ prefix so I've included this - the distinguishing comes from the identifier behind it, but it is your decision to keep or drop it):

```cobolfree
*> @cobol-dependency Shared/foo.cbl
*> @cobol-dependency data Shared/foo.cbl
*> @cobol-dependency procedure Shared/foo.cbl
*> @cobol-dependency function Shared/foo.cbl
```

or "more general":

```cobolfree
*> @source-dependency "Shared/foo.cbl"
```

With a format of

```
@source-dependency [type} file
@source-dependency [type} file
```

_If_ `type` is interesting at all for this plugin, then it may be one of data/procedure/program/function (the first two would be copybooks that cannot stand alone, the later two sources that may be compiled alone). If type is not interesting I still suggest to allow (and internally skip) it.
`file` may be quoted but doesn't have to as long as it does not contain spaces.

**Comment by spgennard** [comment]
Including a type does make give us a great deal as a source file can include multiple programs, multiple functions, multiple classes, interfaces, valuetypes etc..

The quotes are not necessary, as a "space" in a filename is considered illegal as it implies an implicit program-id with a space in it, which is illegal.

Using a "@" prefix could cause other ide, doc generators problems/warnings.  I understand it looks nice but being nice is not the only consideration.


     *> vscode.cobol.dependency: [Shared/foo.cbl]..
     *> v.c.d: Shared/foo.cbl

where this, say this is for "vscode", "cobol" is the extension/language and "dependancy" is the action.

or simply:

    *>  source-dependency: [Shared/foo.cbl]..

**Comment by GitMensch** [comment]
Hm, where do we stand with this? Is a default format/name already defined? Maybe we do have a configurable prefix for this hint already?
