### ISSUE TITLE
NETX/SX patterns must be extended to parse filename for diagnostics in copybooks

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#210]
With SE 5.1and `ERRFORMAT(2) COPYEXT(lib)` I see error messages like:

~~~
**    COBCH0642W Source and target start at same location  : /tmp/TO000.cob,/tmp/ext/SOME.lib(316,46)
~~~

I tried to use `$mfcobol-errformat2-netx-sx` but it includes the full given "path" as filename, and therefore does not actually mark the error (in neither of the two files). I _think_ the correct way here is to either an optional entry in the pattern ending with "," that is not used in the matcher or add a second pattern and tell the users to specify both.

Similar with VC5 (and "$mfcobol-errformat2"):

~~~
**    COBCH0656W Source and target overlap, and source is at lower address than target  : /tmp/TO000.cob,/tmp/ext/SOME.lib(1551,36,29)
~~~

**Comment by spgennard** [comment]
You mean like "mfcobol-errformat2-copybook" but for NX/SX?

**Comment by GitMensch** [comment]
OK, if there's something like that for VC already I've missed it. If it is missing for NETSX (that's SE 5.1, isn't it?) - please add it,

**Comment by GitMensch** [comment]
Please reopen, does not work here, neither with VC (there's no "copybook" pattern there), nor with SE.

Here's another message to extend the tests (without the "," also a good test for "non-copybook") on win32:

~~~
**    COBCH1209I COMP-5 is machine specific format. (future occurrences not indicated)  : X:\project\src\SOME.cob,X:\copies\STUFF.lib(49,57,52)
~~~

Note concerning the severity:
`COBCH(\\d+)([a-zA-Z])` - the symbol noting the type of the diagnostic are only the ones that are noted in the [`CHANGE-MESSAGE` directive](https://www.microfocus.com/documentation/enterprise-developer/ed30/Eclipse/HRCDRHCDIR1S.html), so the "better" pattern would be: `COBCH(\\d+)([SEWI])`

Note: I've just verified by test that both S+E are "translated" from vscode to severity=error, W to warning and I to info.

**Comment by spgennard** [comment]
Added: mfcobol-errformat3-copybook

I assume the error position is in:
 X:\project\src\SOME.cob,
rather than:
 X:\copies\STUFF.lib

true?

**Comment by GitMensch** [comment]
The error is in X:\copies\STUFF.lib at line 49, columns 52-57, included from X:\project\src\SOME.cob.

In theory one may only see this issue when included from a specific source, which is likely the reason that MF reports it that way.
`cobc` currently doesn't report that, whenever it will add it (surely will be done some day) it will prefix the error message line like gcc does (included from xyz:518\nincluded fromabc:123\ncurrent_message).

**Comment by GitMensch** [comment]
According to https://www.microfocus.com/documentation/visual-cobol/VC232/EclUNIX/BKCYCYFLAGS001F029.html we may also see an `U`, leading to `COBCH(\\d+)([USEWI])` to be a reasonable replacement for all COBCH matching patterns.

**Comment by GitMensch** [comment]
Please reopen until solved.

https://github.com/spgennard/vscode_cobol/blob/42e41c98fc5b55f06e59bbb2af82e164eee4215e/src/test/suite/co_mfcobol-errformat3-copybook.txt, which was actually ERRFORMAT'2' is not matched correctly yet.

**Comment by spgennard** [comment]
The mfcobol-errformat3-copybook matcher is not required and will be removed, simular the test file will also be renamed (& content corrected)

**Comment by GitMensch** [comment]
I see, the sample code is clear.

But the deleted  src/test/suite/co_mfcobol-errformat3-copybook.txt should have actually be src/test/suite/co_mfcobol-errformat2-copybook.txt (VC + ERFFORmAT'2') and this is also where the problem occurs that this issue is about.

Additional: either the errformat3 versions should have COBCH removed from the "code" expression or preferably, COBCH should be included in the errformat2 versions, too.

**Comment by GitMensch** [comment]
I just wanted to reopen that because of

> the deleted src/test/suite/co_mfcobol-errformat3-copybook.txt should have actually be src/test/suite/co_mfcobol-errformat2-copybook.txt (VC + ERFFORMAT'2') and this is also where the problem still occurs that this issue is about.

as it still reported a single file:

> TEST.cpy cannot be opened: The file "x:\test\COPIES.cob,X:\test\´cpy\TEST.cpy" cannot be read

then I've moved back to the README which says:

> NOTE: Problem matchers can be stacked in your task definition. It is recommended that any "-copybook" & "-info" problem matcher is included before simular problem matchers.

Doing so solved the issue, so: thanks again.
