### ISSUE TITLE
FR: parse sub-folders of workspace paths by default

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#211]
Reviewing the multi-folder workspace documentation and inspecting how vscode behaves shows that it is a bad idea to have a definition of

folder/src
folder/src/sub1
folder/src/sub2

[note: that was my setup used in the last weeks; all of those folders (main and sub) include programs and copybooks]

* vscode needs longer to load the workspace
* vscode shows the all sub-folders "alone" and "below" the main folder in the explorer view
* vscode shows the files twice in the explorer view (most obvious when searching there)
* vscode shows the files sometimes multiple times when using [CTRL]+[P]

The initial reason I've did this setup was the use of the workspace folders for the metadata. When I'm cleaning the metadata and recreate it after changing the workspace definition to only have "folder/src" in it, vscode is "fine" but the metadata dump now only shows the files of "/src".

Please adjust the workspace folder handling to automatically search in sub-folders, if you don't want that to be the default behavior for reasons I don't understand, then please create a setting to allow this.

BIG thanks.

**Comment by spgennard** [comment]
Does *sub1*, *sub2* contain copybooks or programs?

**Comment by GitMensch** [comment]
src, src\sub1 and src\sub2 **al**l include:

* programs
* copybooks (headers)
* copybooks (data definitions)
* copybooks (code)

**Comment by spgennard** [comment]
If src/sub1 and src\sub2 contain programs then they need to be present in the workspace.

The general rule of thumb is:
 - programs are found in the workspace
 - copybooks are found in the workspace and supplemented with copybook extensions setting

Can you reconsider the structure of your project?

**Comment by GitMensch** [comment]
> The general rule of thumb is:
> 
> * programs are found in the workspace
> * copybooks are found in the workspace and supplemented with the copybook dirs setting

That's a rule of thumb very specific to this etxension, isn't it?
The [vscode docs](https://code.visualstudio.com/docs/editor/multi-root-workspaces) don't give a clue that no "programs" should be below the main workspace - and actually all its samples show code in sub-folders.

> Can you reconsider the structure of your project?

That structure is over 20 years old and cannot be changed, but as outlined above I don't think the structure is wrong.


I had a short hope that `cache_metadata_max_directory_scan_depth` would solve this and was even excited when I've seen that it had a default of 32.

Recreated metadata:

> Directories scanned : 11
> Directory Depth     : 0

Redid after removing the duplicate entries (sub-paths of "src"):

> Directories scanned : 4
> Directory Depth     : 0

So it doesn't seem to parse for metadata in sub-directories.


Here are three approaches I see to be reasonable:

1 as requested in this issue:
   * programs are found anywhere in the workspace
   * copybooks are found anywhere in the workspace and supplemented with the copybook dirs setting
   * no special setting for the depth needed (if the workspace is too big vscode does complain already)
2 as an alternative
   * programs are found in the workspace folders explicit named (no subdirectories) and supplemented with a new programs dirs setting (only used to calculate/resolve metadata)
   * copybooks are found in the workspace folders explicit named and supplemented with the copybook dirs setting
3 like 1, but simpler (maybe the mid-term plan)
   * all copybooks and programs are found anywhere in the workspace, no additional setting needed but an "ordering" one (which we already have for the copybooks

Obviously(?) I suggest to use option 3, a user just opens his main folder and is done; if there are multiple ones (for example in different places) then he can use the multi-workspace folder as documented (just adding another folder to the workspace) and is done.

Do you consider one of these to be reasonable, too?

Solution 1 is likely to

**Comment by spgennard** [comment]
Using your structure given.   I am unable to reproduce the issue.

I have attached a .zip and here is my COBOL panel output:

```text
VSCode version : 1.49.1
Extension Information:
 Extension path    : /home/spg/.vscode/extensions/bitlang.cobol-6.7.34
 Version           : 6.7.34
 Caching
  Cache Strategy               : workspace
  Cache directory              : /home/spg/opensource/issues/211/.vscode_cobol
 UNC paths disabled            : false
 Parse copybook for references : true
  Workspace Folders:
   => 211 @ /home/spg/opensource/issues/211
  Combined Workspace and CopyBook Folders to search:
   => /home/spg/opensource/issues/211


Starting to process metadata from workspace folders (on demand)
Completed scanning all COBOL files in workspace
 Directories scanned : 5
 Directory Depth     : 2
 Files found         : 4
 File scanned        : 2
 File up to date     : 1
 Program Count       : 2
 Entry-Point Count   : 0
 Scan copybooks      : false
Metadata Dump
 cache_metadata : workspace

 cache folder             : /home/spg/opensource/issues/211/.vscode_cobol
 Last modified            : 0
 Dirty flag               : false

Global symbols            : (made lowercase)
 main                                     => /home/spg/opensource/issues/211/folder/src/main.cbl:0
 sub1                                     => /home/spg/opensource/issues/211/folder/src1/sub1.cbl:0
 sub2                                     => /home/spg/opensource/issues/211/folder/src2/sub2.cbl:0

Paragraphs/Sections in file : none (parse_copybooks_for_references set)
```
[issue211.zip](https://github.com/spgennard/vscode_cobol/files/5255713/issue211.zip)

**Comment by GitMensch** [comment]
That's interesting as it is very much the same setup like mine, only differences:

* more folders
* more files
* caching in storagepath
* in this specific test I did now: win32

But my output says:

> Starting to process metadata from workspace folders (on demand)
> Scan aborted (elapsed time 259)

but it doesn't say anything about the reason for the abort?

**Comment by spgennard** [comment]
The code has a try-catch to handle the async abort condition, so another exception might have been raised.

I will enhance the code tonight to have better handling of the exception and add an option to show what file/directory is being parsed, which may help to shed some light on the issue but it looks unlikely it is related to parsing of sub-folders more likely something else.

**Comment by spgennard** [comment]
If you can try out 6.7.36 and let us know

If enabled "cache_metadata_show_progress_messages" it will show you the file/directory as it is being processed.

**Comment by GitMensch** [comment]
~~~
Metadata cache cleared

Starting to process metadata from workspace folders (on demand)
 Maximum time cap for meta data process set to 600000
 Directory : x:\PROJECTS\cust1\cfg
 Directory : x:\PROJECTS\cust1\proc
 Directory : x:\PROJECTS\cust1\src
  Directory : x:\PROJECTS\cust1\sql
Scan aborted (elapsed time 220)
 Directories scanned : 4
 Directory Depth     : 0
 Files found         : 4978
 File scanned        : 0
 File up to date     : 0
 Program Count       : 0
 Entry-Point Count   : 0
 Scan copybooks      : false
Error (FileSystemError):Unexpected abort
Error (FileSystemError): Unable to resolve filesystem provider with relative file path 'x:\PROJECTS\cust1\src\sub1'.
	at _handleError (d:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:706:514)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
~~~

when I click on the highlighted path I get a message:
~~~
"sub1" cannot be opened.
The file is a directory.
~~~

And when I copy that to the system Run dialog the Windows Explorer opens at this path.

I've found that the message is originally coming from "vs/platform/files/common/fileService" and evaluates to "invalidPath".

So... any clues already?

sub1 is the first alphabetical subnode of the directory src

**Comment by spgennard** [comment]
My guess is that the ****x:\**** is being treated as a relative file because everything else is pretty standard.

      Error (FileSystemError): Unable to resolve filesystem provider with relative
       file path '**x:\**PROJECTS\cust1\src\sub1'.

The stacktrace is also interesting as the extension does not appear to be on it.

**Comment by GitMensch** [comment]
> Lastly, you are using vscodium... perhaps this does something different.

Of course it does, but nothing related to free software extensions not working.

> The stacktrace is also interesting as the extension does not appear to be on it.

I _think_ it is via the extensionHostProcess which may be the bridging between the extension instructions and the OS calls (file system).
The "X:" may be an issue and it may be inside vscode.

* the workspace uses only relative files in "path" settings
* it is opened from X:\PROJECTS\cust1\cfg\CUST1.code-workspace
* when the extension prints the paths processed it only shows "x:", so it seems to only know the full path

Out of interest: can you point to the place in the extensions' code where the distinction and the access to folders and files is done?
It doesn't explicit ask for relative search, does it?

**Comment by spgennard** [comment]
```typescript
         const entries = await workspace.fs.readDirectory(folder);
...

        for (const [entry, fileType] of entries) {
            if (fileType === FileType.File) {
                const fullFilename = path.join(folder.fsPath, entry);
                await VSQuickCOBOLParse.processFile(settings, cacheDirectory, fullFilename, true, stats);
            }
            else if (fileType === FileType.Directory) {
                if (!VSQuickCOBOLParse.ignoreDirectory(entry)) {
                    const fullFilename = path.join(folder.fsPath, entry);
                    if (!VSQuickCOBOLParse.ignoreDirectory(entry)) {
                        const directoryUri = Uri.parse(fullFilename);
                        dir2scan.push(directoryUri);
                    }
                }
            } else {
                logMessage(` Symbolic link ignored : ${folder.fsPath}`);
            }
        }
````

**Comment by GitMensch** [comment]
Found the call chain:

* starting with workspace.fs.readDirectory
* calling somehow into the [fileSysteProvider](https://github.com/microsoft/vscode/blob/2cb96e9c7a9ad82b9649ea6f3508cd224d64de75/src/vs/platform/files/common/fileService.ts#L109)
* which errors when `isAbsoluteFilePath`, [declared here](https://github.com/microsoft/vscode/blob/2cb96e9c7a9ad82b9649ea6f3508cd224d64de75/src/vs/base/common/resources.ts#L368) and [defined here](https://github.com/microsoft/vscode/blob/2cb96e9c7a9ad82b9649ea6f3508cd224d64de75/src/vs/base/common/resources.ts#L273) evaluates to false

And that is effectively:

```ts
!!resource.path && resource.path[0] === '/';
````

which obviously doesn't match "x"...

So - that's the reason, looks like a big bug, either somewhere in the call chain or in the last bit.
Can you check for/create an issue on vscode for that?

**Comment by GitMensch** [comment]
It looks like the `folder` you're using here is no guaranteed URI. To create an URI from "^[a-zA-Z]:` one has to prefix it with a slash `/`.
So, _maybe_ something that is an issue with this extension or at least could be worked around here?

**Comment by spgennard** [comment]
Changed to using Uri.file in v6.7.38 rather than Uri.parse

**Comment by GitMensch** [comment]
> Changed to using Uri.file in v6.7.38 rather than Uri.parse

That works. We're nearly done, one last entry open:

> EntryNotFound (FileSystemError):Unexpected abort

The reason is that it is a multi-user/multi-environment workspace which includes two optional folders that may not exist for every developer (actually it is only one - the home directory - but as https://github.com/microsoft/vscode/issues/105290 is not implemented yet it has two of those entries with one _guaranteed_ to not exist...).

Please catch the `EntryNotFound` for workspace folders (something similar was done before with a nice output "directory not found: xyz") and we can close this issue, allowing me to check further on #173 and others ;-)
I also like the inclusion of coboleditor.cache_metadata_show_progress_messages which we got as a side-effect of this issue.

[side note: it seems a leading space is missing in the output for the error handler after ":", also seen above]
