### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#215]
- Issue Type: `Performance`
- Extension Name: `cobol`
- Extension Version: `6.7.43`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.49.0`

[bitlang.cobol-unresponsive.cpuprofile.txt](https://github.com/spgennard/vscode_cobol/files/5281023/bitlang.cobol-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by spgennard** [comment]
This performance spike is directly in line with the size of the document.    

As the spike occurs sending the contents of the source scanned result to the outline view all I can say is tweaked the "coboleditor.outline" setting or turn it off because no source code is provided.

**Comment by spgennard** [comment]
I should also say file stat is also consuming time which could be file system related, as no information is given.

For example, a remote file's stat will take longer than a local file etc..

**Comment by GitMensch** [comment]
Thank you for inspecting this! I'll try to upload a new sample when I see that again with the next version, maybe we can find possible bottlenecks that way step by step (in this case we can reopen this issue then or leave it open).

**Comment by spgennard** [comment]
The only long term solution is not to any node 'fs' api and use the workspace.fs api which is limited to only basic 'fs' functionality.

This would mean access to files outside the workspace directory structure will be prohibited and this would have an impact on some features.. well not really an impact.. impossible to include, the upside of this is that it would reduce the side of the extension :-)

**Comment by GitMensch** [comment]
New result with

- Extension Version: `6.7.51`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.49.0`

And a new [bitlang.cobol-unresponsive.cpuprofile](https://github.com/spgennard/vscode_cobol/files/5297903/bitlang.cobol-unresponsive.cpuprofile.txt) to check.

**Comment by GitMensch** [comment]
And another one - [bitlang.cobol-unresponsive.cpuprofile.txt](https://github.com/spgennard/vscode_cobol/files/5314468/bitlang.cobol-unresponsive.cpuprofile.txt) with Extension Version: `6.7.53`.

Can you spot anything in there?

**Comment by spgennard** [comment]
@GitMensch - in the latest version, I am avoiding using fstatSync to determine if it is a file.  

I have changed to using 'access' which should be okay and I can see it is better than fstatSync but it still slow.

Moving to the non-sync version is not possible as the scanner & various methods are used from places that cannot be in a promise without implementing a sync-point which just moves the issue.   I have experimented with it and it was an utter failure but a valid thing for me to try.

**Comment by GitMensch** [comment]
Thank you for working on this.

I've updated to latest version,then started metadata processing, which "looked" faster.
I've then cleared the metadata, restarted, started metadata processing again - nearly took 2-4 seconds per listed file. I've then changed `coboleditor.parse_copybooks_for_references` to false and did the same - complete workspace (12416/18595 files scanned with 5859 programs, according to the summary) finished in 86 seconds.

It looks reasonable to explicit check the code this setting handles.

**Comment by spgennard** [comment]
Are you saying it is better or not?

**Comment by GitMensch** [comment]
I think it is better now - and becomes nearly unusable when `coboleditor.parse_copybooks_for_references` is set to true

**Comment by GitMensch** [comment]
Here is an updated [bitlang.cobol-unresponsive.cpuprofile](https://github.com/spgennard/vscode_cobol/files/5363599/bitlang.cobol-unresponsive.cpuprofile.txt), this time from GNU/Linux ("nearer" than the windows version via Samba), so it may provide other hints.

**Comment by spgennard** [comment]
I have been working on the "out of process" scanner and if you want to try out an early drop, you can pick it up from the releases tag:
 https://github.com/spgennard/vscode_cobol/releases/tag/6.9.0

**Comment by spgennard** [comment]
Update: https://github.com/spgennard/vscode_cobol/releases/tag/6.9.2

**Comment by GitMensch** [comment]
6.9.2 _feels_ faster... but should delete and create metadata work with this already?

~~~
Metadata cache cleared

Preparing data for external scanner
Scan Data:
 Directories found   : 12
 Directory Depth     : 1
 Files found         : 12438
 Files ignored       : 6311

[checked: no process spawned]

Metadata Dump
 cache_metadata : storagepath

 cache folder             : c:\Users\me\AppData\Roaming\VSCodium\User\workspaceStorage\f00b06fce209b941ff2b9a6714a46820\bitlang.cobol
 Last modified            : 1603174533564.586
 Dirty flag               : false

Global symbols            : (made lowercase)

Paragraphs/Sections in file : none (parse_copybooks_for_references set)
~~~~

It seems to work fine on linux-x64,

**Comment by spgennard** [comment]
I have been working on Linux, so I am glad it works on Linux.

I have not tried it out on Windows but I've just read of an issue with the function that I am using and have made a change, so it would be worth trying it out.

https://github.com/spgennard/vscode_cobol/releases/tag/6.9.3

**Comment by GitMensch** [comment]
Rechecked 6.9.3 (this time only on windows): still no process spawned, no message anywhere (neither in COBOL nor in Logs) no metadata. Note: the environment with GNU/Linux tested yesterday is _exactly_ identical.

**Comment by spgennard** [comment]
Looks like I have come across a bug in pkg, tonight I will look at implementing one of the suggested workarounds.

 https://github.com/vercel/pkg/issues/737

**Comment by GitMensch** [comment]
Interesting. Maybe "don't create binaries` (`--no-bytecode --public --public-packages`) would work, too (no idea if the result could be started as separate process then, but it would very likely allow the external call to work on all systems vscode supports).

**Comment by spgennard** [comment]
That is exactly what I intend to look into.

**Comment by spgennard** [comment]
Updated: https://github.com/spgennard/vscode_cobol/releases/tag/6.9.6

Embedding the js in the exe and not compiling on Windows... aka:

    pkg -t "win-x64" --no-bytecode --public --public-packages '*' -o cobscanner-win.exe cobscanner.js

**Comment by GitMensch** [comment]
> Embedding the js in the exe and not compiling on Windows...

I'm confused now: is the .js in the exe (=compiled) or not? Note: there's still an included extension\bin\cobscanner-x64-win-6.9.6.exe, but I _guess_ this _may_ be correct?
Would something similar be reasonable for MacOS?

Rechecked on Windows with 6.9.10:
Processing files in Workspace works in general, the executable mentioned above (which describe itself as "Node.js: Server-side JavaScript") is spawned and processes all files.
Question: Would it be possible to start it as multiple process [the linux environment finishes in 30seconds with 100% cpu load [one of the processors], the Windows environment does more or less idle]?

Side notes: after using "clear metadata" I was able to start "process workspace for metadata" multiple times, leading to multiple cobscanner instances running at the same time (processing the same files multiple times, ending with "Scan completed (Exit-Status 1)" in the output; a single scan ends just with "Scan completed").

One thing seems strange though: on start (with metadata-process-on-load set) the complete workspace is _always_ rechecked [and I have no clue why the windows environment outputs "Updating: ..." on the way for all files and the linux environment just gives the summary). I _think_ the version from the marketplace found at startup that there is nothing to update and finished quickly.

**Comment by spgennard** [comment]
The pkg by default uses the jit to generate the code ahead of time, so it does not require the source to be include in the binary.

Using the options above, turns off this feature and includes the .js files in the binary, thus avoiding the problem.

Meanwhile, I have taken a different approach and decided to use the nodejs fork feature rather than using pkg, which might not as performant but it at least it works on more platforms.

Using multiple exe is a non-starter because all would be competing to update the global files, plus it could well be seen as a denial of service if the workspace is unexpectedly large.

My long term aim to introduce a "watch" mode that could be turned on and it would allow the cache to be "eventually" consistent but with a delay.

The latest with other changes can be picked up from:

https://github.com/spgennard/vscode_cobol/releases/tag/6.9.11

**Comment by GitMensch** [comment]
I see. That sounds reasonable. Do you see a reason to not upload 6.9.11 to open-vsx yet?

**Comment by spgennard** [comment]
Yes, still not finished ..

Inter-process locking required to prevent corruption and general testing still required to name two things to do

**Comment by GitMensch** [comment]
Thank you for the information. I'll go on with the check. Just updated to that version, did the suggested restart to enable it and (as I still found no option to always show the output pane, if you know how to do please share) used "process  files in workspace for metadata". Result seen after opening the output pane:

~~~
Starting to process metadata from workspace folders (startup)
 - Parsing x:\project1\src\GENERAL.pco                      (32590.00ms)

Starting to process metadata from workspace folders (on demand)
Scan completed (Exit Code=1)
Scan completed (Exit Code=1)
~~~

(the file mentioned is the one that was opened)

Then run the metadata processing again and as it did not worked tried with clean and starting again:

~~~
Starting to process metadata from workspace folders (on demand)
Scan completed (Exit Code=1)
Metadata cache cleared

Starting to process metadata from workspace folders (on demand)
Scan completed (Exit Code=1)
~~~

So it looks like it always exits with 1 and does no scan. Clean again, opened a file not under control of this extension, restarted:

~~~
VSCode version : 1.50.0
 Platform          : win32
 Architecture      : x64
Extension Information:
 Extension path    : c:\Users\SUSER\.vscode-oss\extensions\bitlang.cobol-6.9.11
 Version           : 6.9.11
 Caching
  Cache Strategy               : storagepath
  Cache directory              : c:\Users\SUSER\AppData\Roaming\VSCodium\User\workspaceStorage\f00b06fce209b941ff2b9a6714a46820\bitlang.cobol
 UNC paths disabled            : false
 Parse copybook for references : true
  Workspace Folders:
  [...]
  Combined Workspace and CopyBook Folders to search:
  [...]
  Invalid CopyBook directories (35)
  [...]

Starting to process metadata from workspace folders (startup)
Scan completed (Exit Code=1)
~~~

So - broken?

**Comment by spgennard** [comment]
The utility has some external module requirements which will cause it to fail, if not installed globally but this will be sorted out tonight

**Comment by GitMensch** [comment]
Just an update - rechecked 6.9.15 on both GNU/Linux and Windows I always get "Source scanner already active, no action taken"  (this may be related to the process on start setting, but there's no output of it - instead it starts with "scanner already active").

Note: I do like the notification which shows up "Unable to clear metadata while caching is already in progress".

**Comment by spgennard** [comment]
You may have had a crash previously, remove the cob scanner.json file in your cache directory

**Comment by GitMensch** [comment]
Thanks for the note, yes, this did work. It may be reasonable to delete this in the extension when "clean metadata" is used.
One thing I've recognized: there's no output during the scan, so there seems to be "nothing done" after the "Files found: xyz" entry (currently needs 60-85 seconds for the complete workspace).

If the notification API allows showing and removing notifications it may be good to show one "... in progress" and maybe update it each N seconds with a counter "processing 123/456 files for metadata...".

**Comment by spgennard** [comment]
Nearly finished the changes, it's worth trying out the latest tag/release to github build.

NOTE: I also spotted another issue with the "cache" in storagepath.   

Without thinking about it turns out that the storagepath is completely global to all workspaces/folders, which means that the potential for inter-process issues with multiple vscode working on different areas are high.     I hit it several times when I was using it, the issues are not obvious and rebuilding the cache resolves the issue but it is not a good place to be.

I think the cache/storagepath is a broken implementation and I am now pondering what to do with it.  Removing/deprecating it is one option.. enforcing the user to provide a "workspace" id to act as a sub-folder within the storagepath is another...  

Time to sleep on it.

**Comment by GitMensch** [comment]
> I think the cache/storagepath is a broken implementation and I am now pondering what to do with it. Removing/deprecating it is one option.. enforcing the user to provide a "workspace" id to act as a sub-folder within the storagepath is another...

@spgennard please don't remove the cache/storagepath option as the cache/workspace option is also "broken".

cache/workspace is broken for multiuser access to the same workspace (concerning write/permission/locking), the current work-around is to switch to cache/storagepath. One _could_ also (optionally?) use-sub-folders here with the username but I'd document to just use the cache/storagepath setting in this use-case [and not change anything for cache/workspace].

cache/storagepath as-is is broken because for multiple workspaces the same user should have multiple caches (some users only have a single workspace so they aren't affected by this current problem).
So yes: a subfolder would be the most reasonable approach. I suggest to allow the user to specify a workspace id, if it isn't set fall-back to the workspace name (so a user that has a COBOL.workspace in three different folders would need to specify a workspace-id at least two times - or, if he's a single user switch to cache/workspace instead, but a user who has PROJECT1.workspace, PROJECT2.workspace PROJECT3.workspace wouldn't have to setup anything).

**Comment by GitMensch** [comment]
Looks like 86915002c8a8bcecd51d047df0a8681828d31307 solves both issues with the storagepath outlined above.

**Comment by spgennard** [comment]
I am going to live my changes for a couple of days and if I don't hear anything negative, I will push the delivery out to the world.

**Comment by GitMensch** [comment]
I've just installed the 6.9.17 extension. It works quite well in general and parses file opened new  in general, but stops the scanner when using "process files in workspace for metadata".
I've then switched to the workspace settings, have seen a storagearea_id, adjusted this to a TEXT, then recognized the new folder under bitlang.cobol/$USER/TEXT as expected, tried to produce the metadata again and got:

~~~
Starting to process metadata from workspace folders (on demand)
External scan completed (Exit Code=1)
~~~

Then reloaded the window, forgot that I had auto-scanning on startup sp triggered it manually and checked for the result:

~~~
Source scanner already active, no action taken
 - Parsing x:\OpenedFile.lib                      (952.00ms)
Source scanner already active, no action taken
~~~

--> There's no entry for auto parsing on startup, so something seems to be missing now.

If I open another file I see

~~~
 - Parsing x:\OtherHuge.cob                      (3369.00ms)
~~~

but still manually triggering did not worked.
Last test for today: close all COBOL editors, reload the window.

Result:

**Comment by spgennard** [comment]
update publish to git @ https://github.com/spgennard/vscode_cobol/releases/tag/6.9.19

**Comment by GitMensch** [comment]
Rechecked with 6.9.19:

~~~
Source scanner lock file is present on startup (startup)
 - lock file released
~~~

And "Processing metadata" with a percentage in the statusbar while it runs, sub-folders per user and workspace in the storagepath - I love it!

**Comment by GitMensch** [comment]
OK, found one culprit which I don't know if it can be solved. It _looks_ like while the outline is calculated the build process is blocked.
Can you move the outline to a forked part to not let the extension be unresponsive to vscode while preparing it?

**Comment by spgennard** [comment]
The outline view parsing uses the in memory vscode buffers which, which may not be saved to disk, so cannot be pushed in to another process.

The parsing is often not the slow part, it usually the creation of the outline itself.

The "coboleditor.outlne" allows you to tweak what is shown (or disable it).

**Comment by GitMensch** [comment]
The outline is too important for me to change anything here.
I don't know but possibly you see something in the updated [bitlang.cobol-unresponsive.cpuprofile](https://github.com/spgennard/vscode_cobol/files/5500597/bitlang.cobol-unresponsive.cpuprofile.txt) that can be tweaked.

This appened some times now, as I commonly switch between files and then directly run the build task. It _may_ be possible to keep the in-memory-buffer for the outline "somewhere" as long as the tab is open to not need to recalculate on file switching (which could be a common thing to do).

**Comment by spgennard** [comment]
The outline view is updated when vscode asks for it, until this happens it works on a cached version.

**Comment by spgennard** [comment]
Have seen the files.watcher property, it may help your startup times

**Comment by GitMensch** [comment]
With 6.10.0 deployed I suggest to close this issue. Do you agree?
