### ISSUE TITLE
How to disable a single entry (ideally only for a specific source) from being shown in the problem pane?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#216]
I _guess_ that is a question of the linter itself (so VC for MF VC, GnuCOBOL for GC, ...) via `-C CHANGE-MESSAGE` or `-Wno-,,,` or - for the included linter (which is about code rules and unused paragraphs/sections) via a linter comment in the source [does this option exist currently?] - but I'm not sure.

It is at least confusing that vscode has an option "Add COBOL lint ignore comment" when it doesn't work,
See https://stackoverflow.com/questions/61821822/vscode-lint-ignore-for-task-output-languages-that-are-not-in-built-into-vscod for a bounty-question on that, which includes a screenshot.

If this extension would have a lint comment option, could we add options to ignore messages with a code (like COBCH1216) via comments in the source [for the complete file / a specific line)?
If not: is it possible to disable the context menu entry that ask for "add ignore comment"?

[ignoring the message on the compiler part or via adjusting the problemMatcher would be possible - but that's not the question here]

**Comment by spgennard** [comment]
> I guess that is a question of the linter itself (so VC for MF VC, GnuCOBOL for GC, ...) via -C CHANGE-MESSAGE or -Wno-,,, or - for the included linter (which is about code rules and unused paragraphs/sections) via a linter comment in the source [does this option exist currently?] - but I'm not sure.

To remove a compiler error message, you will as you say have to use a compiler directive, as you say for Micro Focus COBOL using CHANGE-MESSAGE or if you are using a very old compiler HIDE-MESSAGE.

For this extension,  you can turn the linter off via settings, global, workspace and perhaps folder (not checked) or disable each item by itself, you turn off the "unused paragraph linter" itself, you change the severity of the message (default is information_, so it does not appear in the "problems panel" as well but still appear near code that you are editing.

```json
 "coboleditor.linter_mark_as_information": false

```json
"coboleditor.linter_unused_paragraphs_or_sections": false
```

or
```"coboleditor.linter": false
```
Or include the comment marked in the code.

> It is at least confusing that vscode has an option "Add COBOL lint ignore comment" when it doesn't work,
> See https://stackoverflow.com/questions/61821822/vscode-lint-ignore-for-task-output-languages-that-are-not-in-built-into-vscod for a bounty-question on that, which includes a screenshot.

The issue the person observed was related to the linter being triggered for non-linter issues and this was resolved a months ago.

Have you tried to get the issue yourself?

**Comment by GitMensch** [comment]
> Or include the comment marked in the code.

Can you add the options for this in the README please?

And yes: the issue here is solved now, the linter doesn't get triggered any more for error messages parsed from the compiler (so I _guess_ "add linter comment" would work in those cases, now).

**Comment by spgennard** [comment]
and also moving the message away from the problem panel with option below, is very useful if you have a very dirty source code.

```json
 "coboleditor.linter_mark_as_information": false
```

**Comment by spgennard** [comment]
If you turn the message to "information", it will appear in "error lens", for example, if you install;
  https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

You can see the message is placed at the side of the linter warning...

![image](https://user-images.githubusercontent.com/5991192/94526473-797dbf00-022d-11eb-95f9-e34997144a0a.png)

**Comment by GitMensch** [comment]
Thanks for the hint, that's quite useful - and the source for https://github.com/usernamehw/vscode-error-lens/issues/61. :-)
