### ISSUE TITLE
Setting coboleditor.parse_copybooks_for_references needed to get auto-completion of copybook vars?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#219]
Tested with the first the last 6.7 version:

* coboleditor.parse_copybooks_for_references = false
* complete workspace parsed for metadata (on startup)
* starting to type a name of a variable brings up the matching variables fast
* starting to type a name of a variable defined in a copybook doesn't come up

Second test

* coboleditor.parse_copybooks_for_references = true
* starting to type a name of a variable defined in a copybook then the matching variable is shown (but quite laggy)
* coboleditor.parse_copybooks_for_references = false
* reload window
* starting to type a name of a variable defined in a copybook then the matching variable is not shown

Dumped metadata shows that the copybook is indexed and contains the requested variables

I _think_ once the copybook is parsed and referenced in the source then all variable names should be available in auto-completion and _always_ be read from the metadata (not from the file).
Note: the metadata for the copybook would also need to contain a reference to nested copybooks (haven't checked if this is the case yet).

**Comment by spgennard** [comment]
The scanning of the programs/programs are done as independent files, irrespective of the parse copybooks settings.

This way, it can be used with the parse copybook settings when editing the file (so supplement the results).

The cached definition provider looks for symbols in a file and any copybook it references therefore parsing the copybook inline during the "file" cache will result in over scanning for no reason.

More importantly, the symbols, line numbers in the file cache are relative to the file, it has no ability to "nest" files.. ie: the store if symbol, line.. not symbol, line, file hence it was a bug that needed to be fixed.

```json
export class COBOLSymbol {
    public symbol: string | undefined;
    public lnum: number | undefined;

    public constructor(symbol?: string, lineNumber?: number) {
        this.symbol = symbol;
        this.lnum = lineNumber;
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    static fromJSON(d: any): COBOLSymbol {
        return Object.assign(new COBOLSymbol(), d);
    }
}`

**Comment by GitMensch** [comment]
> More importantly, the symbols, line numbers in the file cache are relative to the file, it has no ability to "nest" files.. ie: the store if symbol, line.. not symbol, line, file hence it was a bug that needed to be fixed.

Should this be solved now? With version 6.8.5 I still have the same issue with the nested copybook setup (sample given in #218 with additional setting of `coboleditor.copybookdirs`.

**Comment by spgennard** [comment]
Using parse_copybook_for_references allows you to see fields defined in a copybook.

![image](https://user-images.githubusercontent.com/5991192/95457409-c3bb1a80-0968-11eb-8924-d7173f8852da.png)

**Comment by GitMensch** [comment]
Explained with the new 610.0 README:

> If you want the extension to understand the contents of your copybook before you access them, then turn on the *coboleditor.parse_copybooks_for_references* setting.

So the answer to the initial question is: Yes, the setting `coboleditor.parse_copybooks_for_references` is needed to get auto-completion of copybook vars, even with full metadata-cache available.
