### ISSUE TITLE
Uppercase snippets

### ISSUE THREAD

**Issue by Fulkerson** [spgennard/vscode_cobol#22]
Hello!

The examples on page use UPPERCASE code. But when I pick a autocompleted (e.g. program-id) snippet they are all lowercase. 

Is this an option possible to change?

**Comment by spgennard** [comment]
The only solution I can find at the moment is to duplicate the snippets but with an uppercase identifier and content.

This means if you are typing in uppercase, the uppercase named snippet should be shown first.

I've done this with 3.2.25, so can you please take a look.

**Comment by Fulkerson** [comment]
It works. Thank you!
