### ISSUE TITLE
FR: add localization support to this extension

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#220]
it looks like the standard way for vscode is json string replacement via https://github.com/microsoft/vscode-nls.

See https://github.com/microsoft/vscode-extension-samples/tree/master/i18n-sample how to integrate it.
I won't recommend to use Transifex, instead just add the necessary infrastructure and let people PR to the new i18n directory providing the translations.

**Comment by GitMensch** [comment]
Sample implementation as suggested in another extension: https://github.com/JohnstonCode/svn-scm/pull/1058/files
Note: The strings don't need to be manually extracted, https://github.com/Microsoft/vscode-nls-dev can do this.

**Comment by spgennard** [comment]
I have tried this in the past but found two problems:
 Package.json is expanded on the fly, so the marketplace just shows the unexpanded fields
Next, I could not get it working with webpack

The first problem is problematic, as someone viewing the extension information before install needs to see the information... Irrespective of locale.

**Comment by GitMensch** [comment]
> Package.json is expanded on the fly, so the marketplace just shows the unexpanded fields.

Which fields should be translated in the marketplace? The command titles and other descriptions aren't so if in question I'd say just leave whatever the marketplace shows directly in English.

I think_ there's a solution for the second one, most of the extensions that are under MS umbrella use that and I _guess_ webpack is used in one of these, too.

**Comment by spgennard** [comment]
> Which fields should be translated in the marketplace? The command titles and other descriptions aren't so if in question I'd say just leave whatever the marketplace shows directly in English.

I would aim to translate as much as possible and the more that is done, the worse experience occurs in the marketplace, for example, look at this extension:

![image](https://user-images.githubusercontent.com/5991192/96699914-b9484a00-1386-11eb-9b22-bc6c648e6086.png)

**Comment by GitMensch** [comment]
Yes, that's a very bad user experience. I'll check some MS extensions.

**Comment by spgennard** [comment]
I'll save you some time..

![image](https://user-images.githubusercontent.com/5991192/96785854-50dd8500-13e7-11eb-82af-a5f1ca5182d0.png)

and

![image](https://user-images.githubusercontent.com/5991192/96785984-7e2a3300-13e7-11eb-80db-09dc266573be.png)

**Comment by GitMensch** [comment]
"Known issue", tracked at https://github.com/microsoft/vscode/issues/54111... and very likely the reason the package description itself is not yet translated in the samples above.

**Comment by spgennard** [comment]
will naturally revisit this when Microsoft fix the issue above
