### ISSUE TITLE
Allow tests to be run via CLI

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#223]
> > > Can you automate the tests so that they are automatically done for each PR vi CI?
> > 
> > 
> > The tests are GUI, so I would need a dedicated VM, so sorry not at the moment.
> 
> I see. I've thought that these would be plain `npm`, it may be useful to split the tests to be able to automate every non-gui part.

All of the tests have a dependency on the vscode package & the initialization of the extension.

These tests pickup the problem matchers from the package.json via the extension, so vscode has to load & the extension setup, then it can find the matchers & the regex's to test.

_Originally posted by @spgennard in https://github.com/spgennard/vscode_cobol/pull/221#issuecomment-708966777_

This "reminder" issue is about checking if testing via CLI is possible [research needed] and if it is do the split [help wanted]. I'm totally fine with an assignment of this issue to me as this is something I'm interested in in any case (just won't find the time to do this now).

**Comment by spgennard** [comment]
Almost every file in the extension uses the "vscode" package, therefore this would require a complete re-write and we get little or no advantage.

Everything, I build/publish all the tests are run, so if a test fails it will be known.

Anyone contributing should know to run the tests before submitting a PR if it is a code change.

**Comment by GitMensch** [comment]
> Anyone contributing should know to run the tests before submitting a PR if it is a code change.

I've really looked for that, but where in the README or Wiki may this information (and possibly more dev notes like the structure of this project) be found?

**Comment by spgennard** [comment]
Developers should not have to be told to run tests, it should be in the normal best practices of developing software.
