### ISSUE TITLE
FR: provide outline for "COBOL_LISTFILE"

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#224]
While it isn't a high priority for me it _may_ be "relative easy" to do and the current "the active editor cannot provide ...." stands out from the nice outline we have for the "COBOL" language identifier.

**Comment by spgennard** [comment]
Micro Focus listing files use comments for extra info but proCOBOL doesn't (as you are aware)

Picking up the end of the program in a listing file is problematic.  

Tip: If the code uses 'end program' it works better.
