### ISSUE TITLE
Building extension on win32 does not work anymore (cobscanner)

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#230]
the command `tsc -b && ./bld_cobscanner.sh` does not work because there's no shell interpreter available (ps/cm should work) and because `./` won't work from the cmd which is the default interpreter

**Comment by spgennard** [comment]
Have you setup your npm shell as git bash, it works for me.

    npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"

**Comment by spgennard** [comment]
config issue, see above

**Comment by GitMensch** [comment]
> config issue, see above

maybe "developer documentation issue"?

**Comment by GitMensch** [comment]
> npm ERR! code ELIFECYCLE
npm ERR! syscall spawn C:\Program Files\git\bin\bash.exe
npm ERR! file C:\Program Files\git\bin\bash.exe
npm ERR! path C:\Program Files\git\bin\bash.exe
npm ERR! errno ENOENT

;-)

Using an existing shell helped here (but likely some other node stuff will someday be broken and I'll possibly have forgotten that I've tweaked the shell that way)... So win: the extension does start now with "Launch Extension", leaving #233, but I'll try the approach mentioned there.
