### ISSUE TITLE
cobscanner npm install with warnings

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#232]
Seen when running the tests:

~~~
cobscanner> npm install
npm WARN cobscanner@6.9.16 No description
npm WARN cobscanner@6.9.16 No repository field.
~~~

**Comment by spgennard** [comment]
This is okay, the package.json is never used, other than installing it's deps.   If it was published it would be an issue.

**Comment by GitMensch** [comment]
Hm, looks like it would be easy to fix, can I PR the cobscanner/package.json to fix that?

**Comment by spgennard** [comment]
Don't bother it will be deleted soon.

**Comment by spgennard** [comment]
removed
