### ISSUE TITLE
can't run the tests

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#233]
This is possibly a win32 issue:

~~~
Error: Error: Cannot find module 'c:\dev\vscode_cobol.git\out\test'
Require stack:
- c:\Program Files\VSCodium\resources\app\out\vs\loader.js
- c:\Program Files\VSCodium\resources\app\out\bootstrap-amd.js
- c:\Program Files\VSCodium\resources\app\out\bootstrap-fork.js
	at p._doHandleExtensionTests (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:930:522)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
~~~

"c:\dev\vscode_cobol.git\out\test" is an existing folder in the file system with a content of runtTest.js[.map] and a suite folder which looks also fine.

**Comment by spgennard** [comment]
Works for me, when the shell is set to bash but it is much easier just to use "node out\test\runTest.js" as you get the output in the current console rather than the spawned "git-bash" console which shows the running tests and disappears.

**Comment by GitMensch** [comment]
Running the tests from the integrated terminal resultied in downloading of the vscode-1.50.1-zip and afterwards a

> warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

A second run works directly out of the box. Also working: running the tests via Terminal->Run Tasks->npm->run tests. (the debug configuration still does not work).
I _guess_ there may be a developer docs that says how to run the tests and listing those two options there somedayTM.

**Comment by spgennard** [comment]
You cannot have any vscode instances running, which means you can not run them from vscode itself.

Microsoft might change this but I suspect not, we just have to live with it.
