### ISSUE TITLE
MF matcher problem with COBCH038 name XYZ undeclared, line 878 (first usage)

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#235]
Directly on the terminal the output is:

~~~
**    COBCH0301S Unrecognized verb  : /some/CODE.cob(1619,8,8)
**    COBCH0348S Procedure name U040-ERR undeclared, line 25901 (first usage)  : /some/CODE.cob(398,33,23)
**    COBCH0348S Procedure name C123-ERR undeclared, line 27136 (first usage)  : /some/CODE.cob(1633,30,20)
~~~

I guess the extension stumbles over the `()`.

*Note: I've previously had the problem that the terminal additionally added a line break on windows. To solve this: open cmd.exe, use "default values" in its title's context manue and increase the default of 80... Now every diagnostic but this single one is correctly parsed*

**Comment by GitMensch** [comment]
I try to produce this message with MF SE and combe back with a sample.

**Comment by spgennard** [comment]
I used the included sample output already and make appropriate changes.,

Micro Focus Server Express might not be the same format, so take care.

**Comment by GitMensch** [comment]
Works fine with both MF-VS and MF-SE (tested with ERRFORMAT'2' on both).
For reference: the correctly parsed message from MF-SE is (just in case you want to add it to the tests):

~~~
**    COBCH0348S Procedure name U040-ERR undeclared, line 34546 (first usage)  : /some/CODE.cob(583,20)
~~~

Thanks again!
