### ISSUE TITLE
README: use a single way to reference a setting

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#238]
I volunteer to adjust the README here but wanted to ask for the format to be used.

We currently have:

* `setting`
* *setting*
* "setting"

Note: additional to the ones above I've found these additional way of referencing settings in other extension's README:

* `"setting"`
* "`setting`"
* **setting**
* ***setting***
* **`setting`**
* *`setting`*
* ***`setting`***

I don't mind which one is used, as long as only one format is used everywhere in the README - name one and I'll PR an updated README (after merging/rejecting #237).

**Comment by GitMensch** [comment]
I _guess_ 3d61a21c5efeba9b2a26b69d36c48d7a336252b1 relates to this. So ```setting```, always prefixed with `coboleditor.`, is the preferred way for this repo, correct?

**Comment by spgennard** [comment]
the readme is now okay, so closing it
