### ISSUE TITLE
a

### ISSUE THREAD

**Issue by NicholasVon** [spgennard/vscode_cobol#239]
Hi
My code file at /src 
and copybook file at /src/ABC
after install this extension
I cannot find copybook defination through F12

can you help ?

a

**Comment by spgennard** [comment]
From the README:

```markdown
# Workspace Setup

Visual Studio Code workspaces are not "projects" but do allow you keep your source in one place.

Things to consider:

   -  If you have copybooks, you should change the *coboleditor.copybookdirs* setting to setup where the extension can find your copybooks.
    - If use the copy verb with an extension, you may also need to adjust the *coboleditor.copybookexts* setting
    - If you want the extension to understand the contents of your copybook before you access them, then turn on the *coboleditor.parse_copybooks_for_references* setting.
``

**Comment by NicholasVon** [comment]
I have already set *coboleditor.copybookdirs*  to D:\src\ABC  , but when I press F12 to find defination in cob ,it still returns "not defination found for copybook

**Comment by spgennard** [comment]
Not sure why you using physical directories, when you are using a workspace, ABC is enough.. for example:

![simplescreenrecorder-2020-11-07_11 58 16](https://user-images.githubusercontent.com/5991192/98440596-883f7780-20f1-11eb-9983-08f244bdeda0.gif)

**Comment by GitMensch** [comment]
Other than the the absolute path issue (if you note a workspace instead of a "just open a file" option you can also use forward slashes in the settings - and limit it to that workspace, using a different setting for another), the README now also says:

> If you want the extension to understand the contents of your copybook before you access them, then turn on the *coboleditor.parse_copybooks_for_references* setting.

@NicholasVon can you please "edit" your opened issue to not name it "a" but something useful?

**Comment by NicholasVon** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spgennard/vscode_cobol"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 晚上8:06
收件人:&nbsp;"spgennard/vscode_cobol"<vscode_cobol@noreply.github.com&gt;;
抄送:&nbsp;"冯阳"<361976740@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [spgennard/vscode_cobol] a (#239)





 
Not sure why you using physical directories, when you are using a workspace, ABC is enough.. for example:

**Comment by NicholasVon** [comment]
1.  I found the reason why F12 cannot go to defination.  My cobol version when include copybook it writes "COPY CPYINVM IN LIBRYINV", if I write only "COPY CPYINVM", the go to defination is valid.      
2. How can I go to SUB-PROGRAM in main programes. just like 
XXXX1.COB:
A000-MAIN-LOGIC.
    CALL "XXXX2" USING WA-VAR.
A999-EXIT.
   GOBACK.
How can I  go to "XXXX2.COB" quickly ?

**Comment by GitMensch** [comment]
> I found the reason why F12 cannot go to defination. My cobol version when include copybook it writes "COPY CPYINVM IN LIBRYINV", if I write only "COPY CPYINVM", the go to defination is valid.

@spgennard I actually was prompted with this difference some days ago when making GnuCOBOL "behave correct" - and some applications were not able to be compiled any more. The tested behavior with MF is: search for CPYINVM in a LIBRYINV subdirectory relative to the file, if it doesn't exist check in the specified include directories for a CPYINVM in a LIBRYINV, if it doesn't exist: ignore the library-name and search in the copybook again. (which is now the GnuCOBOL behavior, but GnuCOBOL will issue a warning if the library-name has to be ignored).
You may want to apply a similar lookup in this extension to match what MF does.

@NicholasVon 2 is a completely different issue, please reopen a new one with a speaking title for each as this helps to both answer and for others to find the answer faster. My take on this is: if you use metadata caching (see the README) and at least one-time compute the metadata, then it should work.

**Comment by GitMensch** [comment]
@spgennard Should I open a new issue with the FR about "if no copbook with the library name is found, then search without it" tp match the MF expectation?

**Comment by spgennard** [comment]
The way it works matches both Micro Focus default (see below), GnuCOBOL the mainframe COBOL as well, so I am happy with the behavior.

If they want to open the file under cursor, the use of other extensions such as:
   https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-openfile

fulfills this need.

Micro Focus:
```shell
     8 copy "subcopybook" in missing_directory.
*   8-S****************************************                              **
**    Unknown copybook MISSING_DIRECTORY/subcopybook specified
cob64: error(s) in compilation: mainprogramx.cbl
```

GnuCOBOL:
```shell
mainprogramx.cbl:8: error: missing_directory/subcopybook: No such file or directory
```

**Comment by GitMensch** [comment]
Actually if you use GC 3.1 (latest) or MF VS with its default options and have subcopybook next to mainprogramx it should still work.
GC raises a warning which you can disable, MF does not even raised an informational when I've tested this some days ago.
But I do agree that this "dirty library-name is ignored" behavior may be work around by using https://open-vsx.org/extension/Fr43nk/seito-openfile ;-)

**Comment by spgennard** [comment]
No arguments to the latest Micro Focus product, sorry you must have some other directives or environment variables set or are using if via the IDEs.

If it did not error or magically defaulted to using the same directory as the compiled source, I would raise it as an issue because ignoring the library is just plain wrong.   The reason the developer uses them is to prevent randomly picking up another copybook of the same name.. ie: ensure it is found in xyz.   Plus it works very well to mainframe PDS/PDSE datasets etc..

```shell
~/src/vscode_cobol_issues/239$ cobc mainprogramx.cbl 
mainprogramx.cbl:8: error: missing_directory/subcopybook: No such file or directory
~/src/vscode_cobol_issues/239$ ls -l subcopybook*
-rw-rw-r-- 1 spg spg 3 Nov  9 20:35 subcopybook.cpy
```

and 

```shell
:~/src/vscode_cobol_issues/239$ cobc mainprogramx.cbl 
mainprogramx.cbl:8: error: missing_directory/subcopybook: No such file or directory
~/src/vscode_cobol_issues/239$ cobc -V
cobc (GnuCOBOL) 3.1-dev.0
...
```
