### ISSUE TITLE
CHANGELOG: please include 6.10

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#240]
The 6.10 changelog was moved to a separate file, now we have 6.10.0 published in the marketplace (big yay btw) but the real important changes are not visible in the changelog shown in the extension.

So I suggest for a  new 6.10.1, and I still volunteer for #238 if you want to include this.

**Comment by spgennard** [comment]
A summary change log is included in 6.10.0, as well as the full changelog, so I think this issue as mute.   Especially as version is greater than 6.10.0

**Comment by GitMensch** [comment]
Hm, no?

All clients (market place, registry and most important the vscode client itself) render from https://github.com/spgennard/vscode_cobol/blob/master/CHANGELOG.md which is more or less user-readable but does not contain 6.10

**Comment by spgennard** [comment]
Nothing was fixed in 6.10... so nothing will be present.

**Comment by GitMensch** [comment]
Oh, I've thought 6.10 was the big change to have the way the metadata parser was invoked and features both the changed path for storing it and the nice progress on the lower left, and closes #215 and therefore thought this would be relevant to see in the user-visible changelog.

**Comment by spgennard** [comment]
The changes were staged in private builds before 6.10

Hence the human readable changelog
