### ISSUE TITLE
COPYBOOK go to defination and SUB-PROGRAM go to defination issues , help !

### ISSUE THREAD

**Issue by NicholasVon** [spgennard/vscode_cobol#241]
1. I found the reason why F12 cannot go to defination. My cobol version when include copybook it writes "COPY CPYINVM IN LIBRYINV", if I write only "COPY CPYINVM", the go to defination is valid.
2. How can I go to SUB-PROGRAM in main programes. just like
XXXX1.COB:
A000-MAIN-LOGIC.
CALL "XXXX2" USING WA-VAR.
A999-EXIT.
GOBACK.
How can I go to "XXXX2.COB" quickly ?

**Comment by spgennard** [comment]
Is your copybook in a subdir called LIBRYINV?

**Comment by spgennard** [comment]
My recommendation is to install the "Open file" extension and press "ALT-P" while selecting the CPYINVM the COPY statement.

Search for extension:   fr43nk.seito-openfile
