### ISSUE TITLE
New version with Open-VSX 6.10.19

### ISSUE THREAD

**Issue by jaamaay** [spgennard/vscode_cobol#245]
Hi,
we use bitlang.cobol in VSCodium for our MicroFocus and GnuCOBOL environment. We need a fix from this plug-in via Open-VSX.
Is it possible to provide the current version of Open-VSX?
Thanks

**Comment by spgennard** [comment]
Sorry, Open-VSX has been removed until I can understand the impact of having to accept the new "Eclipse Publisher Agreement".

**Comment by GitMensch** [comment]
I see, that's reasonable and should not be taken too fast. The trigger would be necessary in December, but doing this now is also not bad.

For reference:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management lists that the publishing needs: 

- [x] a GitHub account
- [ ] an [Eclipse Account](https://accounts.eclipse.org/user/register?destination=user), which also means to accept its [Terms of use](https://www.eclipse.org/legal/termsofuse.php)
- [ ] putting a license in package.json (obviously the initial "a free license" was replaced by "any license") - [package.json had previously "MIT"](https://github.com/kabel/vscode_cobol/blame/f0919d29daf1cd2f7ccfe98d91c4d0c2dd663b36/package.json#L100), which matches [this repos LICENSE](https://github.com/spgennard/vscode_cobol/blob/main/LICENSE) so this should be no issue and is reasonable in any case, #246 does this for this repo, https://github.com/spgennard/vscode_cobol4gnucobol/pull/1 for the other one
- [ ] Confirm consent to the [Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)

Compared to the previous "just get a token and upload" this is definitely more (I'm still not sure how I think about this), but compared to the needs for publishing to the MS market place - foremost the [Microsoft Services Agreement](https://www.microsoft.com/en-us/servicesagreement) and [Privacy Statement](https://privacy.microsoft.com/privacystatement) and then the [Visual Studio Marketplace Publisher Agreement](https://cdn.vsassets.io/v/M146_20190123.39/_content/Visual-Studio-Marketplace-Publisher-Agreement.pdf) this is still "less" and in any case "comparable".

The workaround until the extensions (now split into two, see reason in #244) are possibly uploaded to the [Open VSX Registry](https://open-vsx.org/?search=cobol): download the vsix from the [vscode_cobol releases](https://github.com/spgennard/vscode_cobol/releases/latest) and [vscode_cobol4gnucobol releases](https://github.com/spgennard/vscode_cobol4gnucobol/releases) and do a manual install (with the obvious side issue of loosing auto-update).

**Comment by spgennard** [comment]
Goodbye open-vsx :-(

![image](https://user-images.githubusercontent.com/5991192/101615180-bb816900-3a05-11eb-9853-5714a4a89b56.png)

**Comment by GitMensch** [comment]
Welcome Open-VSX

![grafik](https://user-images.githubusercontent.com/6699539/101615987-17042480-3a0f-11eb-81e9-0b4117d68fe4.png)

**Comment by GitMensch** [comment]
I've experienced some downtime on open-vsx yesterday, too.
As you've seen them, too: can I hope for a republishing of the bitlang extensions there soon?

**Comment by GitMensch** [comment]
As the bot is asking for activity: @spgennard Do you found the time already to check the implications that the new Open VSX manager Eclipse has and thought about republishing a new version there?

**Comment by GitMensch** [comment]
Mora activity with a friendly ping @spgennard.

**Comment by GitMensch** [comment]
Another friendly ping @spgennard concerning this.

**Comment by spgennard** [comment]
@GitMensch I am still here and I am still waiting, no change in status

**Comment by GitMensch** [comment]
Thanks for answering the ping. So...

* Should we keep this issue open (possibly renamed)?
* We do have the vsix, which is published under MIT and made available as partial binary via the ms market place [and its source, under the same license, mirrored already]. Is there any reason to not have the extension available on open-vsx? [If you don't want to do it - that's reason enough to stop asking and let the open-vsx CD handle that; otherwise I'd love to know more about the reasons for not uploading].

**Comment by spgennard** [comment]
@GitMensch - My options are either:
 - wait until I get this resolved
 
More aggressive solutions:
 - change the license from MIT to block including of the extension without my permission (as suggested by other contributors)
 - move from a public source to private which will prevent delivery from source without consent (as suggested by other contributors)

Please kindly don't push me into one of these

**Comment by GitMensch** [comment]
Three months passed and MF also has their extension in the MS marketplace, which I _assume_ that the holding of possibly was related to. So... any update?

**Comment by spgennard** [comment]
Sorry no update

**Comment by GitMensch** [comment]
Just another friendly ping.

What do you think of letting either this and/or the gnucobol (and possibly cross-hair/dictionary) extension be automatically published to OpenVSX?

**Comment by spgennard** [comment]
Sorry awaiting legal review.

I would not hold to your breath.

**Comment by GitMensch** [comment]
Thanks for the answer. Does this cover all extensions or only this one?

**Comment by GitMensch** [comment]
New computer, new setup. Looked at COBOL support, did not found anything that worked well enough, so got back to this one, using a manual download and install from VSIX.
This extension is definitely very useful, and as several months passed I do wonder: What was the result of that legal review?

If you don't want to sign the Eclipse publisher agreement along the Microsoft publisher agreement (when comparing those I find the Eclipse one "better", but that's likely situation based) then that's OK; we can get the CI publishing do the uploads and if necessary the building; effectively meaning there is no legal impact on your side.

@spgennard What do you think?

**Comment by spgennard** [comment]
Sorry, my answer still stands and my need to not include it too.

**Comment by GitMensch** [comment]
Hm, the answer was "Wait until this is resolved", wasn't it? And the "resolved" is depending on legal review? If yes: can I do anything to help speeding this up?

I still don't understand the issue, but _really_ would like to.

Side question from before: Does this only apply to bitlang.cobol or also to the other COBOL extensions of yours (= would you be ok with getting the gnucobol one, crosshair and themes published "externally" to osvx)?

**Comment by spgennard** [comment]
It is resolved, I can't do it, end of discussion
