### ISSUE TITLE
something happened to the repository - older revisions lost

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#247]
Compare the mirror repo https://github.com/kabel/vscode_cobol with 1,268 commits with this one, which had the same amount two days ago and now only 11 commits.

Maybe some force-push has gone wrong?

**Comment by spgennard** [comment]
No, The branch names have been moved from master to main & gc'ed

**Comment by GitMensch** [comment]
What is "gc'ed"?

**Comment by GitMensch** [comment]
If it's possible I highly suggest to get the old commits back to the "main" branch (possibly as new "master" branch?), the old > 1200  commits also showed some maturity :-) The last tag with the old commits was [6.10.3](https://github.com/spgennard/vscode_cobol/commits/6.10.3).

**Comment by GitMensch** [comment]
Just a ping @spgennard to tell if this repo may get the old commits "back" or not (and close the issue before the bot does it).
