### ISSUE TITLE
F12 to jump to file not working

### ISSUE THREAD

**Issue by Fabulu** [spgennard/vscode_cobol#248]
**Describe the bug**

This has been a very useful extension for me and it's working nicely after having it all set up. The only problem remaining is that I want to use the functionality to press F12 to jump to a definition in my code, so if I click "styledocument.sd" in the code of a program and press F12 it's supposed to open the styledocument file, but all the editor does is say "No definitions found for "styledocument".". If I use ctrl + p and search for the file there I can find it easily because the folders are correctly defined. Our lead developer says the F12 functionality used to be there and it just vanished at some point for no reason.

Is there any way to get this functionality back? It'd be really useful, I'm very new at programming and this would be a godsend as it'd help me find my way around the code at a reasonable pace, as everything seems really difficult right now.

**To Reproduce**
1. Open a Cobol Program
2. Click on a file that you used "copy" on 
3. Press F12

**Expected behavior**
A new editor tab should open showing the file you clicked on in the code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Newest

**What user & workspace settings are being used?:**

**Additional context**

**Comment by GitMensch** [comment]
Can you please provide a minimal example that we could check? This way we know exactly what does not work and can either recommend a setting or there is something to work on.

Additional: do you know which version / date  it did work and when it started to not work any more?

**Comment by spgennard** [comment]
It seem to work for me.. using either peek or F12

[248.zip](https://github.com/spgennard/vscode_cobol/files/5562434/248.zip)

Here it is..

![issue_248](https://user-images.githubusercontent.com/5991192/99581166-4c9d8b00-29d8-11eb-958a-435e6a636779.gif)

**Comment by Fabulu** [comment]
Thanks for the replies. It must be one of our settings that went wrong. Sadly I'm new at this place so I can't tell you much about how it was in the past. I'll try and get more information tomorrow at work.

**Comment by GitMensch** [comment]
@Fabulu can you please check if it works for you with the attachment 248.zip posted above? if it does then copy the content to your local workspace and check again. If it doesn't work there you have a reason to open two vscode windows, go to the extension settings and compare both.

**Comment by Fabtabulous** [comment]
@GitMensch Thank you, I was able to test it out now and it works perfectly fine in your workspace. My assumption is that our programmers messed up some settings, I will do as you said and try to hunt for the difference in settings. Thank you so much for your support!

**Comment by GitMensch** [comment]
The only settings that are relevant, giving the workspace @spgennard has provided are:

```json
{
    "coboleditor.copybookdirs": [
        "copybooks" // replace by the name of _additional_ directories containing copybooks
    ],
    "coboleditor.copybookexts": [
        "cpy",
        "sd"   // if you have more, then add to this list
    ],
    "files.associations": {
        "*.sd": "COBOL"   // if you have more nonstandard ones, add to this list
    }
}
```

**Comment by Fabtabulous** [comment]
Thank you so much for your help, I was able to make it work.  It ended up being enough just adding the additional directories to the copybookdirs, the plugin can now find all the files even if they're not given in copybooktexts and the file associations aren't given. I'm assuming there is automated functionality that makes those unneccessary.

**Comment by GitMensch** [comment]
>  the plugin can now find all the files even if they're not given in copybooktexts and the file associations aren't given

For the first part: as long as the extension is part of the `COPY` statement - yes: no need to add it to `"coboleditor.copybookdirs"`.

For the second part: if they are not part of the `"files.associations"` the copybooks can be opened but have no COBOL editor functionality (highlighting, outline, go-to, ...), if they are not part of the [default extensions](https://github.com/spgennard/vscode_cobol/blob/6.10.20/package.json#L659).
