### ISSUE TITLE
File is too long?

### ISSUE THREAD

**Issue by alx-api** [spgennard/vscode_cobol#249]
In "OUTLINE" it shows the message "No symbols found in document 'my file name'"

Functions "Go to Definition" and "Peek definition" doesn't work.

Colorization it's ok.

Shortcuts like "Go to data division/procedure division/working-storage section" works ok.

My file has 60k lines, maybe an oversize issue?

**Comment by GitMensch** [comment]
That's a default vscode setting: [`editor.maxTokenizationLineLength`](https://github.com/microsoft/vscode/blob/00525e9f7c4bbaffb4965153837534e79606af9c/src/vs/editor/common/config/commonEditorConfig.ts#L530). As with other every setting you can also set it specific to COBOL.

_If_ you know the name, then binging the duck also provides useful information
https://duckduckgo.com/?q=vs+code+maxTokenizationLineLength

**Comment by GitMensch** [comment]
I suggest to close this with a question tag and possibly add it to an FAQ/wiki.
