### ISSUE TITLE
How can we force quick suggestion/auto-complete to UPPER-case only?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#252]
Is there an option for that, possibly outside of this extension?

**Comment by spgennard** [comment]
Done that I am aware of, typing all in capitals could be done with the extension below:
 Toggle Case - pranshuagrawal.toggle-case
 
 For me, it does not work because I would want the text inside quotes not to be affected.

**Comment by GitMensch** [comment]
Same here, still thank you for taking the time to mention that extension.
I hoped that there may be an option to have the suggested keywords to only be in uppercase, but if that isn't possible then there's only the normal typing and before save using this extensions special command to change keywords uppercase. I may find an auto action to always do that on save/build.

**Comment by spgennard** [comment]
Can't think of a reason to keep this open.. so closing it.
