### ISSUE TITLE
FR: highlight AND, OR, NOT the same way as IF and ELSE

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#253]
```cobol
           IF  OP-CODE NOT = "S"
           AND OP-CODE NOT = "E"
               IF  OP-CODE = "O"
               OR  OP-CODE = "C"
                   PERFORM OC-HANDLING
               END-IF
               PERFORM COMMON-HANDLING
           END-IF
```

has the current highlighting of

![current highlight](https://user-images.githubusercontent.com/6699539/104286412-4b0eb180-54b5-11eb-98fd-ec922e8003af.png)

It would be nice to have the common operators highlighted (like in the highlighted code sample here on github).

**Comment by spgennard** [comment]
If your chosen theme supports "keyword.control" highlights then, it will be present.

You can customize your theme and add this as required or raise an issue with your theme provider.

![image](https://user-images.githubusercontent.com/5991192/104288913-5ad7c700-54b0-11eb-821a-f597c92134d8.png)

**Comment by spgennard** [comment]
For example:

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "keyword.operator.cobol",
                "settings": {
                    "foreground": "#0A90C2",
                    "fontStyle": "italic"
                }
            },
...
```

**Comment by spgennard** [comment]
nothing here contentious, so closing

**Comment by GitMensch** [comment]
Thank you for this information. Works like a charm.

How does one produce the debug info for the tokens you've shown?

Would you accept a PR to README that adds a note about how to configure `textMateRules` `"comment.line.cobol.newpage"` and `"keyword.operator.cobol"` (maybe there are others of relevance, too)?
