### ISSUE TITLE
Metadata parsing misses some sections

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#255]
**Describe the bug**
When using metadata parsing and then dumping one can see that for copybooks that consist only of one section and multiple paragraphs only the paragraphs are included in the lable symbols, not the `SECTION`s that contain them (and therefore "go to definition" does not work).
For programs the first section after the `PROCEDURE DIVISION USING` seem to be missing, all others seem to be fine.

**Expected behavior**
Both sections and labels visible in metadata dump.

**What user & workspace settings are being used?:**
metadata caching on (and as seen with the dump: also works in general and also parses the "target copy")

**Comment by spgennard** [comment]
This not really unexpected, the whole metadata support is a hack upon a hack due to not understanding the context of the copybook itself, which is better but not perfect with the parse_copybooks_for_references support.

**Comment by GitMensch** [comment]
I see, plain scanning for metadata has no context, so the need for "good guess" is heavily increased (in _some_ places maybe scanner enhancements). I _guess_ fixing the first section within the program:

```cobol
      *-----------------------------------------------------------*
       PROCEDURE DIVISION USING ONE-PARM TWO-PARM.
       S000-STARTER SECTION.
       S000-00.
      *
```

has the context needed. This is what the copybooks (after many comments that contain their documentation) look like:

```cobol
      *---------------------------------------------------------*
       C101-INOUT SECTION.
       C101-00.
      *
```

Metadata dumping shows `S000-00` and `C101-00` being recognized, `S000-STARTER` and `C101-INOUT` being not (the later is recognized with the `parse_copybooks_for_references ` setting, which can sadly not be use-able in the case of big workspaces with ~25MB metadata and network paths).
