### ISSUE TITLE
FR: use metadata also for "peek definition" of variables

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#256]
Current state: variables are always found when they are defined in the program currently open.
When metadata parsing is on one can see in its dump that it includes `variable symbol count : NN` and then the symbols along with the line they are contained in.
But go to definition currently only works for variables if `parse_copybooks_for_references` is active.
It seems like it works for go to definition of paragraphs contained in copybooks.

Suggestions:
* "just" also look at the metadata for the copybooks contained in the program, when looking for variable definitions
* add a new metadata entry "copbooks" so a copybook which is contained in a copybook can also be found via metadata and provide the symbols
* don't add `FILLER` to the variables symbol as it cannot be referenced

**Comment by spgennard** [comment]
This is a restiction in the metadata support that is fixed with the parse_copybooks_for_references support.

**Comment by GitMensch** [comment]
I don't understand the reason for not query the (commonly local) metadata (first) before additional parsing of (possible not local) files. No fix possible sounds like a rewarding "if you can make that, I'm fine to pull it in" - is this is the case? (then I know  to reschedule my next week).
`parse_copybooks_for_references` showed to be much too slow for big projects, especially if they are on a network share.

**Comment by spgennard** [comment]
The data is not present in memory, we would need to find all the copybooks (slow/multipath search), then find the .sym to load.. move onto the next one if not found etc.. and this all has to happen in less than 200ms for it to be available... ummm.. not a viable solution.

**Comment by GitMensch** [comment]
So it looks that the main issue here is

> the data is not present in memory

It is possibly no big deal to load the data into memory _once_ when the file is opened (either the cached metadata or by parsing the copybooks), but it into a map and use that for "peek definition".

The main issue is that this data is obviously (with big copybooks that partially contain other copybooks over a network share) queried multiple times (if I remember correctly after each change of the file) where it would be enough to read in that data if file did change (no need to parse all copybooks again if only a space was added to the program file).
I guess this may be a not easy thing to change but it would help in any approach (both cached metadata and "hot-parse of copybooks").

If we'd then have a persistent map with all "active" symbols per editor window the difference would only be: "where does the initial ddata for the map comes from - metadata (which should be quite fast) or "hot parsing".

Back to the suggestion: does the extension already have a "per editor window" memory where we could place such a map?

**Comment by spgennard** [comment]
This has already been done and abandoned because the the cost of searching
for the copybook file, cache checking, loading/uncompressing, saving n+ sym
files/compressing can never be done without being out side the performance
boundaries required plus importantly the file handling affected the normal
editing behaviour.

It crippled file editting.

Caching only reduced part of the problem, it never solved.

This was the reason why it was replaced by the copybook parsing.
