### ISSUE TITLE
FR: auto-hide margins for free format

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#257]
I've thought that the margins would be automatically disabled for free format but it seems this isn't the case.

I _guessed_ that the setting

```json
    "coboleditor.fileformat": [
        {
            "pattern": "**/*.cob",
            "sourceformat": "fixed"
        },
        {
            "pattern": "**/*.cbl",
            "sourceformat": "free"
        }
    ]
```

would switch accordingly (this is the case as I can see in the outline that both types work correctly) and that it would also auto-disable the margins for the free-form reference-format files.

Is there an option for that, would it be possible and reasonable to always hide the margins in free format (or is this possibly already the case with current versions - as I'm using 6.10.3 on this machine)?

**Comment by spgennard** [comment]
This configuration is for the tokenizing of the source code.

margin are provided via editor.rulers and is a per language setting, so we can't set it per file it would affect other editors/open files etc..

**Comment by GitMensch** [comment]
So the option I found is: use a different file type (the rulers are enabled by default for COBOL, but not for GnuCOBOL):

```json
    "files.associations": {
        "*.cbl": "GnuCOBOL"
    },
    "coboleditor.fileformat": [
        {
            "pattern": "**/*.cob",
            "sourceformat": "fixed"
        },
        {
            "pattern": "**/*.cbl",
            "sourceformat": "free"
        }
    ]
```

I guess that's the best option vscode offeres here, so I'm closing this issue.
You may want to drop a similar note in the README on the fixed/free format part.
