### ISSUE TITLE
current tags and releases missing

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#258]
I've jsut recognized tht https://github.com/spgennard/vscode_cobol/tags has 7.0.0 as latest version and https://github.com/spgennard/vscode_cobol/releases 6.11.11.

Can you please re-add tagging and releases, maybe even the [CHANGELOG](https://github.com/spgennard/vscode_cobol/blob/main/CHANGELOG.md) (which is rendered in the market place and in the extension preview and has no update since November)?

**Comment by spgennard** [comment]
changelog creation was being done on an ad-hoc basis but I've not included it in the release script

tags and releases are not required, as this is delivered to the marketplace

**Comment by GitMensch** [comment]
> tags and releases are not required, as this is delivered to the marketplace

Hm, how do you compare changes between releases then?
Say: you know that version G was working, but version N is not (and HEAD is shortly before version P), so the bug was introduced something between them.

Until now the "best practice" I know of is to produce a testcase and run:

```sh
git bisect start
git bisect good G
git bisect bad N
git bisect run test_script arguments # or manually `git bisect`
```

Without tags G and N one would have to look up the complete history, at least of product.json (where one sees "bump" so has to investigate the content manually).

Maybe I did miss something, but tagging _at least_ all versions that are released sounds like a good common practice to me. and also GitGub actions and similar can be triggered for tags that match something (like `v?[0-9]+.[0-9]+.[0-9]+`) and run the release/publish scripts for you.

**Comment by spgennard** [comment]
I compare by date or I'd if needed, so far it has not been needed.

I see no need for me to reintroduce it until I have a reason to use, when I need it will be reintroduced just like it was in the first place

**Comment by GitMensch** [comment]
OK, it was fine in the first place :-) [The only question would be: why not leaving as it was?]
