### ISSUE TITLE
cobolscanner: move early for empty files

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#260]
I _think_ the following lines should not be visible for files that are completely empty or only contain COBOL comments (raised here for copybooks):

> Unable to determine if X is COBOL and how it is used
> Warning - Unable to determine context of Y, this may affect metadata caching for this file

**Comment by spgennard** [comment]
I disagree, it is valid and at the very least it shows, you want copybooks that are not needed.

**Comment by GitMensch** [comment]
Agreed in principle. Maybe an early exit after

> Warning - X is empty.

[while this is likely more reasonable as linter warning than a parsing output, but I have no clue if that would be a simple change or not]
