### ISSUE TITLE
some of this extensions features do not work if "GnuCOBOL" language is used

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#262]
**Describe the bug**
As noted, examples that does not work include `"coboleditor.format_on_return": "uppercase"`.

**To Reproduce**
1. Open a COBOL source
2. Change to GnuCOBOL language 
3. enable `"coboleditor.format_on_return": "uppercase"`
4. enter a line in lower case and press enter

**Expected behavior**
The line shoul be uppercased (according to the setting) - this actually works fine if one switches to the "COBOL" language.
I'd expect every setting in bitlang.cobol to also apply to the language provided by bitlang.gnucobol.

**Extension Version**
- bitlang.gnucobol: 0.1.4
- bitlang.cobol: 7.0.9

**Comment by spgennard** [comment]
This is correctly implemented, this extension provides features for the COBOL variants built into this extension only.

If it had a dependancy on bitlang.gnucobol to provide features to it, it would stop people using the bitlang.gnucobol extension with other "core" COBOL extensions.

If the bitlang.gnucobol extension is used with a different "core" COBOL extension, it may provide simular features or better.   

You may even find other code formatters that work with COBOL, I don't know I've not looked.

**Comment by GitMensch** [comment]
I've thought that the initial split had some "if bitlang.cobol" or "if bitlang.gnucobol" - so if both were available we also had the original features available with GnuCOBOL.

In any case - it is good that it is currently expected, can you do that "conditional combination" or would it be necessary to recombine the extensions for that?

**Comment by spgennard** [comment]
> I've thought that the initial split had some "if bitlang.cobol" or "if bitlang.gnucobol" - so if both were available we also had the original features available with GnuCOBOL.

It did but it did not work because due to the order of which extensions were loaded.

> In any case - it is good that it is currently expected, can you do that "conditional combination" or would it be necessary to recombine the extensions for that?

Not possible without making one dependant on the other.    

This feature is also marked as experimental, so it might make to completion or not.

**Comment by GitMensch** [comment]
> This feature is also marked as experimental, so it might make to completion or not.

Just a feedback: The feature to auto-uppercase (looks I've missed an "experimental" not in its description) works fine (and the metadata stuff in 7.0,9 does that too, btw, "un-deprecating" it would be cool).

> It did but it did not work because due to the order of which extensions were loaded.

Hm, maybe there's an option to tweak that?

**Comment by spgennard** [comment]
Yes, make one dependent on the other but that is not something I can do.

**Comment by GitMensch** [comment]
Hm, would it be possible to have a bitlang.gnucobol-embed which is a branch of bitlang.gnucobol which only has a different name and dependency to bitlang.cobol to solve that?

**Comment by spgennard** [comment]
I think you should look at what is available in the ecosystem is the best and quickest route to getting the function you are looking for.

They are a lot of formatters that could provide you similar to better functionality, depending on how you work.

I would just search in the extensions marketplace;

I used:

```text
@category:"formatters" case
@category:"formatters" uppercase
```

**Comment by GitMensch** [comment]
Thank you for the hint, but those extensions all don't work as they are about selecting text to be upper-cased and the intention here is to uppercase every word (= all but literal contents automatically.
I _think_ that COBOL house rules are not unlikely to be that way, so having it in this extension makes sense to me. Please keep it in.

Closing this issue (which has the formatting only as one of the features that are missing when using the GnuCOBOL language) is good as there is no intention to have the two split parts being combined. I suggest adding a wontfix label.
