### ISSUE TITLE
Tab and Shift+Tab show warning 'command not found' (instead of inserting tab or spaces)

### ISSUE THREAD

**Issue by MCEmperor** [spgennard/vscode_cobol#264]
**Bug description**
When I set the language to COBOL or ACUCOBOL and I press <kbd>Tab</kbd>, then Visual Studio Code displays a warning notification in the right bottom of the window with the message "command 'cobolplugin.tab' not found". Likewise, when I press <kbd>Shift</kbd>+<kbd>Tab</kbd>, the warning message "command 'cobolplugin.revtab' not found" appears. No indentation is changed, as would normally be the behaviour.

**To reproduce**
1. Open an existing or new file in VSCode.
0. Set the language mode to either `COBOL` or `ACUCOBOL`.
0. Press <kbd>Tab</kbd> (or <kbd>Shift</kbd>+<kbd>Tab</kbd>).
4. A warning notification appears in the right-bottom of the window, with the message *"command 'cobolplugin.tab' not found"* (or 'cobolplugin.revtab', when <kbd>Shift</kbd>+<kbd>Tab</kbd> is pressed).

**Expected behavior**
I of course expect that, depending on settings, a Tab or a certain number of spaces is inserted.

**Screenshot**
![image of warning](https://user-images.githubusercontent.com/5734897/105496499-d65e2300-5cbd-11eb-8c89-9ac6c884022b.png)

**Since**
I have switched to older versions to see since when the problem has existed, and it appears that this bug was introduced since version **7.0.12** of this extension.

**Comment by rudation** [comment]
Hi, I think this it the same issue that heppens to me - issue #263

**Comment by spgennard** [comment]
Can you update and check? - #263

**Comment by MCEmperor** [comment]
This issue has been fixed in version `7.0.13`. Thanks!
