### ISSUE TITLE
7.3.23 is forcibly changing `.vscode/settings.json`

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#270]
**Describe the bug**
After installing 7.3.23 and opening _any_ workspace that contains a source-controlled `.vscode/settings.json` file, the extension is manually adding empty settings.

![image](https://user-images.githubusercontent.com/675956/112355072-50e5f780-8c9b-11eb-9a1e-43dd3e238b2d.png)

**To Reproduce**
1. Open a workspace

**Expected behavior**
My workspace files are not automatically edited by extensions without prompt.

**Comment by spgennard** [comment]
fyi - an extension does not have to ask the user to write any setting, including an empty array

If you do want the extension to maintain any metadata, change your user setting to false for coboleditor.maintain_metadata_cache.

This is the resolution for this issue.

**Comment by kabel** [comment]
I understand that extensions are not _required_ to ask the use to write files. But when I'm working open-source projects (like microsoft/vscode) it hurts contribution workflows when files the upstream maintains are mysteriously changed without explanation.

**Comment by GitMensch** [comment]
I did not find the time yet to test the update, is there any option to store the metadata in an external file (one explicit named file with the same formats as are used in the settings would be fine) and/or named folder like it was before?

**Comment by GitMensch** [comment]
@kabel Do you say this also happens for non-COBOL projects (so we'd need to globally set metadata to off and only in COBOL workspaces settings to true)? In this case it would be the question why vscode triggers the extension - or if the extension has to somehow check if the workspace contains any COBOL at all. 😕

**Comment by spgennard** [comment]
@GitMensch - Changes have already been applied to reduce when settings are updated, so please let's focus on the latest version rather than a previous version.  

I have personally have non-cobol projects and using the latest version I have not been able to reproduce the issue.
