### ISSUE TITLE
FYI language mode case change breaks language mode settings

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#271]
**Describe the bug**
Looks like an ID for the `COBOL` language has been added in lower-case `cobol`. Sadly this means that some of my files now open in a different language mode (based on previous configuration). I have `*.c85_m` mapped to `COBOL` and `*.cbl` without mapping opens as `cobol`

VS Code treats these as completely different languages with their own set of config overrides.

```json
"[COBOL]": {
        "editor.autoIndent": "full",
        "editor.renderIndentGuides": false,
        "editor.rulers": [
            6,
            7,
            72,
            80,
            84
        ],
        "editor.useTabStops": false,
        "files.autoGuessEncoding": false,
        "files.encoding": "windows1252"
    },
```

has to be duplicated, in lowercase to apply to both, or I have to adjust my `files.associations`.

**To Reproduce**
1. Have two COBOL files: A.c85_m (mapped to COBOL) B.cbl (not mapped to anything)
2. Open both files

**Expected behavior**
These two share the same language/settings.

**Screenshots**

![image](https://user-images.githubusercontent.com/675956/112654441-671bc100-8e1d-11eb-8335-323ad29cdabb.png)
![image](https://user-images.githubusercontent.com/675956/112654690-a64a1200-8e1d-11eb-953c-86871bb01e48.png)

![image](https://user-images.githubusercontent.com/675956/112654622-916d7e80-8e1d-11eb-8cfd-a4a27a56076e.png)
![image](https://user-images.githubusercontent.com/675956/112654661-9d594080-8e1d-11eb-9d10-c9fc88203c75.png)

**Desktop (please complete the following information):**
 - OS: Windows

**What user & workspace settings are being used?:**

[Attached workspace](https://github.com/spgennard/vscode_cobol/files/6212759/TempWorkspace.zip).

**Additional context**

Is there a reason to [define](https://github.com/spgennard/vscode_cobol/blob/5e89ce0f1e841beb3b645f1c17309a95fa071d43/package.json#L962-L980) the langs with different IDs?

**Comment by spgennard** [comment]
I am not able to reproduce the issue you are having:

https://user-images.githubusercontent.com/5991192/112658108-fd1a1080-8e4a-11eb-801a-ec605402fb37.mp4

**Comment by kabel** [comment]
Odd. Let me clear all my user settings and see if it's something else I didn't include. Does your language picker show two langs?

![image](https://user-images.githubusercontent.com/675956/112658802-c67bd000-8e21-11eb-872c-65329da55bfb.png)

**Comment by spgennard** [comment]
Not quite, the same

![image](https://user-images.githubusercontent.com/5991192/112660583-86324700-8e4d-11eb-9bb2-89ae0a5b525d.png)

**Comment by kabel** [comment]
All user settings removed. 7.3.26 clean installed in insiders.
![image](https://user-images.githubusercontent.com/675956/112665369-fc708280-8e28-11eb-9201-df0cfbbd767e.png)

![TempWorkspace-1616777060202](https://user-images.githubusercontent.com/675956/112665381-fed2dc80-8e28-11eb-83ce-3b2b4a44e03e.gif)

**Comment by kabel** [comment]
More head scratching, association picker shows both upper- and lower-case on selected concurrently:
![TempWorkspace-1616778913761](https://user-images.githubusercontent.com/675956/112668942-157b3280-8e2d-11eb-8271-4e3462d0b3d8.gif)
