### ISSUE TITLE
FR: add simple task contributions

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#274]
README.md has the content for those already. I suggest to:

* move these to `contributes.taskDefinitions`
* change README.md to reference those

If you are OK with this then I'd also volunteer - just assign that issue to me in this case and I'll come up with a PR.

**Comment by spgennard** [comment]
I don't see any point in re-inventing the wheel, there are so many task providers/task contributors out there that provide more than just task definition but file definitions/editing/watchers etc.

I think people should use the standard task providers.

The example task definition is Windows ONLY, so using it as-is would pollute the task definitions for Linux/OSX.

So my answer for this is, thanks but no thanks.

**Comment by GitMensch** [comment]
That sounds reasonable. Can you please point me to one task provider for MF/ACU/COBOL-IT?

**Comment by spgennard** [comment]
Task providers exist for  npm, make, msbuild, shell, gulp, ant just to get started

You choose a task provider to match your existing project build, in the simplest case the shell provider will work just fine for ACUCOBO.

It does not need a specific provider to execute "acubench /build", task is good enough.
