### ISSUE TITLE
Is semantic tokenization still/already working?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#275]
> You can enable ``coboleditor.enable_semantic_token_provider``` if you want to try out semantic tokenisation, it currently provides semantic tokens for variables, sections/paragraphs.

_Originally posted by @spgennard in https://github.com/spgennard/vscode_cobol/issues/269#issuecomment-808978869_

I've tried that and the COBOL output pane shows

```
VSCode version                    : 1.55.0
 Platform                         : win32
 Architecture                     : x64
Extension Information:
 Extension path                   : c:\Users\me\.vscode-oss\extensions\bitlang.cobol-7.4.6
 Version                          : 7.4.6
 UNC paths disabled               : false
 Parse copybook for references    : false
 Editor maxTokenizationLineLength : 20000
 Semantic token provider enabled  : true
```

But the token inspector shows only: `keyword.identifiers.cobol` for `PROCEDURE DIVISION` and `SECTION`, and "meta.symbol.cobol" for everything else (including section- and variable-names and undefined COBOL words), given the following [test sample](https://raw.githubusercontent.com/KUMARITCHANNEL/Mainframe/master/RENMPGM);

```cobol
      ********************************************
      * COBOL PROGRAM FOR RENAMES                *
      * DATE : 07.08.2020                        *
      * AUTHOR : VIJAY KUMAR                     *
      ********************************************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. RENGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 PAY-REC.
       03 FIXED-PAY.
          05 BASIC PIC 9(5) VALUE 10000.
          05 DA PIC 9(5) VALUE 2000.
       03 ADD-PAY.
          05 HRA PIC 9(5) VALUE 1000.
          05 SP PIC 9(5) VALUE 500.
       03 DEDUCTION.
             05 PF-DED PIC 9(5) VALUE 2000.
             05 IT-DED PIC 9(5) VALUE 1000.
             05 OTH-DED PIC 9(5) VALUE 500.
       66  PAY-OTH-BASIC RENAMES DA THRU SP.
       66  PF-AND-IT-DED RENAMES PF-DED THRU IT-DED.
       PROCEDURE DIVISION.
           TESTME SECTION.
           DISPLAY  PAY-OTH-BASIC. dissingsdfdsf 
           DISPLAY  PF-AND-IT-DED.
           STOP RUN.
```

**Comment by spgennard** [comment]
I think you need to review your own settings/theme, as it appears to work for me.

![image](https://user-images.githubusercontent.com/5991192/113878269-5d954000-97b1-11eb-837c-fd5abbc501a3.png)

I even customised readonly fields:

```json
			"[Slack Theme Dark Mode]":{
				"rules": {
					"*.readonly": "#00ff60"
				}
			}
```

**Comment by GitMensch** [comment]
That looks fine, but shouldn't I get a semantic token type like you get (no matter what theme I use)? All I get are "standard token type: Other"
Note: when adding the fake-item I have a different highlighting there, too, but still the "standard token type: Other", but in this case the textmate scope is `variable.other.constant`.

I obviously miss something, but I have no clue what that is...

**Comment by GitMensch** [comment]
OK, that actually _is_ theme related as long as the default settings are active:

```json
"editor.semanticHighlighting.enabled": "configuredByTheme"
```

And as the default-plus theme I use supports semantic tokens I've thought that would also apply, should it (changing the option to "true" does not make a difference). Checking its contents it only directly highligh some semantic tokens, which is possibly the reason for the difference:

https://github.com/microsoft/vscode/blob/f1d7f7f6ce3d0a343bf03bea198aeedefa6cfaf2/extensions/theme-defaults/themes/dark_plus.json#L194-L199:

```		"newOperator":"#C586C0",
		"stringLiteral":"#ce9178",
		"customLiteral": "#DCDCAA",
		"numberLiteral": "#b5cea8",
```

Could you please check if the token inspector shows semantic tokens if you temporarily switch to the Default+ Theme?

**Comment by spgennard** [comment]
These are non-standard semantic tokens:

https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

**Comment by GitMensch** [comment]
Hm, If I got it right those non-standard semantic tokens mostly got in to support MS' "full" cpp extension.
... Using the Slack Theme in my installation did not show any semantic tokens either...

> Could you please check if the token inspector shows semantic tokens if you temporarily switch to the Default+ Theme?

It seems this should be the case so "something" is missing here (and may be for other users) and I'd really like to track that down.

**Comment by spgennard** [comment]
Yes, I am using the Dark theme

![image](https://user-images.githubusercontent.com/5991192/113981843-025e5e80-9840-11eb-9275-8da581dd8525.png)

**Comment by GitMensch** [comment]
OK, then this is not _directly_ schema related. Are there other settings in the extension than `coboleditor.enable_semantic_token_provider` that are responsible for "providing" those tokens? Maybe something "metadata" related?
