### ISSUE TITLE
only first INDEXED BY variable is recognized

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#277]
**Describe the bug**
Only the variable definition (and references of) the first element works.

**Example code**
```cobol
78  country-lim value 900.
77  country-max pic 9(3) value zero.
01  country-table.
    03  country-entry occurs 0  to country-lim
                      depending on country-max.
                      indexed by   country-idx
                                   country-idx2
                                   country-idx3
        05  ISO pic x(2).
        05  ISO3 pic x(3).
```

**Additional context (screenshots)**
Showing via outline: 
![outline](https://user-images.githubusercontent.com/6699539/114546112-17caf280-9c5d-11eb-8f74-1fc777858699.png)
and in the editor via semantic tokens (note: I _guess_ country-max should be highlighted there, too):
![screenshot](https://user-images.githubusercontent.com/6699539/114546387-5eb8e800-9c5d-11eb-90e6-50f59913400a.png)

**Comment by spgennard** [comment]
The included example is has a syntax error, it has a period at the end of ``depending on country-max``.

![image](https://user-images.githubusercontent.com/5991192/114623957-db70b400-9ca7-11eb-803b-4958c21fdccf.png)

and if the period is removed:

![image](https://user-images.githubusercontent.com/5991192/114624035-f7745580-9ca7-11eb-9655-bf897d6f8063.png)

**Comment by GitMensch** [comment]
You're right. With 7.4.13 this then looks as follows:

![editor](https://user-images.githubusercontent.com/6699539/114625983-5ab7b500-9cb3-11eb-8368-1b0ed94df0d2.png)

and the first index is also not seen in the outline any more. As the first part seems to be fixed now I assume all three indexes are found in the outline now, too? If yes this issue can be closed and I'll recheck after upgrading the plugin.

**Comment by GitMensch** [comment]
Side question: is it possible to have stuff like this in a unit test for the parser?

**Comment by GitMensch** [comment]
Verified to work as expected with 7.4.14, can be closed (possibly after adding a test).
