### ISSUE TITLE
Question: Any way to disable the _unable to locate copybook_ problem entries?

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#278]
**Describe the bug**
My program has many network copybooks that I've otherwise disabled from being loaded. When I open this workspace (configured to parse copybooks and scan on load) I get a bunch of problems loaded into the problem view.
![image](https://user-images.githubusercontent.com/675956/114764132-31397080-9d29-11eb-81e9-4bd26e91e6ed.png)

I've tried various configuration options, but I can't seem to make these go away. Is it possible to disable these info problems all together?

**Comment by spgennard** [comment]
Turn the linter to false && scan_comments_for_hints to false

**Comment by kabel** [comment]
Dang. I have the linter off, but I like the `scan_comments_for_hints` so I can tie my dependent copybook together for intellisense. 
![image](https://user-images.githubusercontent.com/675956/114770467-19fe8100-9d31-11eb-9292-acef4e4ea4e1.png)
![image](https://user-images.githubusercontent.com/675956/114770528-297dca00-9d31-11eb-9492-2c9b020a1db0.png)

**Comment by spgennard** [comment]
and this can generate the message as well

**Comment by kabel** [comment]
New config `linter_ignore_missing_copybook` works great. Thanks.
