### ISSUE TITLE
FR: add support for IBM COBOL on Linux x86

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#279]
Compile command: `cob2`
optional: special source format (matches the "common" terminal format, _similar_ but not identical to `free-form reference-format`)
Compiler Output for pattern matcher (all in stdout):

~~~
0LineID  Message code  Message text
      1  IGYDS0001-W   A blank was missing before character "h" in column 19.  A blank was as
                       sumed.
      2  IGYDS1005-E   The "DATA DIVISION" header was not found.  A "DATA DIVISION" header wa
                       s assumed before "WORKING-STORAGE".
      5  IGYDS1159-E   A "PICTURE" clause was not found for elementary item "FILLER".  "PICTU
                       RE X(1)" was assumed.
                       Same message on line:      7
     10  IGYPA3013-W   Data items "TEST-1 (NUMERIC INTEGER)" and "TEST-VAR (GROUP)" had overl
                       apping storage.  An overlapping move will occur at execution time.
-Messages    Total    Informational    Warning    Error    Severe    Terminating
0Printed:       5                          2         3
End of compilation 1,  program HELLO,  highest severity: Error.
Return code 8
~~~

**Comment by spgennard** [comment]
Sorry, this will need to be done in a different extension as it is out of scope for inclusion in this extension.

As I don't want to support something I have no exposure to or even have access to.

Your options are:
 - raise this as an enhancement with the IBM Z® Open Editor
 - create your own extension to support it

**Comment by GitMensch** [comment]
> I don't want to support something I have no exposure to or even have access to.

That's very reasonable. But I can help with that:

* [complete documentation online](https://www.ibm.com/docs/en/cobol-linux-x86/1.1)
* [60 day trial version](https://www.ibm.com/account/reg/us-en/signup?formid=urx-50118) (includes a license file which you could replace, also by another trial version license file...): work on Ubuntu >= 16.04 and RHEL >= 7.8 (and very likely with other apt/yum friends, too). The install script also gets all the dependencies installed (if you run Windows 10, then you could also use WSL and the Ubuntu installation from the MS store is enough to use the install script)

> raise this as an enhancement with the IBM Z® Open Editor

[Done](https://github.com/IBM/zopeneditor-about/issues/120) and got the response "no, this extension is only about zOS".

Note: supporting this would only mean:

* use the existing IBM syntax files for that
* add pattern matcher
* possibly in the place where `ccbl`, `cob`, and friends are called, call `cob2` and/or document, something I can help with
