### ISSUE TITLE
VSCode become unresponsible after run processAllFilesInWorkspace command in a huge worskspace

### ISSUE THREAD

**Issue by vladhietala** [spgennard/vscode_cobol#282]
**Describe the bug**
Opening a workspace with a lot of COBOL files causes the extension to save a lot of data in the setings.json file. And when I run the command cobolplugin.processAllFilesInWorkspace VSconde become unresponsible, crashes when click in Reopen and cycling message when clink in Keep Waiting.

**To Reproduce**
In our company, the ERP software is fully developed in COBOL, with 8100++ programs and 7700++ copybooks (File definition, working/local storage and procedure copybooks), so it's dificult to reproduce this behavior. All files are in local ssd drive.

**Screenshots**
![image](https://user-images.githubusercontent.com/3045903/118863616-8121cf00-b8b5-11eb-82fe-70e97f443324.png)

**Desktop (please complete the following information):**
```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
Extension Information:
 Extension path                             : c:\Users\username\.vscode\extensions\bitlang.cobol-7.5.18
 Version                                    : 7.5.18
 UNC paths disabled                         : false
 Parse copybook for references              : true
 Editor maxTokenizationLineLength           : 50000
 Semantic token provider enabled            : true
 editor.semanticHighlighting.enabled        : configuredByTheme
 [COBOL]editor.semanticHighlighting.enabled : true
```

**What user & workspace settings are being used?:**
https://gist.github.com/vladhietala/53711c800b71462332e21959caa20090
data from `coboleditor.metadata*` keys are autogenerate by extension

**Comment by GitMensch** [comment]
Does this change when you switch to the deprecated metadata handling?
1. Create a temporary folder, for example c:\Users\username\metatest
2. set the following:

```json
		"coboleditor.cache_metadata": "user_defined_directory",
		"coboleditor.cache_metadata_user_directory": "c:\\Users\\username\\metatest",
		"coboleditor.process_metadata_cache_on_start": true,
		"coboleditor.cache_metadata_show_progress_messages": true,
```
Then open that workspace again and check for differences.

**Comment by spgennard** [comment]
@GitMensch - Can you please stop changing the subject.    The processAllFilesInWorkspace is common among all caching mechanisms.   The deprecated metadata handling is deprecated and as said before it will be removed

@vladhietala - Windows has a 5second hung app timeout, so if processing takes longer than this, it might be the reason why it is not always reproducible.  If you search for HungAppTimeout, you will find out more information about it.

**Comment by spgennard** [comment]
You also might want to increase the user setting.

```json
    "json.maxItemsComputed": 50000
```

**Comment by GitMensch** [comment]
@spgennard Sorry, I just wanted to help, even with looking at the code from time to time I was not aware that this procedure is identical with all metadata variants (at least the big settings json would not have been created [that's an "uncommon" thing to have so it _may_ produce some issues, at least that was my thought)...

**Comment by spgennard** [comment]
I have increased the frequency of the process indicator, which should help keep the ui alive (if this is the problem) and lastly you can place a hard time limit on the metadata processing by changing the setting coboleditor.cache_metadata_time_limit

**Comment by vladhietala** [comment]
I'll try these tips.

**Comment by vladhietala** [comment]
One question, is it expected that the `settings.json` file from workspace have more than 8 thousands lines?

**Comment by spgennard** [comment]
> with 8100++ programs and 7700++ copybooks

It sounds reasonable given, the above.

```json
  "coboleditor.parse_copybooks_for_references": true,
```
Also, if you are using  parse_copybooks_for_references, then the only reason you need full metadata is out-of-program IntelliSense or full reference search.   Both these features are used in frequently, so just not using full metadata is still going to be a good experience.

**Comment by spgennard** [comment]
@GitMensch - this data has never been saved anywhere other than the workspace, it is substantially more complete than the depreciated caching mechanism and I have no plans to extend the depreciated cached mechanism, it is so buggy, often failed to remove items (so.. it can just grow and grow in size..), syms often included corrupt symbols.. it so buggy

@GitMensch - if you are not happy, feel free to turn it off with the ```coboleditor.maintain_metadata_cache`` option.

@GitMensch - re: ``` code-workspace is not "meant" to be growing that large```, sorry I disagree but if you feel this way please disable the option

**Comment by GitMensch** [comment]
Thanks for taking the time to answer, I'll keep the setting to put it into a named folder then (and possible delete its content from time to time manually - I totally see that this is no situation a new user should be put into by default).

**Comment by spgennard** [comment]
@GitMensch - in the future can you move this sort of conversation/commentary that is not directly related issue to the discussions area, which will allow it to continue irrespective of the status of the issue that someone has kindly raised
