### ISSUE TITLE
Margin setting not respected

### ISSUE THREAD

**Issue by Oxdeception** [spgennard/vscode_cobol#285]
**Describe the bug**
The margin setting no longer has any effect on margin decorations. Decorations appear to be always enabled for fixed format programs.

**To Reproduce**
1. Open fixed format program
2. Toggle Coboleditor.margin
3. Margin decorations are not changed

**Expected behavior**
The margin decorations are disabled if the margin setting is disabled.

**Screenshots**
![Margins](https://user-images.githubusercontent.com/30361731/121066320-bd02d280-c797-11eb-9ec4-aa042e26c4b2.gif)

**Desktop (please complete the following information):**
 - Extension Version 7.6.5
 - Also tested on Windows 10
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.12.2-1-MANJARO
```

**What user & workspace settings are being used?:**
Default beyond mentioned settings

**Comment by GitMensch** [comment]
I can confirm this issue, but note that

> [ALT] + [SHIFT] + [M]: Toggle margins (overrides user/workspace settings)

does work the same as before (next to the COBOL identifier an entry "Sourceformat: fixed" is toggled) - but both in 7.1.1 and in 7.6.5 it seem to not have any effect.

I do see that the `coboleditor.margin` setting has no description - possibly that's only a stub now (will be removed)?
The code is still in an margindecorations.ts seems also to be called but the decoration seems to not be applied.

Not sure if the `editor.rulers` setting conflict with this setting - does it?

**Comment by GitMensch** [comment]
Hm, rechecked with 7.6.6, the setting has still neither an effect (when inspecting a fixed-form reference-format source with the language id COBOL); as [ALT] + [SHIFT] + [M] doesn't do anything anymore in this scenario either, I guess the command `cobolplugin.toggle_margin` seems to don't do anything.

As the README has a note about "toggle margins" I'd expect to just do that (may only be reasonable for fixed-form at all), not change the internal reference-format (which it _may_ has partially done before).

**Comment by Oxdeception** [comment]
I believe this issue should be reopened - Neither the setting or the command appear to have any effect in 7.6.7.

**Comment by spgennard** [comment]
@Oxdeception - Works for me, so I think you need to provide more information

https://user-images.githubusercontent.com/5991192/121253303-dcd1ed80-c8a0-11eb-94d1-4478c52230f0.mp4

**Comment by Oxdeception** [comment]
Disabled all other extensions. Reset extension settings to defaults. 
Please let me know which other details I can provide.

![7.6.7](https://user-images.githubusercontent.com/30361731/121274306-397cda80-c898-11eb-80aa-43c687ffb80e.gif)

**Comment by spgennard** [comment]
@Oxdeception - You will see no difference because the *automatic* source format has already found it is "fixed" format

If you look closely, the sequence numbers area and columns 73-80 are all the same, so it is fixed.

If you "break" the fixed format rules by extending one of your lines you will see that the area changes column and this is when the "override" use of the margin property can be used.

You can see the difference, already... compare line 4-5 on your original screenshot with your latest animation.

**Comment by GitMensch** [comment]
I _think_ this is most an issue what the setting is about. Can you please add a description to it and possibly also extend the explanation in the README?

_My_ personal misunderstanding was that this is about showing the "rulers".

**Comment by spgennard** [comment]
@GitMensch - for editor.rules you will have to consult Microsoft documentation, as it provides the functionality

**Comment by Oxdeception** [comment]
The expected behavior is that the margin decorations are not drawn when the setting is disabled, even if the source format is fixed.  Going back through previous versions, this was how the setting appeared to work until 7.3.29.

The setting behaving as expected in 7.3.28:
![Expected](https://user-images.githubusercontent.com/30361731/121345098-737aca80-c8f2-11eb-9422-b317916ee948.gif)


"Breaking" the fixed format rules also only seems to apply if I have three lines that break the format in the first 10 lines. One line and two blank lines also works for that. I would however prefer not to need to break the format rules. Should this setting be split instead into a general enable, and a force enable for free format?

**Comment by spgennard** [comment]
Having thought it more.

The `coboleditor.margin` was created independently from the source format scanning and now that is mostly driven by the source format itself, it makes no sense to have the `coboleditor.margin` option, as they only allow an override option, not an on/off toggle as you desire.   So I will remove it and stick source format options instead.

You can force the fixed source format by using compiler directives in your source file, for example with Micro Focus dialects use:
`$set sourceformat"free"`

**Comment by Oxdeception** [comment]
While a compiler directive is an option, I would prefer not to need to add and remove it just to not have margin decorations. The programs I work on are and should always be fixed format, and unfortunately the margins cause quite a bit of input lag on my remote system.

Please reconsider removing this option.

**Comment by spgennard** [comment]
You will still be able to use the source format strategy option (setting it
to fixed) and I look at doing the scanning without depending on a completed
scan

**Comment by spgennard** [comment]
I will make the transition automatic between the settings and it will be
consistent.

**Comment by Oxdeception** [comment]
I'm not sure the scanning is the source of the input lag, unless you're talking about the line scanning for where to put the decorations.

Using 7.3.28 with source format set to "always fixed" and margins on also has this input lag, where turning the margin setting off removes it. 

I may possibly be misunderstanding what you're saying, however.

**Comment by spgennard** [comment]
I am talking about the lag between scanning (no parsing happens) and the
determination of the source format so that margins can be placed it removed
