### ISSUE TITLE
Discussion/question about COBOL debuggers

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#288]
As #273 is solved I originally wanted to move that to discussions but it seems that feature has gone.

Because of the message for debuggers for another COBOL vendor: Do you have some knowledge about the availability of a COBOL debugger extension for VisualCOBOL and/or COBOL-IT? That would be good news.

Just a note: the debugging check currently has no check for COBOL, therefore the extension currently creates a bunch of warnings for Python, C, ... noting this is a debugging extension for another COBOL vendor.

**Comment by spgennard** [comment]
The extension checks for breakpoint support for the COBOL language, so I
expect it to pickup other extensions that may not advertise COBOL support
but do have it, for example the webfreak gdb debugger.

**Comment by GitMensch** [comment]
That's interesting and then makes sense, thank you. In this case only that extension will be noted and the others skipped - a reasonable approach..

As I had to debug in called "C" routines from a MF only workspace yesterday and GDB is the reasonable debugger for that - is there an option to disable the debug extension check in general? (The bitlang.gnucobol extension is deactivated in the workspace, so the "skip" that works for a GnuCOBOL related workspace won't be triggered here?)

**Comment by spgennard** [comment]
I use a different instance of vscode and give it a seperate ext/config area eg:

```shell
code  --user-data-dir ~/.gdbcode --extensions-dir ~/.gdbcode_exts
```

and then setup an 'alias' eg:

```shell
alias gdb_code="code  --user-data-dir ~/.gdbcode --extensions-dir ~/.gdbcode_exts"
```

then just use gdb_code..
