### ISSUE TITLE
Go To Definition with MF Cobol Extension

### ISSUE THREAD

**Issue by Jeb187** [spgennard/vscode_cobol#290]
**Describe the bug**
"Go to Definition" is broken, when using this plugin together with the Micro Focus Cobol extension. Variable and section names with "-" delimiters are not correctly recognized.

**To Reproduce**
1. have this extension and Micro Focus Cobol extension activated
2. Extend_micro_focus_cobol_extension is set to true
3. have a section called W00-CALL-MFE 
4. Right-Click on any part of the section name in the "perform" line (PERFORM W00-CALL-MFE)
5. select "Go to Definition"
6. See error "No definition found for 'W00'" (when rightclicking on the W00 part)  or "No definition found for 'CALL'"  (when rightclicking on the CALL part); you get the idea
![screenshot](https://user-images.githubusercontent.com/54668471/125029548-21140180-e08a-11eb-9889-4a9c1cd704be.png)

When the section name is selected, the last part of the name is used for searching the definition.
![screenshot2](https://user-images.githubusercontent.com/54668471/125029775-705a3200-e08a-11eb-824a-fdd4c70b1319.png)

**Expected behavior**
Going to the definition of W00-CALL-MFE in the source file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (client), SLES (Linux Host)

**Comment by spgennard** [comment]
@Jeb187 - The issue with the "-" is that the Micro Focus COBOL extension language does not change the wordPattern for language definition of "cobol".

Short term, I can fix it from my extension but you should consider raising the issue with Micro Focus.

Next the "Micro Focus COBOL extension" does not have any "goto definition" support.

I can fix, this by enabling my extensions "goto definition" support when the MF extension is active.

Again, long term this should be fixed in the Micro Focus Extension.

**Comment by GitMensch** [comment]
> I can fix, this by enabling my extensions "goto definition" support when the MF extension is active.

Please do (and also for the gc extension, please).

**Comment by spgennard** [comment]
@GitMensch - I don't think the Micro Focus COBOL extension can be used with GnuCOBOL extension, as it uses a different language id, so I fail to see how it is appropriate.

**Comment by GitMensch** [comment]
The idea was to extend both the MF extension, ideally using the language id mfcobol, and the GnuCOBOL extension which takes gnucobol.
This way you can have all three installed and this extension improved both of the others.

**Comment by spgennard** [comment]
@GitMensch - I think I have been very clear the focus of this extension has nothing to do with the GnuCOBOL extension or its toolchain

The co-existence of extensions that provide tools for the same language is an edge case, as most developers will only be using one toolchain.

I don't know for sure, but I suspect that your job is focused on migration between micro focus-based sources to gnucobol, so consequently, you want me to bend this extension to meet your will but my focus is providing the best for people who want to use micro focus compiler toolchain, so I am afraid we will always be at an impasse as our core requirements differ.

**Comment by GitMensch** [comment]
> Next the "Micro Focus COBOL extension" does not have any "goto definition" support.
> I can fix, this by enabling my extensions "goto definition" support when the MF extension is active.

While this issue (word pattern) is solved, if I read this correctly the "go to definition", which is not yet available in the MF extension, currently still won't work. If this is the case, can you please add it?

Note: I work in a multi-COBOL environment, so I'd in general prefer one extension handling the language part well and have additional vendor-specific extensions that add their own pattern-matchers, tasks and debuggers.

**Comment by spgennard** [comment]
@GitMensch - Not sure what you are doing it is present if you have enabled it

> Note: I work in a multi-COBOL environment, so I'd in general prefer one extension handling the language part well and have 
> additional vendor-specific extensions that add their own pattern-matchers, tasks and debuggers.

Then you should, as I previously said, raise the defect with Micro Focus COBOL extension authors, as that is the right thing to do.

This change is only a short-term "stop" gap change.

```json
	"settings": {
		"coboleditor.extend_micro_focus_cobol_extension": true,
		"coboleditor.extend_micro_focus_cobol_extension_editor": true,
		"coboleditor.extend_micro_focus_cobol_extension_editor_fix290": true,
```

**Comment by spgennard** [comment]
@Jeb187 - I am sorry to inform you but the license of the "MF COBOL extension" prohibits it from being extended, so I will need to remove this feature.
