### ISSUE TITLE
FR: for untrusted workspaces: have "go to definition" work in the same file

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#291]
It is good that untrusted workspaces don't have the full feature-set with this extension.

Could "go to definition" be added as "only in the file currently opened" (= no use of workspace definitions, only temporarily done in the current file)?

**Comment by spgennard** [comment]
Sorry, not possible, as the source is untrusted, so it is not scanned, therefore any feature dependant on this is not possible either.

This is not a restriction, it is by design and not something I am willing to endamage on.

**Comment by GitMensch** [comment]
Thanks for the note, then this is totally the correct thing to keep.
