### ISSUE TITLE
FR: add pattern matcher for citpgsql

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#292]
As this is a COBOL-IT -> MF product used for preprocessing it seems useful to be added.

**Comment by GitMensch** [comment]
Maybe it would be good to tell the bot to don't auto-clause anything that got a label?

**Comment by GitMensch** [comment]
Hey bot, can you reopen this? If not: @spgennard what is your take on this?

**Comment by GitMensch** [comment]
Ping on re-opening. Additional: Would you like to have a PR to include [CitSQL](https://www.microfocus.com/documentation/cobol-it-sql/1-3/pdfs/getting-started-with-citsql.pdf) pattern matcher? I'd assume that all CIT SQL Precompilers (`citmysql`, `citodbc` and `citpgsql`) use the same message format, but I actually don't know and could only test with the last one.

**Comment by spgennard** [comment]
I will put this on hold until the next COBOL-IT is released and then review.

**Comment by GitMensch** [comment]
Hm, not sure there will be a new CitSQL anytime soon.
Is there a way for you to keep this issue open (possibly a "on hold" tag that the bot checks)?
