### ISSUE TITLE
Add Adabas Natural support

### ISSUE THREAD

**Issue by yanivz** [spgennard/vscode_cobol#295]
Can you add please add support for the programing language "Natural" Of ADABAS MF?
it's similar to COBOL but there is no support all over visual studio marketplace.

**Comment by spgennard** [comment]
It is not something I familiar with.

Can you point me at some documentation/examples?

**Comment by spgennard** [comment]
The only thing I found is at https://en.m.wikipedia.org/wiki/ADABAS#Natural_(4GL)

**Comment by yanivz** [comment]
You can find here too [https://documentation.softwareag.com/natural/nat821mf/overview.htm](https://documentation.softwareag.com/natural/nat821mf/overview.htm)

**Comment by GitMensch** [comment]
That sounds interesting but out of scope of this extension. I think the best option would be to fork it and create another one targeting ADABAS.

**Comment by spgennard** [comment]
@GitMensch You may be right but that is something I will decide if/when I decide to do it
