### ISSUE TITLE
VS marketplace: ChangeLog broken

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#298]
This is an "external" bug, just reporting it here because it may has something to do with the formatting or even package.json.
I did not check further but am quite sure that the link found on the marketplace showed something reasonable before - now it is all garbage:
https://marketplace.visualstudio.com/items/bitlang.cobol/changelog - compare with https://marketplace.visualstudio.com/items/bitlang.cobol-switcher/changelog

**Comment by spgennard** [comment]
okay, will remove it.

**Comment by GitMensch** [comment]
The Changelog of the cobol-switcher is now completely gone (please bring it back) and now the Changelog of this extension is identical broken.

It started 15 days ago with 386d67a2fc061c578f5b4aea3b456ce5af91d9da  and c13e9d2c3579b7547091cb2b281a46918e539905 and is now updated the same broken way. Please bring it back again.

**Comment by GitMensch** [comment]
I've created #301 to fix this for this extension, it still would be nice to have a reasonable Changelog for the switcher plugin.
