### ISSUE TITLE
What is the point of gnucobol prefer syntax

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#300]
Doesn't this disable this plugin effectively completely for COBOL files (so only directive files and pattern matchers are available)?
Would it be possible to _extend_ this plugin by the bitlang.gnucobol one instead, so it is possible to use the best of both in a single workspace? (Sorry for asking again, last time we did talk about this in #290, but I still haven't understood this, but _really_ would like too).

**Comment by spgennard** [comment]
No, gnucobol.prefer_gnucobol_syntax is only used when checking for debugger compatibility.

**Comment by GitMensch** [comment]
Yeah, that's sure, but when I activate it then the language automatically changes from the workspace setting "COBOL" to "GnuCOBOL" and all outline, semantic highlighting, go to is gone - which is what this extension provides, isn't it?
So even with this extension activated - all its features are disabled and then it would be more reasonable to deactivate the extension completely...
What point did I miss?

**Comment by spgennard** [comment]
You need a language server for gnucobol syntax if you want these features.

**Comment by GitMensch** [comment]
Actually this extension works quite fine for that, as long as it isn't "disabled" by this setting.

**Comment by GitMensch** [comment]
The extension now also works in use with GnuCOBOL extension. This one is now only used for the additional features [dump/listing highlighters and problemMatchers] which is good, thanks to b65a551744c8cca.
