### ISSUE TITLE
get commands and keybindings work in valid_cobol_language_ids

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#303]
the current version in package.json is:

```json
   "when": "editorLangId == COBOL && !inSnippetMode"
```

and therefore listed multiple times and does not work for `coboleditor.valid_cobol_language_ids`.

I think the [in-conditional-operator](https://code.visualstudio.com/api/references/when-clause-contexts#in-conditional-operator) may work (if `config` is not limited to boolean values):

```json
   "when": "editorLangId in config.coboleditor.valid_cobol_language_ids && !inSnippetMode"
```

Otherwise it should be possible when copying the setting at execution (or setting adjustment) time to a [manual context](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context).

**Comment by spgennard** [comment]
Not all commands are appropriate for all COBOL language identifiers, therefore restricting this to "known" supported languages by this extension feels like the right thing to do.

If this change was made, it would open it up to unsupported scenarios and possible keybinding command/keybinding clashes outside of the control of this extension.

**Comment by GitMensch** [comment]
OK, what about adding a context with the fixed list to be able to reduce the duplication in package.json? I volunteer to PR for that too :-)

**Comment by spgennard** [comment]
package.json properties does not have such a thing as a read-only property list, it would also require validation on entry, validation on change (in the extension) and deciding what to do if someone put something illegal in the list, which my reckoning is way more complex than a few static cut-paste items in the package.json.
