### ISSUE TITLE
web-extension with no symbols / outline

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#307]
Works fine in vscode, but on github.dev the outline is empty, no bracket navigation and go to definition not working.

Main questions:

* Is it intended to work?
* If yes: Does it work for you?
* If not: Is it "on the roadmap"?

Side note: also happens with the mfcobol extension, but I don't know if it does provide the symbols on vscode.

**Comment by spgennard** [comment]
It is currently working as expected.   

The web version has very limited functionality but it will get better over time as more features are re-coded to work in the browser.

> Side note: also happens with the mfcobol extension, but I don't know if it does provide the symbols on vscode.
Sorry but it is not for me to comment on the mfcobol extension, you should speak to them through the documented channels.

**Comment by GitMensch** [comment]
Sounds good and totally reasonable. Can you please adjust README.md to

* either have a short notice in the feature list  (like `_not available in the web-extension yet, wip_` after the "outline" and "breadcrumb" and other related headers)
* or have a separate header "Web-Extension status" saying which of the features are already or not / not yet available for the web extension

If/once they are all working that can be removed completely.
