### ISSUE TITLE
bitlang.vscode_cobol_depreciated_features with non-working repo link

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#309]
Keep that legacy code in a separate extension for now was definitely a good move.
Can you please make https://github.com/spgennard/vscode_cobol_depreciated_features public?

**Comment by spgennard** [comment]
> Keep that legacy code in a separate extension for now was definitely a good move.
"for now" should be replaced forever.

Sorry, the repo is archived, so it has no value in making it public.

The repo link was removed, after the first release, so no reference to this repo exists.

**Comment by GitMensch** [comment]
> no reference to this repo exists.

Then I wouldn't have known of it. The marketplace lists it under "homepage" at https://marketplace.visualstudio.com/items?itemName=bitlang.cobol-depreciated-features (as it was the case for the switcher extension before you had switched it homepage to this repo).

> Sorry, the repo is archived, so it has no value in making it public.

Hm, it is listed as licensed under MIT, you may want to adjust this.

I totally agree that as "it is deprecated and has it in its title" + having the repo archived makes a reasonable strong statement that you won't work on this code any more.

In any case an extension with source code has always value as it allows people to inspect the code and - if they ever find they need an adjustment to get it working with newer [or older] vscode versions - they can easily create a fork of the archived repo, do their changes and use the resulting vsix without the need to ask you for the git snapshot/dump.
Additional value: some environments don't allow to install just any vsix - it is much easier to get through such process when there's a public source repo available, even when it is archived.

**Comment by spgennard** [comment]
The extension has been removed and next weekend/next week I take time to reconsider its use and how it should be licensed to ensure the expectation of use is in line with that the amount of time I want to spend on it.

**Comment by GitMensch** [comment]
Actually MIT + archived repo with a DEPRECATED header is quite clear that this is a "take it as it is" extension (and "go fix it yourself if necessary"). Is stay tuned for the result of your consideration.
