### ISSUE TITLE
Outline view

### ISSUE THREAD

**Issue by worksofliam** [spgennard/vscode_cobol#312]
Hi!

I am testing your extension with some COBOL that compiles on IBM i (prev. AS/400) and wondering how much work it would take to support it. ILE COBOL supports up to COBOL 85, and from the testing I've done, this snippet should show results in the outline view.

```cobol
       IDENTIFICATION DIVISION.
           PROGRAM-ID. PGMNAME.
       DATA DIVISION.
           LINKAGE SECTION.
               01 base.
                 05 a PIC X(5).
                 05 b PIC X(10).
      *      Output struct might go here

           WORKING-STORAGE SECTION.
      *        Variables

       PROCEDURE DIVISION USING base.
           MAINLINE.
               DISPLAY a OF base.
               DISPLAY b OF base.
               STOP RUN.
```

While the outline view doesn't show anything, the 'Go to Data/Procedure/Working-Storage Division' buttons work as expected, which is great.

Thanks for a great project!

ILE COBOL standards information: https://www.ibm.com/docs/en/i/7.3?topic=aiclr-industry-standards-1

**Comment by worksofliam** [comment]
Here is the output from the COBOL output channel.

```
VSCode version                              : 1.63.2
 Platform                                   : darwin
 Architecture                               : arm64
Extension Information:
 Extension path                             : /Users/barry/.vscode/extensions/bitlang.cobol-8.1.19
 Version                                    : 8.1.19
 UNC paths disabled                         : false
 Parse copybook for references              : false
 Editor maxTokenizationLineLength           : 20000
 Semantic token provider enabled            : false
 editor.semanticHighlighting.enabled        : configuredByTheme
 [COBOL]editor.semanticHighlighting.enabled : true
 workbench color theme                      : GitHub Light
 Is Workspace Trusted                       : true
```

**Comment by worksofliam** [comment]
Actually, pretty much everything else, like 'remove comments' and 'make keywords camelcase' work!

**Comment by spgennard** [comment]
You will find on closer inspection some keywords are not displayed correctly, a quick guess from looking at the pdf above would be following keywords:

> ACQUIRE 
> BACKGROUND-COLOUR
> BITS
> B-LESS
> COMMITMENT
> COMP-0
> COMP-7
> COMP-8
> COMP-9
> COMPUTATIONAL-0
> COMPUTATIONAL-7
> COMPUTATIONAL-8
> COMPUTATIONAL-9
> CONTROL-AREA
> CURRENT
> CURSOR
> DB-FORMAT-NAME
> DEFAULT
> DESCRIBED
> DISCONNECT
> DROP 
> DUPLICATE
> EBCDIC
> EMPTY
> EMPTY-CHECK
> EXCEEDS 
> EXCLUSIVE 
> EXTERNALLY-DESCRIBED-KEY
> FETCH
> FILE-STREAM
> FILES
> FIND
> FINISH
> FOREGROUND-COLOUR
> GET
> INDICATOR
> INDICATORS
> KANJI
> KEEP
> LEFT-JUSTIFY
> LENGTH-CHECK
> LIBRARY
> LOCALE
> LOCALLY
> MEMBER
> MODIFIED
> NONE
> NULL-KEY-MAP
> NULL-MAP
> ONLY
> PREFIX
> PRESENT
> PRIOR
> PROCESS
> REALM
> RECONNECT
> RECORD-NAME
> REFERENCE-MONITOR
> RELATION
> REPEATED
> RETAINING
> RETRIEVAL
> RIGHT-JUSTIFY
> SHARED
> STARTING
> STORE
> SUB-SCHEMA
> SUBFILE
> TENANT
> TRAILING-SIGN
> TRANSACTION
> UNEQUAL
> VALID
> VLR
> WITHIN

**Comment by GitMensch** [comment]
Note: according to the referenced docs, which match the COBOL standard, there's an error in the code - `LINKAGE` should come after `WORKING-STORAGE`.

Another note: You _may_ have luck with downgrading the extension, it definitely shows up in the outline (even with wrong order) when using bitlang.cobol 7.1.1

**Comment by GitMensch** [comment]
> You will find on closer inspection some keywords are not displayed correctly, a quick guess from looking at the pdf above would be following keywords:

A bunch of those are under "(3) A COBOL reserved word that is not in Standard COBOL and is not supported by the ILE COBOL compiler. If used, a diagnostic message will be issued."; so at least those should be no problem.

**Comment by spgennard** [comment]
@GitMensch - Can you again please stop advising people to downgrade or perform unnecessary actions

@worksofliam - Hi Barry, using the same version. It works for me (even when I tweak the linkage storage order).

![image](https://user-images.githubusercontent.com/5991192/150778168-2cbdcfe5-290a-43ff-85d9-a53776b7fbaa.png)

**Comment by worksofliam** [comment]
@spgennard Came back this morning and it's working all of a sudden!

![image](https://user-images.githubusercontent.com/3708366/150796265-01f42fd4-5436-44a7-a844-6f652424b88a.png)

**Comment by spgennard** [comment]
@worksofliam - I will take a look at the pdf and see if I can see any specific gotcha that might affect its use for you.

**Comment by worksofliam** [comment]
I also figured out why it's not showing up when browsing source on the IBM i.

You can have `knownSchemes` and `member` and `streamfile` (both schemes which Code for IBM i implements) isn't on that list! Perhaps I will fork and do some playing around :D

**Comment by worksofliam** [comment]
Looks much better! Now I can open up source directly on the server and have the outline view.

![image](https://user-images.githubusercontent.com/3708366/150798529-57be0f40-9c4a-42d8-acb2-fd34ead2f969.png)

**Comment by spgennard** [comment]
@worksofliam If you using the latest, then the schema changes should be included

**Comment by worksofliam** [comment]
@spgennard Yup - thanks a bunch! That means a lot. It is working perfectly so far
