### ISSUE TITLE
Adding program extensions or file associations

### ISSUE THREAD

**Issue by kellycookson** [spgennard/vscode_cobol#316]
**Describe the bug**
The COBOL VS Code extension colorizes source code if the source code file name ends with the *.cbl extension. I would like to colorize source code if the source code file name ends with any of the following extensions:
  *.cbl
  *.cblle
  *sqlcblle
  *cblcpy
These extensions are used for COBOL source code files on the IBM i system. I am wondering if this can be accomplished by setting up file associations in settings.json. If not, I am wondering if there is some other way to get the COBOL extension to work with these additional source code file name extensions.

**To Reproduce**
1. Create a COBOL source file and use one of the following file name extensions: cobolsource.cblle, cobolsource.sqlcblle, cobolsource.cblcpy.
3. Open the COBOL source file in VS Code with the COBOL extension installed.
4. The COBOL source code is not colorized (compared to the colorized source code if the source code file was named cobolsource.cbl).

**Screenshots**
![image](https://user-images.githubusercontent.com/60078622/170555015-cb35c6f1-1b9f-4dec-b9c7-17eba9efb8fe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 21H2

**Additional context**
I have no experience VS Code extension development, or I would offer to contribute what I am requesting. I would be willing to pay a contributor to get the additional source code file name extensions added.

**Comment by spgennard** [comment]
I am not in a position to test this out, as I don't have access to a ibmi based machine but I have blindly made some changes, hopefully it helps you.

**Comment by kellycookson** [comment]
Thank you very much for the effort.

**Comment by spgennard** [comment]
Glad it worked for and thanks for the kind review

**Comment by spgennard** [comment]
Glad it worked for you and thanks for the kind review
