### ISSUE TITLE
ordering of copybook directory searchs

### ISSUE THREAD

**Issue by mdn8rdr** [spgennard/vscode_cobol#319]
How do I make the editor check the current directory before searching directories that I added to Copybookdirs?

I have a copybook that is both in the workspace folders and in a folder that I added to Copybookdirs and it is not showing the correct version with peek or shift-click or whatever method is use

**Comment by spgennard** [comment]
Sorry but Vscode has no concept of current directory

Remember it works in a browser, in a container or with remote file systems

**Comment by mdn8rdr** [comment]
Well if you can specify relative directories, how would you indicate current as a relative path? 
And to be clear, it DOES find the copybook in the current directory if its not in one of the directories on Copybookdir.
However, in that case, it is finding it as one of the directories in the workspace.
So to reword this question, how do I get it to check the workspace directories BEFORE checking the Copybookdir directories?
    On Thursday, September 15, 2022 at 02:11:29 AM EDT, spgennard ***@***.***> wrote:  
 
 


Sorry but Vscode has no concept of current directory

Remember it works in a browser, in a container or with remote file systems

**Comment by spgennard** [comment]
The search for copybooks is done through the workspace combined with the copybook search path (combining each dir together etc..)

The combined search path is shown in the diagnostic panel called COBOL.

The order of the areas in the workspace is determined by vscode itself, however you can tweak the order with the ```coboleditor.workspacefolders_order``` settings.  This allows a workspace to take presidence other another.

Relative paths (aka the use of ".."), may or may not work as URLs generally do not support them, I would avoid them if you wish your workspace to be portable and future-proof (ie: use it else for example on github etc.)
