### ISSUE TITLE
Misspelling of FEEDBACK

### ISSUE THREAD

**Issue by peterhagelund** [spgennard/vscode_cobol#323]
**Describe the bug**
The section in the sidebar that should read `HELP ON COBOL AND FEEDBACK` shows as `HELP ON COBOL AND FEEBACK` missing the `D` in `FEEDBACK`.

**To Reproduce**
1. Open VS Code with a COBOL project or file
2. Make sure the sidebar is expanded
3. Locate the above mentioned section

**Expected behavior**
`FEEDBACK` should be spelled correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/15679466/204033398-5162435c-fb63-46b3-bd23-d163d1e7f814.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.0.1

**What user & workspace settings are being used?:**
N/A
**Additional context**
N/A

**Comment by spgennard** [comment]
Thanks
