### ISSUE TITLE
Usability Question: can I turn off the vertical clues to column 7?

### ISSUE THREAD

**Issue by arnieHouston** [spgennard/vscode_cobol#326]
First Off: I love this plug-in! Its great!

But I'm using free format COBOL instead of fixed, is there any way to turn off the vertical clues for column 7, etc?

**Comment by spgennard** [comment]
This is provided by vscode and I customise it on per-language basis.   

The specific settings is "editor.rulers", so if you don't want any rules, in your settings you can use:

```jsonc
    "[COBOL]": {
        "editor.rulers": [
        ]
    }
```

**Comment by arnieHouston** [comment]
Nice. But, ah, where in the UI do add this JSON? I do not see settings for the COBOL extension. Do I put it in settings.json somewhere?

**Comment by spgennard** [comment]
https://code.visualstudio.com/docs/getstarted/settings#_settingsjson
