### ISSUE TITLE
Code coloring issue with REMARKS keyword in variable

### ISSUE THREAD

**Issue by innerskyone** [spgennard/vscode_cobol#327]
When a source contains REMARKS anywhere in the code, it will color everything starting from that line in green as comments.
For example if in working-storage there is a variable 01 REMARKS-W0, everything below is seen as comment lines.

Easy to reproduce by using any variable that has "remarks" in it.

**Expected behavior**
It should not treat a variable that contains "remarks" as comment section.

Can be worked around by adding a single commented line with END-REMARKS in it below each variable...

![image](https://github.com/spgennard/vscode_cobol/assets/65064943/eff0a900-cbb2-4e94-a996-41d58e86206b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by spgennard** [comment]
Just to let know I am looking into this issue

**Comment by innerskyone** [comment]
Thank you, love your extension!

**Comment by spgennard** [comment]
Thanks @innerskyone Free free to leave a _[review](https://marketplace.visualstudio.com/items?itemName=bitlang.cobol&ssr=false#review-details)_.
