### ISSUE TITLE
VSCOBOL / NECOBOL language identifiers

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#329]
Given a single editor (vscode) be used to work on code for several environments (Server Express, Visual COBOL 4, Visual COBOL 6, Visual COBOL 8) it would be nice to be able to configure a matching set of keywords and functions by switching the language-identifier.

So far there is ACUCOBOL and COBOLIT (quite different), along with COBOL (_what_ is that directly?) and BITLANG-COBOL, would it be possible to provide versioned dialects (like done in the GnuCOBOL extension) for "major releases" of NE/VC, or at least one for NE another for VC (the differences there are quite intense)?

This way one can use a workspace setting to configure all COBOL files to use the matching dialect.

**Comment by spgennard** [comment]
Sorry, this is out of scope

This sort of requirement is available in the official extension via background parsing.

**Comment by GitMensch** [comment]
Maybe one single "NetExpress/ServerExpress" language would still be reasonable?

**Comment by spgennard** [comment]
No point, the upgrade path is well understood, so I do not wish to promote the use of an old product.

Next, you will be requesting CIS COBOL

**Comment by spgennard** [comment]
I will take the approach to de-emphasize any support for Net Express/Server Express, thus avoiding any need to have a difference between the dialects.
