### ISSUE TITLE
conditional words not highlighted

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#330]
compare bitlang.cobol
![grafik](https://github.com/spgennard/vscode_cobol/assets/6699539/a137aa31-4451-4c2b-8a0e-39d0c0e5d125)

to BroadcomMFD.cobol-language-support
![grafik](https://github.com/spgennard/vscode_cobol/assets/6699539/f3a720e0-3e51-48b9-841e-aab74e310837)

the first doesn't have `AND`/`OR`/`NOT` highlighted.

**Comment by spgennard** [comment]
Not true, your theme just does not support keyword.operator

![image](https://github.com/spgennard/vscode_cobol/assets/5991192/75be9903-1e2c-423b-a015-ac4b2373b54b)

**Comment by GitMensch** [comment]
Sorry for the noise (especially as I've stumbled over this several months ago already). You're right, switching from the Default Dark/Dark+ to another one they are highlighted.
I suggest to add that piece of information to the README, _especially_ as this isn't shown with the default distributed one... Maybe add it to the tips?
