### ISSUE TITLE
How to turn off warnings for Acucobol?

### ISSUE THREAD

**Issue by innerskyone** [spgennard/vscode_cobol#331]
Warnings were not displayed in the past, now they are (acutally displayed as info messages). 
This is very anoying. How can I turn these off? (Turning off the filter is not enough as it still pollutes the code view.

See screenshot
![Screenshot 2023-11-21 081237](https://github.com/spgennard/vscode_cobol/assets/65064943/ff5ecd73-c2f1-449d-a172-33a5c81c9e27)

**Comment by spgennard** [comment]
You can set ```coboleditor.linter``` to false if you don't want to see them
