### ISSUE TITLE
add alternative option for source-dependency ?

### ISSUE THREAD

**Issue by Evileoo** [spgennard/vscode_cobol#333]
Hello

I would like to know if it was possible to add an alternative option for the `*> @source-dependency` comment.

Most of the times, when we add files by an other way as COPY, it is identical between all calls, so it would be awesome if we had a regex match option to get the filename.

exemple : 
*option :* `coboleditor.copybook_parse_regex: "EXEC SQL INCLUDE \"$filename\" END-EXEC."`

What do you think about it ?

**Comment by StephenGennard** [comment]
I am unsure what you are saying because if I you are in the source file fred.cbl, then:

```COBOL
EXEC SQL INCLUDE \"$filename\" END-EXEC
```

would be including itself aka:

```COBOL
EXEC SQL INCLUDE "fred.cbl" END-EXEC
```

---------------



Are you asking for a snippet "EXEC SQL INCLUDE" that does:

```COBOL
EXEC SQL INCLUDE "fred.cpy" END-EXEC
```
when in fred.cbl?

**Comment by spgennard** [comment]
Did yesterday release help? @Evileoo

**Comment by Evileoo** [comment]
This works like a charm !

Thanks !
