### ISSUE TITLE
How to use/enable the Cobol LSP?

### ISSUE THREAD

**Issue by octanervoc** [spgennard/vscode_cobol#336]
BitLang Cobol does not seem to include an LSP by default, unlike IBM Open Editor, for instance. By following past issues from this repository, I found out that the LSP is provided by another extension, such as the Micro Focus Cobol extension. However, that did not seem to make any difference. My `JAVA_HOME` is correctly set to `/usr/lib/jvm/temurin-17-jdk-amd64`. 

Am I doing something wrong? Is BitLang Cobol supposed to use another extension for LSP support? Thanks for the extension, it's much less bloated than IBM Open Editor, which helps me a lot as a complete beginner to Cobol.

**Comment by spgennard** [comment]
The extension was created before VSCODE had support for lsp, so it uses the extension  apis.

The best approach is to disable the extension via profiles and use this or other extensions when/where ever required

**Comment by spgennard** [comment]
The Micro Focus extension requires a microfocus product installed/ licensed for its lsp to work.
