### ISSUE TITLE
[feature request] navigation with SQL cursors

### ISSUE THREAD

**Issue by Evileoo** [spgennard/vscode_cobol#340]
Currently, this is not possible to see cursor declaration and references

Could it be possible to identify it as a variable ?
It would be awesome if we can move thru cursor calls

![image](https://github.com/user-attachments/assets/ef7a66f8-b020-47ae-985e-60b0a87a5406)
![image](https://github.com/user-attachments/assets/ab132a27-055f-470f-af39-6f2385e35ea0)

**Comment by spgennard** [comment]
I think this is a reasonable request, let me have a think about the best way I can do it.

**Comment by spgennard** [comment]
Please try out version 10.8.28

**Comment by Evileoo** [comment]
Okay

*Go to / peek definition* works
But *Go to / peek references* doesn't

It is still a bit easier to navigate thanks

**Comment by Evileoo** [comment]
this feature broke https://github.com/spgennard/vscode_cobol/issues/333 with the update

**Comment by spgennard** [comment]
Thanks, i will look at it tonight.

Peek references are present but hoverover peek is not

**Comment by spgennard** [comment]
If you get a chance, update and you should fine it has changed.

**Comment by Evileoo** [comment]
Yep it got fix, thanks

**Comment by Evileoo** [comment]
Tell me if I'm wrong
We can only see cursor DECLARE and FETCH right ?
It didn't seem to work on OPEN and CLOSE

**Comment by spgennard** [comment]
It should be okay, can you provide an example (does not have to compile, so you remove anything important to you)

**Comment by Evileoo** [comment]
Okay it works in my example but doesn't in the code
I'm searching for the bug

**Comment by Evileoo** [comment]
Sorry for the long waiting time.

I found out the bug doesn't come directly from your extension.
I copied a program with the bug in a new file to remove some parts and see what breaks the feature.
Surprsingly, it worked without removing any part...

I am still searching why it doesn't work in the original file.

Thanks for everything,
Léo

**Comment by spgennard** [comment]
Okay, thanks

**Comment by Evileoo** [comment]
The functionnality broke with version 24.9.29

**Comment by spgennard** [comment]
Should be okay now

**Comment by Evileoo** [comment]
Yeah, it is partially back

![image](https://github.com/user-attachments/assets/c4ffbd95-1248-4bc8-9766-1df6d4d87a71)

I can see cursor declaration but I can't navigate to it
