### ISSUE TITLE
@source-dependency Problems

### ISSUE THREAD

**Issue by Giupeppe999** [spgennard/vscode_cobol#343]
I tried to add in a source file, the comment with "@source-dependency" mark and it works correctly:
![image](https://github.com/user-attachments/assets/36e9d97f-f84d-4e91-8c73-2d622e78f4da)
![image](https://github.com/user-attachments/assets/9ae60bf6-8f3b-4a1a-888f-c98d1f1be3b4)

But there is a problem with the references of the variables in the working and linkage section, they don't work:

BEFORE:
![image](https://github.com/user-attachments/assets/8ad365c7-b25b-492a-8b54-25239c27eb74)

AFTER:
![image](https://github.com/user-attachments/assets/9126f765-9d1f-4715-b8c2-9dcea6e954a5)

And also if i search the references with F12, it doesn't work properly.

THIS PROBLEM IS TRIGGERED BECAUSE THE FILE THAT I REFER INTO THE SOURCE FILE CONTAINS THE SAME STRUCTURE OF THE SOURCE PLUS THE PRE-PROCESSOR DATA STRUCTURE (THAT ARE VERY IMPORTANT TO READ THE SOURCE FILE AND THEY HAVE TO BE REFERENCED IN THE SOURCE).
CAN YOU DO SOMETHING ? 

According to me, we should have the possibility to choice the use of the source dependecy between:
- only for data structure ( so the extesions scan only the working and the linkage section);
- all of the source ( like now ).

**Comment by spgennard** [comment]
I'm not sure, I will need to take a look this weekend

**Comment by spgennard** [comment]
Would implementing this help?

https://github.com/IBM/zopeneditor-about/issues/441

**Comment by spgennard** [comment]
I've added some code for including references from source-dep files, it is disabled by default but you enable it with setting:

`scan_comments_for_references`

**Comment by Giupeppe999** [comment]
![image](https://github.com/user-attachments/assets/53e85ba8-087b-438e-95a9-5f663319835e)
It seems that it doesn't work correctly, there are references in wrong places.
And when i press F12 in a working variable, it does't find anything. And for some variable that are used in the procedure does not appear the reference tag.
![image](https://github.com/user-attachments/assets/cab6e90c-555e-4772-9c0f-fec55501c6bb)
for example in this case it matches only the declaration, but the variable is used in the procedure.
![image](https://github.com/user-attachments/assets/9d4334a1-65d9-4618-9e89-5ea5d235d3c8)

**Comment by Giupeppe999** [comment]
ok maybe the solution is to implement the source dependency only to navigate at the declaration in the file referenced but is important to resolve the bugs above. For me could be top if i can go to the declaration in the source dependency file. but with no bugs in the references in the working.

**Comment by Giupeppe999** [comment]
ok with the last update, the references tags seems working correctly in the procedure division, but if i try to see the references in the procedure division with f12 of a variable that is used in both files (source code and source dependency activated with tag @) and are always managed not correctly.
in the image the variable S-INPU-DEPO is used in procedure division both in one file ( source) and in another (source dependency) , can you resolve this showing the using of the variable in each file as well as the declaration that appears now? 
Moreover, can i choose if i want to see only the references of the source file and the declaration if they exist from the source dep.?
if can you make me possible to choose to see only declaration with mouse or f12 from source file to source dep could be the top. i want only this. please. you can make me the work easier .

![image](https://github.com/user-attachments/assets/a34cc3f3-9453-4ab3-9e18-da4a4203a41f)

**Comment by Giupeppe999** [comment]
With last updates, everything works good, only if i press F12 on a declaration it shows only the declarations one in the source file one in the source dependency, not the using of the var, but if i press shift+f12 it works and shows me the references in the procedure and the using of var.

So the solution maybe is that if the extension is elaborating a declaration, it must not analyze the source dependency looking for another declaration, because i remind you that in my source dep there are the same declarations of the source file. 
So because of this the references of a variable not used in the procedure are wrong.
THANK YOU FOR ALL!
After this you can close the issue.


NOTE 
![image](https://github.com/user-attachments/assets/b395c435-5b22-4b98-a722-bb2de2275206)
in the image FCBH-ISAM-MNEM for example is not used in the procedure, but it shows me 2 references because it found another declaration that is set as reference.

**Comment by Giupeppe999** [comment]
!!!!!!!!!!!!! MAYBE ENDING SOLUTION !!!!!!!!!!!!!!!!
ANALYZINIG MY SOURCE DEPENDENCY FILE,
ONLY THE ROWS THAT HAVE IN THE FIRST 7 ROWS THE STRING "adecp+" SHOULD BE ANALYZED AS SOURCE DEPENDENCY BECAUSE ARE THE PARTS THAT ARE MISSING IN THE SOURCE FILE BEFORE THE PRE-PROCCESSOR COMPILATION.
AS YOU SAID 
Would implementing this help?
https://github.com/IBM/zopeneditor-about/issues/441

Yes this could help, but on the opposite, so the rows with a defined string are analyzed in the source dependency, the others NOT, are ingored.

THERE IS AN EXAMPLE OF COMPILED SOURCE (IMAGE 1) THAT I WANT TO INCLUDE IN THE ORIGINAL SOURCE FILE (IMAGE 2)
![image](https://github.com/user-attachments/assets/48535d0f-41c3-40ea-8306-891fb75def7f)

![image](https://github.com/user-attachments/assets/eafc9b7e-62ce-426b-9941-3c25ae7ff33a)

**Comment by Giupeppe999** [comment]
With the last commits it see a that you have implented a way to ignore party of source dependency, it'ok but i am not able to modify directly the source dependency if you find way to EXCLUDE ALL rows in the source dependency EXCEPT for the rows that start with a String is the top.
Maybe i was not clear in previous commenti. 
Sorry another time 😖

**Comment by spgennard** [comment]
Please note these changes have not been released and are subject to change/ removal etc, eg if this causes stability or performance issues 

> Fyi. You can place a tag at the top source that turns it off

**Comment by spgennard** [comment]
Thinking about it more, the easiest way is to have a post-build step that takes your listing file and creates a dep file, for example:

```cobol
       program-id. fred.
       working-storage section.
adecp+ 01 ws-wibble pic x(10).
       01 ws-second pic x.
       procedure division.

           goback.

       end program fred.
```

Then using the simpliest of tools:

```shell
grep -E "^adecp+" fred.cbl >fred.cbl.dep
```
Your get:


```cobol
adecp+ 01 ws-wibble pic x(10).
```

**Comment by spgennard** [comment]
1> use a makefile or something, which if done right only does the actions unless it is out of date
2> do the dep file creation on the client
3> do it on save or a post build

extensions are available to execute commands on save, so this could be another route to ensure the dep file is always in-sync

**Comment by Giupeppe999** [comment]
yes of course but i use the remote ssh extension, because we work on server so i cannot create file on the client and or on the client or on the server, there would be the same problem the amount of the genereted files, thousand of files 😖

**Comment by Giupeppe999** [comment]
Any news?

**Comment by spgennard** [comment]
WIP to add regex based inclusion filter and finer grain with lsp on/off comments

With docs update

**Comment by Giupeppe999** [comment]
THANK YOU, YOU'RE THE BEST

**Comment by spgennard** [comment]
You can try out, the regex is between the two /'s

```cobol
*> @source-dependency /adecp+/ proc.cbl`
```

also you can ignore specific ranges with:

```cobol
      *> BEGIN-LS-IGNORE
      01 ws-hidden pic x.
      *> END-LS-IGNOREc
```

If the semantic token provider is enable, then the tokens are marked as comments.

```json
{
 "settings": {
"coboleditor.enable_semantic_token_provider": true,
..
```

**Comment by Giupeppe999** [comment]
Thank you for all, this upagrde make us work a lot better. 😊😊
