### ISSUE TITLE
Automatic source dep. with a relative path for all files 

### ISSUE THREAD

**Issue by Giupeppe999** [spgennard/vscode_cobol#345]
My source dependency files are always in the same scheme of path that change depending on the name and on the position of the file. 

The path could be compose with the vscode variables in this way:
${relativeFileDirname}/CBL/${fileBasenameNoExtension}.CBL
(resolved is SL/E28/CBL/PROGRAM.CBL)

Is possible to set this path (with vscode vars) automatically for all of files that end for example with "*.DD" and the extension considers the resolved one (without vars but values)?

THANK YOU, sorry if i am disturbing you a lot.

**Comment by spgennard** [comment]
Why dont you use the copybookdirs setting?

**Comment by Giupeppe999** [comment]
Because there is one file source dependency for only one source file not for all files. And is not a copybook but a compiled resutl file by preprocessor.

**Comment by spgennard** [comment]
A source-dependancy is a copybook that is included via a comment.

Referencing a listing file will bring in more items than is required and should be avoided, which may well break the structure program.

Only include the items you need, and as rule of thumb source-dependencies and copybooks are interchangeable.

**Comment by Giupeppe999** [comment]
In the source files the source dep. is not referenced by "COPY" statement, and if i add the directory in copybookdirs, it doesn't do nothing, so i'm using for every file the source-dependency comment and it works as well as possible. 
But for every source i must add the comment, and i have a lot of source files. 
So this is the reason why i want to declare a relative path to include the source dependecy in every file.

**Comment by spgennard** [comment]
Relative paths are not portable as vscode uses urls under the covers, as it works in the browser.

**Comment by Giupeppe999** [comment]
ok so if you cannot do anything i close this issue, but please resolve this in the last comment IS IMPORTANT for us:
https://github.com/spgennard/vscode_cobol/issues/343

**Comment by Giupeppe999** [comment]
closed
