### ISSUE TITLE
References bug came back (less annoying)

### ISSUE THREAD

**Issue by Evileoo** [spgennard/vscode_cobol#346]
Hello

The references bug https://github.com/spgennard/vscode_cobol/issues/342 came back but in a less annoying way

They are some *X references* showing up at random positions in the code

![image](https://github.com/user-attachments/assets/b6326126-be85-4fa7-be80-67673bb326f8)

Like in previous issues, when you click the references, it shows *No results*

![image](https://github.com/user-attachments/assets/61f587a8-80f3-4ca7-8080-c9d7fc9be4a8)

**Comment by spgennard** [comment]
You will need to provide an example

**Comment by Evileoo** [comment]
Okay I've been trying to find why there is a bug, and this is going REALLY weird

[Vidéo 10 09 à 13.49.webm](https://github.com/user-attachments/assets/8fbe5bb1-6ee2-4df7-9a09-3ca4f539926e)

It happens with some specific includes/source-dependency combos and the *references* will always show at a specific line (120 in this case), no matter what is written on the line

This bug appeared in the version 24.9.23

**Comment by spgennard** [comment]
I believe this is fixed

**Comment by Evileoo** [comment]
It is. Thanks
