### ISSUE TITLE
CALL program open source

### ISSUE THREAD

**Issue by Giupeppe999** [spgennard/vscode_cobol#347]
Good morning, 
i have a request, tell me if it is possible.
Can you make me able to press ctrl+click on call program or press F12 to see the source of called program?
For instance, i have this call:
![image](https://github.com/user-attachments/assets/0ac65923-4347-459d-a83c-60e3f9b26be9)

i press ctrl+click on the call program between quotation marks and automatically the extension bring me to the called program source.

**Comment by Giupeppe999** [comment]
news? is it possible ?

**Comment by spgennard** [comment]
As said, you can navigate to a known program that has been seen or processed through the metadata (maintain_metadata_cache).

Then, once you use it for navigation to the file, you can then navigate back to the previous source file with alt+left aka go > back command.

What is definitely not present, isn't supported is called-by searches, so they may be some confusion here.
