### ISSUE TITLE
Custom comment

### ISSUE THREAD

**Issue by Giupeppe999** [spgennard/vscode_cobol#348]
Another request.
Is it possible to customize the comment string.
now if i select a part of code, how can i comment the selected part?
and can i customize the type of comment?
for instance we use to comment with this string "<<<<<<*" instead of "      *".
can i do this?

**Comment by spgennard** [comment]
This is a comment if the source is fixed format because the * is in the right place.

"<<<<<<*"

**Comment by Giupeppe999** [comment]
i know, i want that "*" on the 7 column is replaced by "<<<<<<*", can i do this?

**Comment by spgennard** [comment]
You will need to add your own colourisation in your vscode syntax extension.

**Comment by Giupeppe999** [comment]
yes i did this, but if i press ctrl + ù does not commenti with <<<<<<* but only with *
