### ISSUE TITLE
feature request - support settings.json file when working with multi-root workspace

### ISSUE THREAD

**Issue by Evileoo** [spgennard/vscode_cobol#349]
Hello,
Actually, when working with a multi-root workspace, if some settings are changed in the settings.json file of a workspace, it is ignored.
![image](https://github.com/user-attachments/assets/03f017be-d18f-492b-ad7c-4d6060d4d565)

I'd like to know if it was possible to handle multi-root workspaces

**Comment by spgennard** [comment]
It's possible but what specific settings are you looking to have on a per workspace basis?  (most important first please)

**Comment by Evileoo** [comment]
Most important : 
* copybookexts
* parse_copybooks_for_references
* copybookdirs

Less important :
* intellisense_style
* format_on_return
* comment_tags & enable_comment_tags
* linter settings* tabstops

**Comment by spgennard** [comment]
Thank you that helps, let me take a look

**Comment by spgennard** [comment]
Just to keep you in the loop , this is in progress, but i have some technical debt that is slowing my progress.

**Comment by Evileoo** [comment]
Hello, I forgot about the `program_extensions` in *most important*
sorry

**Comment by spgennard** [comment]
Program extensions are used at a workspace level (source window, file
associations)

Perhaps you want to use copybookexts
