### ISSUE TITLE
REQUEST IMPLEMENTATION 

### ISSUE THREAD

**Issue by Giupeppe999** [spgennard/vscode_cobol#352]
Good morning,
i have a request, tell me if it is possible.
Can you make me able to press ctrl+click on call program or press F12 to see the source of called program?
For instance, i have this call:
![image](https://github.com/user-attachments/assets/30897c77-cb2d-4113-b051-d464f3d44dfb)

i press ctrl+click on the call program between quotation marks and automatically the extension bring me to the called program source.

**Comment by Evileoo** [comment]
It is already live
double click on the name of the program and press F12

**Comment by Giupeppe999** [comment]
for me it doesn't work, should i configure some settings to fix it?

**Comment by spgennard** [comment]
If you provide example source files and your workspace file it would be easier to help
