### ISSUE TITLE
Add highlighting for JES2 control statements

### ISSUE THREAD

**Issue by Zastai** [spgennard/vscode_cobol#38]
Currently, most "normal" JCL syntax is highlighted nicely (thanks!).
However, JES2 control commands (/*ROUTE, /*JOBPARM, ...) are not highlighted at all.

Overview: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.ieab600/j2st.htm

**Comment by spgennard** [comment]
Can you try out the recent changes and give me some feedback.

with thanks

**Comment by Zastai** [comment]
Looks pretty good already. I'd be inclined to want the keyword in the same color as an operation for a regular JCL statement. In other words, the ROUTE (or the entire /*ROUTE, if that's easier) in "/*ROUTE ..." in the color of the EXEC, not the MYSTEP, in "//MYSTEP EXEC FOO".

I may log some other cosmetic tickets for JCL later. None of those are high priority; I'm very happy to have JCL syntax highlighting at all :)

**Comment by spgennard** [comment]
The word has been done, if you find any other problems please raise a further issue and include an example or just the snippet of the code to demonstrate the issue.
