### ISSUE TITLE
No longer displaying working storage names in suggestion pop-ups

### ISSUE THREAD

**Issue by andycrofford** [spgennard/vscode_cobol#41]
This was a change made in 2.1, here is the original request:

https://github.com/spgennard/vscode_cobol/issues/10#issuecomment-397339258

For some reason it does not seem to be working now. I am not sure in which version it stopped.

Thanks,
Andy

**Comment by spgennard** [comment]
Can you be more specifc, it appears okay for me.

![image](https://user-images.githubusercontent.com/5991192/50363907-c6673880-0565-11e9-8c70-41c27270502c.png)

Test case:

```cobol
000100 IDENTIFICATION DIVISION.                                         000100
000200 PROGRAM-ID. HELLO.                                               000101
0A0250* THIS IS A COMMENT LINE                                          000102
000300 PROCEDURE DIVISION.                                              000103
000350 A000-FIRST-PARA.                                                 000104
         *> Inline comment
      * no line number comment

* this line should also be a comment
 * this should not be a comment
  * or this
   * or this
    * or this
     * or thhis
      * this is okay

000400     DISPLAY "Coding Sheet"                                       000105
000500 STOP RUN.                                                        000106

* Line 20
*> Line 21
```

**Comment by spgennard** [comment]
I believe this is fixed, can you please try again and re-open/open with an example it fails

**Comment by andycrofford** [comment]
> I believe this is fixed, can you please try again and re-open/open with an example it fails

Yes, it works perfectly. Thank you!
