### ISSUE TITLE
Keywords and literals are not colored when followed by comma or semicolon in AcuCOBOL

### ISSUE THREAD

**Issue by MCEmperor** [spgennard/vscode_cobol#42]
Keywords and numeric literals are not colored when they immediately precede a semicolon or comma in ACOCOBOL, but they should.

The following code shows this behavior:

    read SOME-FILE next
        at end
            continue;
    end-read;
    goback 0;

I expect the keywords `continue` and `end-read` to be colored, as well as the zero.
They are not, however, because they are followed by a semicolon. If the semicolons are removed, then these keywords are colored.

**Comment by MCEmperor** [comment]
In the source code for the tokenization of COBOL, many keywords are tokenized as such when they follow particular characters, for example, a space or period, for example `(?=\\s|\\.|$)`.
However, I think they should be tokenized whenever the following character is _other than_ A-Z, a-z, 0-9 or a hyphen or an underscore, as those characters are legal identifier characters.

**Comment by spgennard** [comment]
I've tweaked the tokenization as you suggested and feels like a much nicer solution that using ``(?=\\s|\\.|$)``, so it would be appreciated if you could pick up the latest version see if it works for you.

**Comment by MCEmperor** [comment]
> I've tweaked the tokenization as you suggested and feels like a much nicer solution that using `(?=\\s|\\.|$)`, so it would be appreciated if you could pick up the latest version see if it works for you.

Works like a charm! Thank you very much.
