### ISSUE TITLE
Outline on ACUCOBOL

### ISSUE THREAD

**Issue by ebat79** [spgennard/vscode_cobol#47]
When I open an ACUCOBOL file for the first time, the outline sidebar is empty. If i change the language mode to COBOL and then return to ACUCOBOL, the outline sidebar become filled.

I open the file with ACUCOBOL Language Mode:
**
![immagine](https://user-images.githubusercontent.com/1749453/53324361-e4904280-38e0-11e9-8473-0a548b4cf542.png)
**

Change to COBOL and then return to ACUCOBOL:
**
![immagine](https://user-images.githubusercontent.com/1749453/53324647-a3e4f900-38e1-11e9-9051-392477076bd9.png)
**

**Comment by spgennard** [comment]
Thanks, I think I know what this issue will be.   

I will look at getting a fix out tonight.

**Comment by ebat79** [comment]
With the latest update, the problem has been solved. Thank you!

**Comment by spgennard** [comment]
Great, I also added some shortcut keys to allow you to select the AcuCOBOL format.
