### ISSUE TITLE
Paragraph detection

### ISSUE THREAD

**Issue by chupi33** [spgennard/vscode_cobol#54]
Hi

if there is something in the 6 first characters of paragraph's declaration, this one isn't detected

**Comment by spgennard** [comment]
Can you give us an example and are talking about the outline view?

**Comment by chupi33** [comment]
of course !!!

with comments, no trace of paragraph in search result
![With comments](https://user-images.githubusercontent.com/4981101/55176640-cc327280-5181-11e9-8dd2-5806011ab91b.png)

without comments, paragraph appears in search result
![Without comments](https://user-images.githubusercontent.com/4981101/55176644-cccb0900-5181-11e9-95ef-8d31911bb241.png)

thxs
