### ISSUE TITLE
Show definition DCLGEN

### ISSUE THREAD

**Issue by chupi33** [spgennard/vscode_cobol#56]
Hi

i've declared copybook emplacement

on copy declaration i can do "show definition"

is it possible to implement the same thing on "exec sql include" which declare database structure(DCLGEN). Those declarations are in copybook too

By the way, great job with this plugin !! 👍

**Comment by spgennard** [comment]
The best I can do is allow "exec sql include fred end-sql" to open fred as if it is a copybook.

If the "exec sql" is spread over multiple lines it won't work.

**Comment by chupi33** [comment]
the best you can do is perfect for us
thxs

**Comment by chupi33** [comment]
i think there is a mistake
that's declared like that 
"exec sql include fred end-exec." 
not 
"exec sql include fred end-sql."

**Comment by chupi33** [comment]
Thxs 👍

**Comment by chupi33** [comment]
Hello

I'm sorry, but this problem has come up again
I try to add double quotes around (like : EXEC SQL INCLUDE "DCOCPDEC" END-EXEC.) but it's KO

**Comment by spgennard** [comment]
To check out the issue
