### ISSUE TITLE
Go To/Peek definition of PERFORM/THRU paragraph wrong

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#62]
Ctrl+Click (or Ctrl+Hover) on `EXAMPLE-EXIT` of `PERFORM` line, takes me to the first PERFORM line with that paragraph. The Outline view is able to properly detect the `EXAMPLE-EXIT` paragraph and jump directly to it. These providers must not be using the same backing data.

Source:
```cobol
       MAIN.
           PERFORM EXAMPLE-ENTRY THRU EXAMPLE-EXIT.
           STOP RUN.
       EXAMPLE-ENTRY.
           DISPLAY "HELLO".
       EXAMPLE-FALLTHROUGH.
           DISPLAY "WORLD".
       EXAMPLE-EXIT.
           EXIT.
```

Screenshot:
![image](https://user-images.githubusercontent.com/675956/55641865-8b93b400-5794-11e9-938b-8ba97ed72e47.png)

**Comment by spgennard** [comment]
fyi - the source definition provider used a very crude tokenizer, whereas the outlook provider, which
       was created much later used a mini-cobol parser, which turned out to be more accurate than the
       tokenizer.

So yes, I had two different mechanisms but I spent tonight removing the tokenizer mechanism and
replacing it with the mini-cobol parser, so this issue is now resolved.
