### ISSUE TITLE
Indexes not being picked up by parser

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#65]
Cannot go to definition for index defined on storage occurrence.

Example:

```cobol
       01  ws-table.
           02  ws-entry occurs 5 times indexed by ws-i pic x.
       main.
           set ws-i to 1.
           display ws-entry (ws-i).
```

Ctrl+Hover over `ws-i` doesn't link.

**Comment by spgennard** [comment]
Applied a crude parser change, so this will now work.

```cobol
       working-storage section.
       
       01  ws-table.
           02  ws-entry occurs 5 times indexed by ws-i pic x.
       
       procedure division.
       
       main.
           set ws-i to 1.
           display ws-entry (ws-i).
```

(note: working-storage/procedure division markers have to be present for the outliner to pick it up)

**Comment by kabel** [comment]
Thanks for knocking this out so quickly. Unfortunately, it doesn't work with the way I format these lines. I should have provided a better example that matched my scenario:

```cobol
       working-storage section.

       01  ws-table.
           02  ws-entry                occurs 5 times 
                                       indexed by ws-i 
                                                   pic x.
       procedure division.

       main.
           set ws-i to 1.
           display ws-entry (ws-i).
```

If I get a spare moment, I'll see if I can build on your work and submit a PR.

**Comment by spgennard** [comment]
The parser works "line by line" and all the processing for a variable is in the same the place, so to handle it quickly the search for "indexed by" was tagged onto the same bit of logic

My fix will be to make them independent of each other.

**Comment by spgennard** [comment]
My fix will work providing "indexed by" is on the same line as the variable.

Creating a proper parser is on my backlog :-)
