### ISSUE TITLE
inline comment configuration

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#78]
ACUCOBOL has `|` as line comment, it would be news to me if they added the iso variant `*>`  later (if they did it must be done very recently).
GnuCOBOL supports both, but the acu variant only with a given option `-facu-comment` (or, I guess, `-std=acu`) - as the pipe is not reserved otherwise in any COBOL dialect that I'm aware of it may or may not be reasonable to add it to the GnuCOBOL variant (OpenCOBOL did not support it).

**Comment by GitMensch** [comment]
related:
https://github.com/spgennard/vscode_cobol/blob/master/acucobol.configuration.json#L3
https://github.com/spgennard/vscode_cobol/blob/master/gnucobol.configuration.json#L3

**Comment by spgennard** [comment]
I can confirm the ACUCOBOL compiler does accept *> without any compiler options.

I will checkout gnucobol/cobol-it compiler later.

**Comment by spgennard** [comment]
I have tried out the gnucobol compiler and it handles these comment style without any options.

Therefore, as far as I can see no reason to change the defaults, as using "fixed" comments won't 
difference source formats.

**Comment by GitMensch** [comment]
@spgennard It seems I did not make myself clear and confused you.

> I can confirm the ACUCOBOL compiler does accept *> without any compiler options.

Interesting. This must be a very recent change. Historically ACUCOBOL-GT added the `|` as inline comment (must have been in the nineties). Therefore my *suggestion* stays to change the inline comment with this style to the old style (I *guess* the new version did not drop the pipe to not break year old sources). I didn't checked but the inline comment configuration may be an array, in this case I suggest to use the pipe as first one and the 2002+ standard style as second (*most acu sources that use inline comments will use the pipe).

> I have tried out the gnucobol compiler and it handles these comment style without any options.

´*>` is at least supported since 2008 in OpenCOBOL (likely before). GnuCOBOL added *additional* parsing for the acu format ="pipe", but only upon explicit request. Therefore you *may* want to add the pipe as second (if its an array configuration), but it is completely fine to leave it as-is.

**Comment by spgennard** [comment]
Thanks
