### ISSUE TITLE
VS.Code always detects encoding as Windows-1256

### ISSUE THREAD

**Issue by crazycodr** [spgennard/vscode_cobol#85]
Hi,

I tried various things and i'm starting to think that the problem is with the Cobol Editor itself and not VS.Code.

If i created a `settings.json` with the following content:

```json
{
    "files.encoding": "utf8"
}
```
It should always open and save my files using UTF8 encoding. It works with all my other languages and editors inside VS.Code except for this extension. For example. If i create a PHP file with:

```php
Ceci est un test avec des accents

Accepté
Regrêts
Décès
```

And reopen it, it will not attempt to open it with Windows-1256. How i see this is simple, launch the "Change Encoding" command with "Save with encoding" and the palette with all encodings **doesn't** show me "Guessed from content: Windows 1256".

But when i do this with Cobol files, it constantly guesses the encoding to be "Windows 1256", this forces me to switch my entire workspace to use:

```json
{
    "files.encoding": "windows1256"
}
```

Is there a reason for this?

**Comment by spgennard** [comment]
We set:

```json
            "[COBOL]": {
                "files.autoGuessEncoding": true,
```

If you want to have you own for COBOL, can follow the guide @ 
  https://flaviocopes.com/vscode-language-specific-settings/

and override this.

For reference here all the other settings:

```json
            "[COBOL]": {
                "files.autoGuessEncoding": true,
                "editor.autoIndent": false,
                "editor.insertSpaces": true,
                "editor.formatOnType": true,
                "editor.rulers": [
                    6,
                    7,
                    72
                ],
                "editor.detectIndentation": false,
                "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?"
            },

```

**Comment by spgennard** [comment]
Using files.autoGuessEncoding=true, allows sources to be saved in Unicode + BOM
and this is picked up various COBOL Compilers.

Therefore if you want to override at a per user/workspace level use the above.

**Comment by crazycodr** [comment]
Ok i also had to force autoGuessing to `false`:

```json
{
    "[COBOL]": {
        "files.encoding": "utf8",
        "files.autoGuessEncoding": false
    }
}
```

If i didn't force autoGuessEncoding to false, it would still try to detect it. Funny thing though, the accents are now showing ok but going into "Save with Encoding" still shows that it guessed "Windows-1256" :P

At least, all ends well now.

**Comment by spgennard** [comment]
I add something to the docs if you want
