### ISSUE TITLE
Feature Request: In outline, assume copybook break out of current paragraph

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#87]
Copybooks that appear at the end of a procedure paragraph are nested under that paragraph in the outline. This is mostly undesirable nesting.

Example:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. hello-world.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-FOO-FIELD-A                          PIC X.
       PROCEDURE DIVISION.
       main-processing SECTION.
       mainline-paragraph.
           STOP RUN.
           COPY "main-helpers.cbl"
```

Actual Outline:
...
* main-processing section (method)
  * mainline-paragraph (method)
    * COPY "main-helpers.cbl" (file)

Expected Outline:
...
* main-processing section (method)
  * mainline-paragraph (method)
  * COPY "main-helpers.cbl" (file)

**Comment by spgennard** [comment]
Sorry but I disagree, the COPY file is within mainline-paragraph, therefore it is a sub-node of it.

**Comment by kabel** [comment]
Yes, this is kind of an opinionated request. It's mainly bothersome when the copybook defines it's own paragraphs that would _not_ be nested in a paragraph. In general, the `COPY` statement is a compiler-directing statement and it not tied to the structure of the outline.

It gets more confusing when using `EXIT` paragraphs which logically shouldn't have anything nested in them after the exit.

**Comment by spgennard** [comment]
I can't see any way of controlling the actual nesting, as this is provided by vscode.   

I just say where the object starts/end and because it is inside paragraph, the vscode outline nests it automatically.

The best I can do is provide an option to not include the copy verb in the outline view.

**Comment by spgennard** [comment]
NOTE: lines after a COPY statement in the paragraph are attributed to the outer section/div,
so the "coboleditor.copybooks_nested" is not perfect but it might be good enough for you.

**Comment by kabel** [comment]
Yeah, I think that's good enough for me.
