### ISSUE TITLE
Feature Request: Recursively parse discovered copybooks for go-to-definition symbols

### ISSUE THREAD

**Issue by kabel** [spgennard/vscode_cobol#88]
This should allow a workspace/project that is split into many copybooks to quickly jump to the storage and procedures of any referenced file. Using the logic that handles go-to-definition for COPY statements, after the file is resolved, add the file to a list and parse it for adding the discovered methods and fields to go-to-definiation storage.

Example:

__file:__ `main.cbl`
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. fooimpl.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
           COPY "lib/ws-foo.cbl".
       PROCEDURE DIVISION.
       main-processing SECTION.
       main.
           MOVE "BAR" TO WS-FOO-FIELD-A.
           PERFORM FOO-DO-SOMETHING.
           STOP RUN.
           COPY "lib/proc-foo.cbl".
```

__file:__ `lib/ws-foo.cbl`
```cobol
       01  WS-FOO-FIELD-A                          PIC X.
```

__file:__ `lib/proc-foo.cbl`
```cobol
       FOO-DO-SOMETHING.
           DISPLAY "FOO: " WS-FOO-FIELD-A.
       FOO-EXIT.
           EXIT.
```

Expectation:
* Ctrl+Click on `WS-FOO-FIELD-A` in `main.cbl` navigates to `lib/ws-foo.cbl:1`
* Ctrl+Click on `FOO-DO-SOMETHING` in `main.cbl` navigates to `lib/proc-foo.cbl:1`

Bonus points for nesting the symbol definitions in the copybooks under the outline for the respective (file) nodes.

**Comment by spgennard** [comment]
You don't need this plugin todo this, you can do this by creating a ctags file, for example:

    ctags -R -f .tags *.cbl lib/*

The install a ctags plugin, for example: jaydenlin.ctags-support

Then select the item you want to navigate too and press ctrl-t

For example:

![ctags_with_cobol](https://user-images.githubusercontent.com/5991192/64477075-f9eb0100-d18e-11e9-9f8e-3c553b31b6f2.gif)

**Comment by spgennard** [comment]
I am thinking about consuming the ctag file in the plugin, to make the use of ctags easier and not dependant on extra plugins.

**Comment by kabel** [comment]
I appreciate that an external tool like ctags _could_ be leveraged for this kind of functionality. However, it does come with some major drawbacks without stronger vscode integration:

* It requires an external binary to be properly installed and configured outside of VS Code (difficult in a cross-platform environment to support)
* Recursive `-R` support doesn't follow the same copybook locating logic your extension configuration provides via `coboleditor.copybookdirs`
* Needs additional `ctags` configuration/parameters to mirror the `coboleditor.copybookexts` extension configuration into `--langmap=` option
* Requires additional, external tooling to watch the workspace for changes to resolved copybook files to trigger a re-invoke of `ctags`
* The suggested vscode interface `jaydenlin.ctags-support` doesn't understand word boundaries and requires full symbol selection to properly locate a symbol with `-`
* Provides a similar, but different, experience than _Go To Definition_ or _Peek Definition_
* Not integrated with the _Outline_ or _Go To Symbol in File_ (Ctrl+Shift+O)

**Comment by spgennard** [comment]
> It requires an external binary to be properly installed and configured outside of VS Code (difficult in a cross-platform environment to support)
I could use the javascript converted ctags implementation, so the need for this would be removed

> Recursive -R support doesn't follow the same copybook locating logic your extension configuration provides via coboleditor.copybookdirs
> Needs additional ctags configuration/parameters to mirror the coboleditor.copybookexts extension configuration into --langmap= option

Again, if I either generated ctags or used an existing ctags generator (in javascript) this could be handled

> - The suggested vscode interface jaydenlin.ctags-support doesn't understand word boundaries and requires full symbol selection to properly locate a symbol with -

However, the extension jtanx.ctagsx does

> Provides a similar, but different, experience than Go To Definition or Peek Definition
The extension jtanx.ctagsx works better than the first suguestion.

> Not integrated with the Outline or Go To Symbol in File (Ctrl+Shift+O)
Outline/Goto symbol in file are both "current" file based, so including all the workspace based symbols in this view would be wrong and make the outline view usable in large workspaces.

**Comment by spgennard** [comment]
I am thinking about how I can extend the symbol resolver to look into symbols found in copybooks.

**Comment by spgennard** [comment]
To enable change at the moment you will need to enable the ```coboleditor.copybook_search```
settings.

**Comment by kabel** [comment]
Awesome! It's not super speedy on my production code with many copybook dirs to search and over 60 different files, but ctrl+click did eventually (within 5-10 seconds) take me to where I wanted to be.

**Comment by spgennard** [comment]
> Awesome! It's not super speedy on my production code with many copybook dirs to search and over 60 different files, but ctrl+click did eventually (within 5-10 seconds) take me to where I wanted to be.

I expected it to be not as performant as I would like due to the fact is does not cache anything and traverses all the tokens.   

The later has just been fixed, so it might make a little bit of a difference but until I apply some caching it will not be a perfect solution.

**Comment by spgennard** [comment]
Any update on the performance?

**Comment by kabel** [comment]
Not a significant change in performance. Going to the same symbol over-and-over seems a bit quicker. In general this is still hanging the extension host for an uncomfortable amount of time. Logs/profiles at https://gist.github.com/kabel/45d97c5320237e1982904e2f41db6dea#file-vscode-window-log

**Comment by spgennard** [comment]
Added, some more changed.

It should be better with sections/paragraphs.

**Comment by spgennard** [comment]
Any comments on recent changes?

PS: I've abandoned caching in workspace and now just use in-memory caching.

This is because the workspace caching was slow and had a problem with circular references.

**Comment by kabel** [comment]
I wish I had better news or more data I could share with you. There is nothing in the visible output/logs to share why things are slow with the feature turned on. The extension host isn't hanging (or logging warnings about it) anymore.

I had to turn this feature flag off in my largest production code workspace, because it was too slow to be of any value and caused a regression in the speed I could go-to-definition for COPY statement file tokens. Just toggling the feature and using this specific use case goes from immediate jump to file to seeing the VS Code "loading" indicator in the tab bar for a solid 30 (first invoke) to 15 (second invoke) before the jump to the right file.

Is there any valuable information I can gather for you? I manually recorded some [profiles](https://drive.google.com/open?id=1a5C7cJmsE9coUP2jauF91DYHR8qt2yhh) from the Chrome Developer Tools during testing this one use case. They are pretty big files (37 MB, 16 MB, 4 MB). I'm not sure if those are helpful. I can't share the confidential workspace source files.

**Comment by spgennard** [comment]
The performance analysis I did, found different results but it could be due to recent changes
that I did.   

I moved away from using workspace on-disk cache to an in-memory cache (recently used style)

Next, I noticed the outline view does a lot of "quicksorts" on the items, so if you have a lot
items, it takes a very long time.

So, I have added a setting called "coboleditor.outline" that allows it to be either turned off,
(allowing other plugins such as "symbols from ctags" to be used), on (default), partial (no paras)
and slim (no vars & para/sections).

I was thinking about adding an "auto" that only includes some of the items eg: 1 in x number of sections/paragraphs for example.

note: this does not affect the searching just the contents of the outline view.

**Comment by kabel** [comment]
Thank _you_ for working on this hard, IDE-like feature!

Would it make sense to adjust the caching approach and start a file watcher when a cobol workspace is loaded and do the quickparse stuff into memory (or workspace) cache. Then, only use the cache when a definition request comes in (no calls to `fs` module)? The cache would then be refreshed when a file watcher change is signaled.

Seems like parsing/validating the cache for every definition request takes a bit of time in large workspaces. I'd rather have stale cached results than have to wait 30 seconds for fresh, fully-re-parsed workspace.

**Comment by spgennard** [comment]
Performance might not be ideal but I plan to migrate the code to an "out-of-process" model that will
eventually, they have less impact on the editing experience.

So, for now, I will close the issue and if needed specific issues can be addressed as another issue
number.
