### ISSUE TITLE
Autocomplete suggestion using tab key

### ISSUE THREAD

**Issue by mllamazares** [spgennard/vscode_cobol#89]
When I start typing and I want to autocomplete the keyword, but if you press the Tab key, it adds spaces until the end of the line. It just works with the Enter key or by clicking on the suggestion pop-up. It hasn't happened to me with other syntax highlighters. Is there any way to modify this?

**Comment by spgennard** [comment]
Adding spaces to the end of the line will occur if your cobol editor tabstop settings include a far right margin number.

Excess spaces can be removed on saving via a editor config setting.

The behaviour is different due to this extension changing the tab/detab key.

You can always change this back to the default.

**Comment by mllamazares** [comment]
Thanks for the reply! I've set `"coboleditor.tabstops": [0],` so now it doesn't insert spaces until the end of the line, but the tab key still doesn't accept the suggestion (like Enter does). Could you tell me how do I configure its behavior back to default, please?

**Comment by spgennard** [comment]
You can change the keybindings:

https://code.visualstudio.com/docs/getstarted/keybindings

For example:

      { "key": "tab", "command": "tab",  "when": "editorTextFocus && editorLangId == COBOL" }

where editorLangId can also be OpenCOBOL, GnuCOBOL, ACUCOBOL

**Comment by mllamazares** [comment]
I ended up installing the Multi Command extension:
https://github.com/ryuta46/vscode-multi-command

In settings.json I added this:
`"multiCommand.commands": [
        {
            "command": "multiCommand.okandtab",
            "sequence": [
                "acceptSelectedSuggestion",
                "tab"
            ]
        }
    ]`

And in keybindings.json
`   { 
      "key": "tab", 
       "command": "multiCommand.okandtab",  
       "when": "editorTextFocus && editorLangId == COBOL" 
    }`
