### ISSUE TITLE
coboleditor.tabstops not working

### ISSUE THREAD

**Issue by mllamazares** [spgennard/vscode_cobol#90]
I've added the following lines to my Settings file:

`    "coboleditor.tabstops": [
        8,
        12, 
        45
    ],`

But after saving, it still show the rulers at the default positions: 7, 8, 73:

![image](https://user-images.githubusercontent.com/5461023/64928486-2d75fd00-d819-11e9-9e6c-70ef77f6e70d.png)

**Comment by spgennard** [comment]
Sorry, I think you have miss understood the purpose of setting.  The settings is to override the tab/tabs top key with Cobol like behaviour, not to reformat any embedded tabstop characters or reformat given a different tab setting.

**Comment by mllamazares** [comment]
Ok, thanks @spgennard! Then, there is no way to do what I want? If I change the settings the `"editor.rulers": [80,120]` parameter, it still does not reflect the changes.

**Comment by spgennard** [comment]
Sorry, what you need is a "reformat" tab options that understand embedded COBOL tab.

You might be able to get away with converting the tabs to spaces and using column-based editing to re-org it (multi-cursor stuff).
