### ISSUE TITLE
Better Comments extension compatibility 

### ISSUE THREAD

**Issue by mllamazares** [spgennard/vscode_cobol#91]
I have installed Better Comments extension:
https://marketplace.visualstudio.com/items?itemName=OmarRwemi.BetterComments

It works with other languages, but when I try to use it with COBOL syntax highlight enabled, it doesn't work:

**Bash**
![image](https://user-images.githubusercontent.com/5461023/64947122-9d65a100-d874-11e9-930a-1781d8446fa0.png)

**COBOL**
![image](https://user-images.githubusercontent.com/5461023/64947060-8030d280-d874-11e9-87f2-82fd34da6a64.png)

Note that Better Comments extension does have COBOL syntax support.

**Comment by spgennard** [comment]
The issue is with OmarRwemi.BetterComments extension not understanding COBOL comments.

     > Works with C#, F#, VB.NET, C/C++, JavaScript, Python, HTML, and XAML.

**Comment by mllamazares** [comment]
Sorry, I put the wrong link. This is the one:
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

In Supported Languages there is COBOL included.

**Comment by spgennard** [comment]
Again, this plugin does not support this type of comment, it only supports "*>" comments.

Take a look @  https://github.com/aaron-bond/better-comments/blob/master/src/parser.ts

You will see:

```javascript
		case "COBOL":
				this.delimiter = this.escapeRegExp("*>");
				break;

```

**Comment by spgennard** [comment]
I've done a pull request for changes see: https://github.com/aaron-bond/better-comments/pull/183

**Comment by spgennard** [comment]
Please note, the development of above appears to have stagnated, this the second pull request for Cobol support for fixed line comments.
