### ISSUE TITLE
Unable to parse Copybooks without extension

### ISSUE THREAD

**Issue by ebat79** [spgennard/vscode_cobol#94]
![immagine](https://user-images.githubusercontent.com/1749453/67586354-b9047700-f751-11e9-8d21-39edb9c62a65.png)

The file "GCPRMLOC" exist in "coboleditor.copybookdirs" and have no extension.
If i will rename it with an extension work.

My "coboleditor.copybookexts" looks like this:
```

		// COBOL CopyBook Extensions
		"coboleditor.copybookexts": [
			"",
			"cpy",
			"CPY",
			"scr",
			"SCR",
			"cbl",
			"CBL",
			"txt",
			"TXT",
		],
```

**Comment by cobolcowboy** [comment]
I'm also running into this issue. Copybooks without an extension are not parsed.

**Comment by ebat79** [comment]
Relative path seems not to work...
![immagine](https://user-images.githubusercontent.com/1749453/68877197-f8493680-0705-11ea-8b4d-7c968ac4bdcd.png)
When caching content, can you add a log when a directory of "coboleditor.copybookdirs" is found or not ?
![immagine](https://user-images.githubusercontent.com/1749453/68877809-f764d480-0706-11ea-9568-807a0fdf92d4.png)

**Comment by spgennard** [comment]
> Relative path seems not to work...
> ![immagine](https://user-images.githubusercontent.com/1749453/68877197-f8493680-0705-11ea-8b4d-7c968ac4bdcd.png)
> When caching content, can you add a log when a directory of "coboleditor.copybookdirs" is found or not ?
> ![immagine](https://user-images.githubusercontent.com/1749453/68877809-f764d480-0706-11ea-9568-807a0fdf92d4.png)

A workspace has one or more directories, so using relative directories will have completely unexpected search paths.    I am not convinced this is a good idea but I will look at the impact of
this.

**Comment by cobolcowboy** [comment]
Perhaps at the very least include a note in the setting description saying they should be absolute paths. I also tried using relative paths.

**Comment by spgennard** [comment]
The working/workspace set of directories is shown, along with any "invalid" directories.

This is because a workspace can include multiple directories.. so including "..\\c" may well be invalid 
or actually be an unexpected directory.

I am not specifically banning it but as the directories are now shown, at least it is visible
what directories are being used?

One last point,  I must also stress these are non-portable directories, if you are multi-platform it will
also, be a problem.

**Comment by spgennard** [comment]
The first 25 lines by default are used to determine if the file is COBOL or not, this can now be changed by changing the "coboleditor.pre_parse_line_limit" settings.

The list of directories to be searched is now shown plus the ones that are invalid are also shown.

I am now at an impasse on where this issue can be taken, so without a concrete example, I
will close it.

Feel free to open up another issue with a reasonable example when you have it.
