### ISSUE TITLE
Go to entry points

### ISSUE THREAD

**Issue by cobolcowboy** [spgennard/vscode_cobol#95]
Goto/Peek Definition doesn't work with CALLs that reference entrypoints from copybooks.

**Comment by spgennard** [comment]
You can you ctags to navigate around today.

**Comment by cobolcowboy** [comment]
I'm not super familiar with ctags but I haven't been able to get it to work with entry points. It just says "No related tags are found". I see that the file that includes the entry points was parsed and there are tags from the file but it doesn't seem to recognize entry points.

**Comment by spgennard** [comment]
I will have a look and see what I can do.. I have not yet decided which of two routes to take.

More information, as I progress.

**Comment by cobolcowboy** [comment]
Happy to try to help if you have any ideas on how to resolve this issue.

**Comment by spgennard** [comment]
If you are working in a workspace, you can enable the below option and it will help you.

At the moment in time, after enable the setting (changing to "on"), you will need to save the workspace, exit vscode and start vscode again.

This is because I've not yet wired up any dynamic configuration change actions, hence you need to save/exit/reload.

![image](https://user-images.githubusercontent.com/5991192/68340269-0253af80-00de-11ea-93dd-53672f5cdd93.png)

**Comment by cobolcowboy** [comment]
I've enabled this. It seems like once I've opened the copyfile I'm trying to peek/goto, I then can peek/goto from other files (including entries). But until I open the file, even if it is in my copybook search paths, it won't find the file or entry calls.

**Comment by spgennard** [comment]
It sounds like your cache directory has not been setup.   If you execute the command below:

![image](https://user-images.githubusercontent.com/5991192/68401528-cd913800-0171-11ea-8340-322b2c96d3f1.png)

What files do you have in the workspace/.vscobol_cobol directory?

note: the name of the command will change soon.

**Comment by cobolcowboy** [comment]
I ran "Process All Copybook FIles" and the issue persists. 

My .vscode_cobol directory:
```
$ ls                                                                
2a9ec8888b3d5d13f949ad39c2a1f1a4c69d7defa86d2f4ebad93a0c130d1e83.sym
4064839a4010a8b798dcf4e117bb37cacdcfe4f7867dceda1eee4035e3a70a69.sym
4820a34c273ff86a7927d24b0d2b66717a0ab019de419e09ff70f75895113497.sym
5ad0fcba53eb560dafed68f16ff6df97844ad5ea624d720f0e0145fd0f42710a.sym
5b7e856e04e10c1d68629f515c58a499fca17ed29de03b9670b0b6352da1f50c.sym
82c203a954c3dbbd49882c1e71f35e63b244399ff9c683d6e5540ec0c34ff1fb.sym
94901e0fcf6c1a9e4c18c4dc0f03ac2d21d5c5e8350be0bb38a3aa4aeebdf25e.sym
9fc64217fc50e68c03796f3b3b2eb0f34e759c2ee74cdee8ddbf792feba1b5f1.sym
a8899ede3117fa75a618b5ab2cc77c3eede1aca1d54f795a174c9eecb792c223.sym
acb2facf2793e7b0b90f6ad9b00524373b7fa5c3d07cebb7b682cd8bbebb9b88.sym
bba2d8570ca66ba06643d35f95f08dce6f9996dd8518faffa8b32bfc9d790ed8.sym
c05733792a27c3b010f81007e605101e1f9efe9bd3e59686e8fe3caa7d075a31.sym
c2dabdcf5dba990ed511f730e62aa0e3ab0b5f0364c0e5165cdec343caf9b664.sym
cdfebbb9af5d632192ec9ce785fb8413464c65e076d63fd3061e709346204669.sym
d42162ea0f5070c0677b0bd9c47014c1de2c73a3391c12ac7df61a92e25ae7cf.sym
deca7da11fbe4e1ddf43364bc3a29a428c320ae49dd2613dd08d592847979914.sym
e45d85581b4c298341ab48290388c42216775b5b516dd4f1d415515e7bfa4262.sym
e5cfc513e62691cf3ef61319b6b16c031de0f5c1c60ddf490a7ecdadeb229491.sym
f17f0849a4e615c34a96563dd54edc461ff288a53627f32d5a3dc976a8e13341.sym
f4a5a028a2cf48c4b19bee5fb050ae434f09d5a480661310aa9bd7dccb0afa9b.sym
fb87ab43e4ce5fa0b5a1e2f59b71728951369de5d40a8ca8c478309815162340.sym
globalsymbols.sym       
```

**Comment by spgennard** [comment]
I think you will need to provide a more specific example because my simple examples work.

**Comment by spgennard** [comment]
fyi - I've added a "COBOL: Dump meta" command, that might help us understand if your programs/entry-points have been parsed.

**Comment by cobolcowboy** [comment]
I don't see the file I would be expecting to see in the metadata dump. It is in the same directory as other files I do see listed. I'm going to try to put together a sample for you when I have a moment.

**Comment by cobolcowboy** [comment]
I've also noticed that Goto/Peek won't find a symbol if the capitalization is different, and unfortunately we have a lot of files that are written in different styles.

**Comment by cobolcowboy** [comment]
it looks like i'm still having issues with peeking symbols with different capitalization after 59e0344

**Comment by cobolcowboy** [comment]
I've also noticed that if I have a copybook for example named METADATA.cpy:
` 01  META-SWITCH  EXTERNAL.
    10  META-SW PIC 9 OCCURS 40.`
and in another file's working storage section I have:
`COPY METADATA`
I cannot goto/peek into METADATA.cpy from there. However, if there is a reference to `META-SWITCH` or `META-SW` the goto/peek works.

**Comment by spgennard** [comment]
> I've also noticed that if I have a copybook for example named METADATA.cpy:
> 
> ```cobol
>  01  META-SWITCH  EXTERNAL.
>     10  META-SW PIC 9 OCCURS 40.
> ```
> 
> and in another file's working storage section I have:
> `COPY METADATA`
> I cannot goto/peek into METADATA.cpy from there. However, if there is a reference to `META-SWITCH` or `META-SW` the goto/peek works.
> 
> EDIT: This isn't much of an issue tbh since these are the filenames and I can just Ctrl+P to get to them actually. However it would be nice to have a consistent experience as I was setting up another developer with this extension today and this led to confusion.

I fixed something simular to this but it was due to not being in a workspace.

**Comment by spgennard** [comment]
Okay, time to close as the feature has been implemented.  

Though I understand it is early days with it, so feel free to raise issues with a good example, as this really does save me a lot of time.
