### ISSUE TITLE
command 'cobolplugin.processAllCopybookFiles' not found

### ISSUE THREAD

**Issue by cobolcowboy** [spgennard/vscode_cobol#97]
I'm getting this error notification when attempting to run this command via the Command Palette. Although my CPU spikes as if it is processing.

**Comment by cobolcowboy** [comment]
Its taking a long time to process (this is fairly large codebase), this has been running for 30 minutes now.

**Comment by spgennard** [comment]
You will need to turn coboleditor.Cache_metadata to "off" or "partial", as unfortunately parsing lots of sources takes time.

If you turn it off, then you use other forms of source-to-source navigation.

**Comment by spgennard** [comment]
Changed the default to only process files in the workspace when caching is "on"
