### ISSUE TITLE
No symbol found in the document 

### ISSUE THREAD

**Issue by Tony-Gremillon** [spgennard/vscode_cobol#98]
Hello

I'm in version 5.7.16

We have the message "No symbol found in the document 'xxxxxxxx.cbl' " in most part of our programs.
It seems that if the IDENTIFICATION DIVISION. is too far away in the program, the symbols are not detected.
I made some tests deleting some lines and the symbols reappear !

Unfortunatly, most of our programs begins with a lot of commentary and the IDENTIFICATION DIVISION. is below them

Thank you

**Comment by magictony31** [comment]
It works ! Thx

**Comment by spgennard** [comment]
Great
